### ISSUE TITLE
NPE on ObjectMapper

### ISSUE THREAD

**Issue by edethoor** [springfox/springfox#1056]
I use springfox-swagger2 (2.2.2) on a Spring boot Application (1.3.0.RELEASE) with the spring-boot-starter-web in my pom.xml and i get a NPE on objectMapper with this stacktrace : 
```
Caused by: java.lang.NullPointerException: null
	at springfox.documentation.schema.property.OptimizedModelPropertiesProvider.beanDescription(OptimizedModelPropertiesProvider.java:315) ~[springfox-schema-2.2.3-SNAPSHOT.jar:2.2.3-SNAPSHOT]
	at springfox.documentation.schema.property.OptimizedModelPropertiesProvider.propertiesFor(OptimizedModelPropertiesProvider.java:115) ~[springfox-schema-2.2.3-SNAPSHOT.jar:2.2.3-SNAPSHOT]
	at springfox.documentation.schema.property.CachingModelPropertiesProvider$1.load(CachingModelPropertiesProvider.java:52) ~[springfox-schema-2.2.3-SNAPSHOT.jar:2.2.3-SNAPSHOT]
	at springfox.documentation.schema.property.CachingModelPropertiesProvider$1.load(CachingModelPropertiesProvider.java:50) ~[springfox-schema-2.2.3-SNAPSHOT.jar:2.2.3-SNAPSHOT]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527) ~[guava-18.0.jar:na]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319) ~[guava-18.0.jar:na]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282) ~[guava-18.0.jar:na]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197) ~[guava-18.0.jar:na]
```

I tried to use version 2.2.3-SNAPSHOT of springfox-swagger2 but i still have this NPE.

**Comment by dilipkrish** [comment]
Create an `ObjectMapper` bean; it looks like there is none found :confused:

**Comment by edethoor** [comment]
I think it's not the good solution because normaly Spring Boot auto-configuration with starter-web create one.

**Comment by edethoor** [comment]
I continued my investigations and it turns out that the listener ```ObjectMapperConfigured``` is never register with the ```ApplicationEventPublisher``` because i never had a bean of type ``` RequestMappginHandlerAdapter``` in this method of the ```ObjectMapperConfigurer``` class : 
```
@Override
  public Object postProcessBeforeInitialization(Object bean, String beanName) throws BeansException {

    if (bean instanceof RequestMappingHandlerAdapter) {
      RequestMappingHandlerAdapter adapter = (RequestMappingHandlerAdapter) bean;
      adapter.setMessageConverters(configureMessageConverters(adapter.getMessageConverters()));
    }
    return bean;
  }
```

If i don't use springfox-swagger2, my application start well and i have a bean of type ```RequestMappingHandlerAdapter``` (verified with the endpoint ```/beans``` provided by actuator) : 
```
{"bean":"requestMappingHandlerAdapter","scope":"singleton","type":"org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter","resource":"class path resource [org/springframework/boot/autoconfigure/web/WebMvcAutoConfiguration$EnableWebMvcConfiguration.class]","dependencies":[]}
```

Is it possible springfox want to make some things before this Bean is defined ?

**Comment by edethoor** [comment]
I forgot to mention that i use spring security in my Boot application.
