### ISSUE TITLE
ArrayIndexOutOfBoundsException when using custom Maps

### ISSUE THREAD

**Issue by ericdahl** [springfox/springfox#1062]
When using a custom `Map` type that has only one type parameter, such as:

```java
public class CustomMap<T> extends LinkedHashMap<String, T> { }
```
The API generation results in an error with 2.2.2:
```
java.lang.ArrayIndexOutOfBoundsException: 1
    at java.util.Arrays$ArrayList.get(Arrays.java:3841)
    at springfox.documentation.swagger2.mappers.ModelMapper.typeOfValue(ModelMapper.java:97)
    at springfox.documentation.swagger2.mappers.ModelMapper.mapProperties(ModelMapper.java:85)
    at springfox.documentation.swagger2.mappers.ModelMapper.mapModels(ModelMapper.java:62)
    at springfox.documentation.swagger2.mappers.ModelMapper.modelsFromApiListings(ModelMapper.java:163)
    at springfox.documentation.swagger2.mappers.ServiceModelToSwagger2MapperImpl.mapDocumentation(ServiceModelToSwagger2MapperImpl.java:49)
    at springfox.documentation.swagger2.web.Swagger2Controller.getDocumentation(Swagger2Controller.java:75)
...
```
due to logic in `ModelMapper` that assumes that any subclass of `Map` has two type parameters.

Reproduce (with [test repo](https://github.com/ericdahl/boot-swagger-exception/)) by:
1. `git clone https://github.com/ericdahl/boot-swagger-exception.git`
2. `cd boot-swagger-exception`
3. `mvn spring-boot:run`
4. [http://localhost:8080/v2/api-docs](http://localhost:8080/v2/api-docs)

**Comment by dilipkrish** [comment]
@ericdahl :metal: for creating a repo that demonstrates the issue! might not be a couple of weeks till I get to this issue
