### ISSUE TITLE
@EnableSwagger2 failed to load with Spring 3.0.6

### ISSUE THREAD

**Issue by ragzisme** [springfox/springfox#1091]
I am trying to setup Spring 3.0.6 with Swagger 2(tried 2.1.2 and 2.2.2) but the startup is failing with the error below.

I debugged it to notice that it is failing while parsing the @EnablePluginRegistries of the SpringfoxWebMvcConfiguration class. How do i fix this? 

[2015-12-11_13:58:38.040] ERROR: org.springframework.web.context.ContextLoader - Context initialization failed
java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy
        at sun.reflect.annotation.AnnotationParser.parseClassArray(AnnotationParser.java:653)
        at sun.reflect.annotation.AnnotationParser.parseArray(AnnotationParser.java:460)
        at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:286)
        at sun.reflect.annotation.AnnotationParser.parseAnnotation(AnnotationParser.java:222)
        at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:69)
        at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:52)
        at java.lang.Class.initAnnotationsIfNecessary(Class.java:3079)
        at java.lang.Class.getAnnotations(Class.java:3059)
        at org.springframework.core.type.classreading.AnnotationAttributesReadingVisitor.visitEnd(AnnotationAttributesReadingVisitor.java:131)
        at org.springframework.asm.ClassReader.a(Unknown Source)
        at org.springframework.asm.ClassReader.accept(Unknown Source)
        at org.springframework.asm.ClassReader.accept(Unknown Source)
        at org.springframework.core.type.classreading.SimpleMetadataReader.<init>(SimpleMetadataReader.java:54)
        at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:80)
        at org.springframework.core.type.classreading.CachingMetadataReaderFactory.getMetadataReader(CachingMetadataReaderFactory.java:101)
        at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:76)
        at org.springframework.context.annotation.ConfigurationClassParser.processImport(ConfigurationClassParser.java:154)
        at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:128)
        at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:102)
        at org.springframework.context.annotation.ConfigurationClassParser.processImport(ConfigurationClassParser.java:155)
        at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:128)
        at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:102)
        at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:85)
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:194)
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:144)
        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:599)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:407)
        at org.springframework.web.context.ContextLoader.createWebApplicationContext(ContextLoader.java:282)
        at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:204)
        at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:47)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4206)
        at org.apache.catalina.core.StandardContext.start(StandardContext.java:4705)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:799)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:779)

**Comment by dilipkrish** [comment]
At a minimum spring 3.2.x is required. 

Also there is better spring 3.2.x support in 2.3.0 of this library.

**Comment by ragzisme** [comment]
oops. i have an existing application based on Spring 3.0.6 which i need to generate documentation for. Would the legacy Spring-mvc library work for it? upgrading my Spring is not an option as its a critical application and i am not allowed to make changes.
