### ISSUE TITLE
spring-boot unable to open nexted jar file

### ISSUE THREAD

**Issue by davidpleydell** [springfox/springfox#1131]
Trying to launch the service from the command line produced the follow issues:

$ java -jar service-0.1-SNAPSHOT.jar
java.io.IOException: Unable to open nested jar file 'lib/springfox-swagger-ui-2.3.1.jar'
        at org.springframework.boot.loader.jar.JarFile.getNestedJarFile(JarFile.java:349)
        at org.springframework.boot.loader.archive.JarFileArchive.getNestedArchive(JarFileArchive.java:112)
        at org.springframework.boot.loader.archive.JarFileArchive.getNestedArchives(JarFileArchive.java:96)
        at org.springframework.boot.loader.ExecutableArchiveLauncher.getClassPathArchives(ExecutableArchiveLauncher.java:75)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:60)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
Caused by: java.io.IOException: Unable to find ZIP central directory records after reading 65792 bytes
        at org.springframework.boot.loader.jar.CentralDirectoryEndRecord.<init>(CentralDirectoryEndRecord.java:64)
        at org.springframework.boot.loader.jar.JarFile.<init>(JarFile.java:118)
        at org.springframework.boot.loader.jar.JarFile.createJarFileFromFileEntry(JarFile.java:387)
        at org.springframework.boot.loader.jar.JarFile.createJarFileFromEntry(JarFile.java:357)
        at org.springframework.boot.loader.jar.JarFile.getNestedJarFile(JarFile.java:343)
        ... 5 more

In fact the UI hasn't appeared when run in intellij though the end points /swagger-resources work fine.

**Comment by dilipkrish** [comment]
No idea what the problem might be... perhaps the jar is corrupt could you try cleaning out your libs and re-building. Incidentally what build/packaging tool are you using? maven or gradle?

**Comment by davidpleydell** [comment]
I'm using Maven.  I cleaned the maven repo and target and rebuilt and the error was still the same.  Running from Intellij I don't get the error but from the command line I receive the error message.

**Comment by dilipkrish** [comment]
It seems like a corrupt jar. You may need to clear your maven local cache as [suggested here](https://stackoverflow.com/questions/21403987/java-io-ioexception-when-running-spring-boot-jar-on-centos-6-4-open-jdk-1-7-0)

**Comment by davidpleydell** [comment]
I did clear my maven repos and rebuilt the jar.  I can run the jar on the linux server without issue.  
I include:
		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger-ui</artifactId>
			<version>2.3.1</version>
		</dependency>

Rebuild and same error.  Comment it and rebuild the service runs no problem.

**Comment by dilipkrish** [comment]
I suspect its something to do with your classpath/environment. If spring-boot:run works then its definitely environmental

**Comment by estn** [comment]
@dilipkrish  Thank You. I clean my local repo and it works!

**Comment by vargaendre** [comment]
Hi, 
just as a reference for whom it might be helpful (and for future me).

I had the same issue. I was running a Spring Boot jar in a docker container on a devserver.
The problem was that the disk was full on the server. I cleaned up unused docker containers and images and then it was all fine.
hth
