### ISSUE TITLE
Support DTOs from libraries in static documentation

### ISSUE THREAD

**Issue by asm0dey** [springfox/springfox#1230]
We're using springfox 2.4.0. We're trying to generate static docs with our application. When we put DTOs inside our main module and annotate them - they're documented fine, but in out project DTOs are living in separate module. And when we annotate them in those module - documentation doesn't include their swagger annotations.

**Comment by dilipkrish** [comment]
@asm0dey that doesn't make sense. It should just work regardless of where the DTOs are. Could you clarify or possibly provide an example of what you mean?

**Comment by asm0dey** [comment]
I'll try to provide you with example today. Thank you for your answer.

**Comment by asm0dey** [comment]
Sorry, we weren't able to reproduce this in any simple exmple. Looks like it's error somewhere in our code/setup.

**Comment by gionn** [comment]
I think we are facing the same problem, we are using Spring 4.0 and controllers annotated with `@RestController`, most of them has a `PageRequestDTO` parameter (that resides in a separated maven module, but this isn't the problem):

```
    public List<MyUserDTO> getAllAdminPaged( @Valid PageRequestDTO request, HttpServletResponse response,
            @RequestParam ( required = false ) String textField ) throws Exception
```

If I try to validate spec via swagger cli:
```
SyntaxError: Error resolving $ref pointer "/home/gionn/api.json#/definitions/PageRequestDTO". 
Token "PageRequestDTO" does not exist.
    at Function.ono [as syntax] (/home/gionn/.nvm/versions/node/v5.5.0/lib/node_modules/swagger-cli/node_modules/ono/lib/index.js:67:20)
    at Pointer.resolve (/home/gionn/.nvm/versions/node/v5.5.0/lib/node_modules/swagger-cli/node_modules/json-schema-ref-parser/lib/pointer.js:74:17)
    at $Ref.resolve (/home/gionn/.nvm/versions/node/v5.5.0/lib/node_modules/swagger-cli/node_modules/json-schema-ref-parser/lib/ref.js:139:18)
    at $Refs._resolve (/home/gionn/.nvm/versions/node/v5.5.0/lib/node_modules/swagger-cli/node_modules/json-schema-ref-parser/lib/refs.js:154:15)
    at /home/gionn/.nvm/versions/node/v5.5.0/lib/node_modules/swagger-cli/node_modules/json-schema-ref-parser/lib/dereference.js:49:29
    at Array.forEach (native)
    at crawl (/home/gionn/.nvm/versions/node/v5.5.0/lib/node_modules/swagger-cli/node_modules/json-schema-ref-parser/lib/dereference.js:40:22)
    at /home/gionn/.nvm/versions/node/v5.5.0/lib/node_modules/swagger-cli/node_modules/json-schema-ref-parser/lib/dereference.js:71:22
    at Array.forEach (native)
    at crawl (/home/gionn/.nvm/versions/node/v5.5.0/lib/node_modules/swagger-cli/node_modules/json-schema-ref-parser/lib/dereference.js:40:22)
```

The peculiarity of this class is that is always used in input as in the example and never as output.
Obviously the generated json contains a bunch of definitions for other DTOs of the same package of `PageRequestDTO`.

Suggestions?

**Comment by gionn** [comment]
Ugly workaround:

```
    @RequestMapping ( value = "/swagger_workaround", method = RequestMethod.POST )
    public PageRequestDTO workaroundSwagger( )
    {
        return new PageRequestDTO(  );
    }
```

Now I have another similar error:
```
SyntaxError: Error resolving $ref pointer "/home/gionn/api.json#/definitions/List". 
Token "List" does not exist.
    at Function.ono [as syntax] (/home/gionn/.nvm/versions/node/v5.5.0/lib/node_modules/swagger-cli/node_modules/ono/lib/index.js:67:20)
    at Pointer.resolve (/home/gionn/.nvm/versions/node/v5.5.0/lib/node_modules/swagger-cli/node_modules/json-schema-ref-parser/lib/pointer.js:74:17)
    at $Ref.resolve (/home/gionn/.nvm/versions/node/v5.5.0/lib/node_modules/swagger-cli/node_modules/json-schema-ref-parser/lib/ref.js:139:18)
    at $Refs._resolve (/home/gionn/.nvm/versions/node/v5.5.0/lib/node_modules/swagger-cli/node_modules/json-schema-ref-parser/lib/refs.js:154:15)
    at /home/gionn/.nvm/versions/node/v5.5.0/lib/node_modules/swagger-cli/node_modules/json-schema-ref-parser/lib/dereference.js:49:29
    at Array.forEach (native)
    at crawl (/home/gionn/.nvm/versions/node/v5.5.0/lib/node_modules/swagger-cli/node_modules/json-schema-ref-parser/lib/dereference.js:40:22)
    at /home/gionn/.nvm/versions/node/v5.5.0/lib/node_modules/swagger-cli/node_modules/json-schema-ref-parser/lib/dereference.js:71:22
    at Array.forEach (native)
    at crawl (/home/gionn/.nvm/versions/node/v5.5.0/lib/node_modules/swagger-cli/node_modules/json-schema-ref-parser/lib/dereference.js:40:22)
```

Looking for List in the json, I found:

```
                "googleCharts": {
                    "additionalProperties": {
                        "$ref": "#/definitions/List"
                    },
                    "type": "object"
                },
                "graphs": {
                    "additionalProperties": {
                        "$ref": "#/definitions/List"
                    },
                    "type": "object"
                },
```

So that is referring to two properties insied another DTO class:
```
    private Map<String, List<GraphUrlDTO>> graphs;
    private Map<String, List<GraphUrlDTO>> googleCharts;
```

Should I open a separated issue?
