### ISSUE TITLE
V2.4.0 : java.lang.ArrayIndexOutOfBoundsException: 1 - HandlerMethodResolver$2.apply(HandlerMethodResolver.java:110)

### ISSUE THREAD

**Issue by tdeverdiere** [springfox/springfox#1241]
The class that is being parsed has 2 methods with the same name. 
```
    @Override
    @Transactional
    public DTO<String>[] loadDetails(String id) {
        ...
    }

    @Override
    @Transactional
    public DTO<String>[] loadDetails(String id, Date since) {
        ...
    }
```
The exception stack trace is :
```
java.lang.ArrayIndexOutOfBoundsException: 1
        at springfox.documentation.spring.web.readers.operation.HandlerMethodResolver$2.apply(HandlerMethodResolver.java:110)
        at springfox.documentation.spring.web.readers.operation.HandlerMethodResolver$2.apply(HandlerMethodResolver.java:104)
        at com.google.common.base.Present.transform(Present.java:71)
        at springfox.documentation.spring.web.readers.operation.HandlerMethodResolver.methodParameters(HandlerMethodResolver.java:98)
        at springfox.documentation.spring.web.readers.operation.OperationModelsProvider.collectParameters(OperationModelsProvider.java:88)
        at springfox.documentation.spring.web.readers.operation.OperationModelsProvider.apply(OperationModelsProvider.java:58)
        at springfox.documentation.spring.web.plugins.DocumentationPluginsManager.modelContexts(DocumentationPluginsManager.java:129
```

**Comment by dilipkrish** [comment]
Without looking at the code, it appears that this may be a bug. Thanks for reporting

**Comment by tdeverdiere** [comment]
I confirm this commit resolves the bug
