### ISSUE TITLE
ApiResponses can not support custom status code such like 1010 

### ISSUE THREAD

**Issue by dockerlet** [springfox/springfox#1380]
<details>
 <summary>java.lang.IllegalArgumentException: No matching constant for 1010</summary>

Caused by: java.lang.IllegalArgumentException: No matching constant for [1010]
	at org.springframework.http.HttpStatus$Series.valueOf(HttpStatus.java:524) ~[spring-web-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at springfox.documentation.swagger.readers.operation.SwaggerResponseMessageReader.isSuccessful(SwaggerResponseMessageReader.java:153) ~[springfox-swagger-common-2.5.0.jar:2.5.0]
	at springfox.documentation.swagger.readers.operation.SwaggerResponseMessageReader.read(SwaggerResponseMessageReader.java:109) ~[springfox-swagger-common-2.5.0.jar:2.5.0]
	at springfox.documentation.swagger.readers.operation.SwaggerResponseMessageReader.apply(SwaggerResponseMessageReader.java:74) ~[springfox-swagger-common-2.5.0.jar:2.5.0]
	at springfox.documentation.spring.web.plugins.DocumentationPluginsManager.operation(DocumentationPluginsManager.java:113) ~[springfox-spring-web-2.5.0.jar:2.5.0]
	at springfox.documentation.spring.web.readers.operation.ApiOperationReader.read(ApiOperationReader.java:80) ~[springfox-spring-web-2.5.0.jar:2.5.0]
	at springfox.documentation.spring.web.scanners.CachingOperationReader$1.load(CachingOperationReader.java:50) ~[springfox-spring-web-2.5.0.jar:2.5.0]
	at springfox.documentation.spring.web.scanners.CachingOperationReader$1.load(CachingOperationReader.java:48) ~[springfox-spring-web-2.5.0.jar:2.5.0]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3542) ~[guava-19.0.jar:na]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2323) ~[guava-19.0.jar:na]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2286) ~[guava-19.0.jar:na]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201) ~[guava-19.0.jar:na]
	... 70 common frames omitted
 ...this is hidden, collapsable content...
</details>

**Comment by dilipkrish** [comment]
Thanks for reporting!
