### ISSUE TITLE
Springfox expects _links to be array, while Spring hateoas return _links as object

### ISSUE THREAD

**Issue by jiangchuan1220** [springfox/springfox#1440]
I use Spring hateoas in my Spring boot project, it add _embedded and _links into response body. I expect the _links to be a array as follows:
"_links": [
"self": {
"href": "http://localhost:8080/lists"
}
]
However, the response turns out the _links is an Object as follows:
"_links": {
"self": {
"href": "http://localhost:8080/lists"
}
}
Is there any way to change the _links from object to array (from "{}" to "[]") ?
This problem comes out when I use swagger to generate api description. Swagger expects the _links to be array, as follows:
"_links": [
{
"href": "string",
"rel": "string",
"templated": true
}
]
Looking forward to your reply! Thanks.

**Comment by dilipkrish** [comment]
@jiangchuan1220 This is a subtle issue that you're experiencing. Links are actually modeled as an array. However spring-hateoas serializes those links as a map of `rel -> {href: value}`. If you let springfox know about the alternate type it should render it correctly for you.

**Comment by jiangchuan1220** [comment]
@dilipkrish Thanks for your reply.
It seems that springfox is expects an invalid HAL format. Do you know any way that I can submit this issue to springfox team?  I am not quite sure if it works just raise a question on Github.

**Comment by dilipkrish** [comment]
This is the site to submit issues. But what you're seeing is _NOT_ an issue. That is the way its supposed to work. If you want it to work differently you can provide alternate types to change the expectation

**Comment by jiangchuan1220** [comment]
@dilipkrish Is there any way to change springfox to model links as Hashmap?

**Comment by jiangchuan1220** [comment]
My idea is that Spring hateoas declare links as List<Link>, and use a custom serializer to transform link from List to map. This transform lead to springfox cannot know the real type of links. Is this idea correct?

**Comment by jiangchuan1220** [comment]
@dilipkrish Now that springfox doesn't know anything about custom serializers. why do not leave _links as  object, then it can accept any type of links.

I modified the _links type in my API description as follows:

"Resource": {
            "type": "object",
            "properties": {
                "_links": {
                    "type": "array", //change array to object
                    "items": {
                        "$ref": "#/definitions/Link"
                    }
                },
                "id": {
                    "type": "string"
                }
            }
        },

then I can use the description to generate client SDK with swagger codegen. With the client SDK, I can accept links as Map.

**Comment by dilipkrish** [comment]
@jiangchuan1220 you can create an [alternate type rule](http://springfox.github.io/springfox/docs/current/#springfox-swagger2-with-spring-mvc-and-spring-boot) see 10*. to render the links how ever you want it.

**Comment by jiangchuan1220** [comment]
I have seen alternate type rule, but it does not work. It seems that alternate type rule can change the type of API response, but I want to change part of response instead of the whole response.
For example, the controller return type is "Resources<pet>", the "List<Link>" _links is a property of Resources, how can I just change "List<link>" to "map" in the API?

**Comment by jiangchuan1220** [comment]
I success to change type by the following code
````
          .alternateTypeRules(
        		  AlternateTypeRules.newRule(typeResolver.resolve(List.class, WildcardType.class),
                		  typeResolver.resolve(Object.class)))
````
But there is still another issue, this will change all List<T> fields to Object, not only _links. Is there any method to change only _links type?

**Comment by jiangchuan1220** [comment]
It seems that I should not use the org.springframework.hateoas.Link for alternatetype, anyone know which Link I should use?

**Comment by dilipkrish** [comment]
@jiangchuan1220 Let me try and come up with a sample

**Comment by jiangchuan1220** [comment]
That's great! Looking forward for your sample.

**Comment by khong07** [comment]
Hi,

I'm also curious about the solution (i have a same problem). Because in case of _links is an object, what properties we should put it in? (self, etc...) Because the "rel" is dynamic so ...

For example: i have two endpoints that return resources with links
The first one, links should contain "self" and "image"
The second one, links should contain "self" and "sound". How you can specify it in API Description? It should be two different objects

**Comment by jiangchuan1220** [comment]
@khong07 There would be no difference for your example if we change links to Object. In fact, I think custom link like "image" and "sound" should not be included into API description.

**Comment by khong07** [comment]
@jiangchuan1220 yes, there will be no difference if we change links from Array to Object. Waiting for dilipkrish's example.

PS: In my case, i need (in additional of "self" link) "image" and "sound" links present in API description. These links are not optional.

**Comment by dilipkrish** [comment]
Sorry folks that it too so long! I just verified that it was a bug with classmate that needed to be fixed. 

In the mean while, until it is released you'd need to create an alternate type rule similar to the one I created [in the test](https://github.com/springfox/springfox/blob/master/swagger-contract-tests/src/test/groovy/springfox/test/contract/swaggertests/Swagger2TestConfig.groovy#L151-L153), where `LinkAlternate` looks [like this](https://github.com/springfox/springfox/blob/master/springfox-spring-web/src/test/java/springfox/documentation/spring/web/dummy/controllers/BugsController.java#L103-L113).

Only your rule would be slightly different.

```java
newRule(
              resolver.resolve(List.class, resolver.resolve(Link.class, String.class)), //<--- this
              resolver.resolve(Map.class, String.class, BugsController.LinkAlternate.class))
```

**Comment by jiangchuan1220** [comment]
@dilipkrish I followed your simple, but there is error when I start my application.
My code like this:
````
Docket docket =  new Docket(DocumentationType.SWAGGER_2)  
          .select()                                  
          .apis(RequestHandlerSelectors.any())              
          .paths(PathSelectors.any())
          .build()
          .apiInfo(apiInfo())
          .alternateTypeRules(
  AlternateTypeRules.newRule(typeResolver.resolve(List.class,  typeResolver.resolve(Link.class, String.class)),
   typeResolver.resolve(Map.class, String.class, BugsController.LinkAlternate.class)))
````
The error is as follows:
````
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'api' defined in class path resource [com/siemens/isb/rest/hateoas/configuration/SwaggerConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [springfox.documentation.spring.web.plugins.Docket]: Factory method 'api' threw exception; nested exception is java.lang.IllegalArgumentException: Can not create TypeBinding for class org.springframework.hateoas.Link with 1 type parameter: class expects 0
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599) ~[spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1123) ~[spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1018) ~[spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510) ~[spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482) ~[spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772) ~[spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:839) ~[spring-context-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538) ~[spring-context-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118) ~[spring-boot-1.3.3.RELEASE.jar:1.3.3.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:766) [spring-boot-1.3.3.RELEASE.jar:1.3.3.RELEASE]
	at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:361) [spring-boot-1.3.3.RELEASE.jar:1.3.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307) [spring-boot-1.3.3.RELEASE.jar:1.3.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1191) [spring-boot-1.3.3.RELEASE.jar:1.3.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1180) [spring-boot-1.3.3.RELEASE.jar:1.3.3.RELEASE]
	at com.siemens.isb.rest.hateoas.Application.main(Application.java:33) [bin/:na]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [springfox.documentation.spring.web.plugins.Docket]: Factory method 'api' threw exception; nested exception is java.lang.IllegalArgumentException: Can not create TypeBinding for class org.springframework.hateoas.Link with 1 type parameter: class expects 0
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189) ~[spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588) ~[spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	... 18 common frames omitted
Caused by: java.lang.IllegalArgumentException: Can not create TypeBinding for class org.springframework.hateoas.Link with 1 type parameter: class expects 0
	at com.fasterxml.classmate.TypeBindings.create(TypeBindings.java:91) ~[classmate-1.3.1.jar:1.3.1]
	at com.fasterxml.classmate.TypeResolver.resolve(TypeResolver.java:145) ~[classmate-1.3.1.jar:1.3.1]
	at com.siemens.isb.rest.hateoas.configuration.SwaggerConfig.api(SwaggerConfig.java:55) ~[bin/:na]
	at com.siemens.isb.rest.hateoas.configuration.SwaggerConfig$$EnhancerBySpringCGLIB$$b4b8b8fc.CGLIB$api$0(<generated>) ~[bin/:na]
	at com.siemens.isb.rest.hateoas.configuration.SwaggerConfig$$EnhancerBySpringCGLIB$$b4b8b8fc$$FastClassBySpringCGLIB$$740605ec.invoke(<generated>) ~[bin/:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:355) ~[spring-context-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at com.siemens.isb.rest.hateoas.configuration.SwaggerConfig$$EnhancerBySpringCGLIB$$b4b8b8fc.api(<generated>) ~[bin/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_65]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_65]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_65]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_65]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162) ~[spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	... 19 common frames omitted
````

Seems that in the method resolver.resolve, I can not add generic type for Link.class.

**Comment by dilipkrish** [comment]
Sorry for providing the incorrect solution. That won't work because classmate does check the types. I guess you'd have to wait for 2.6.0, which should be out in the next couple of weeks.

**Comment by jiangchuan1220** [comment]
Thanks for your reply. Looking forward for 2.6.0.

**Comment by jiangchuan1220** [comment]
Hi dilipkrish,
I have been working on another project. So I just switch back to verify whether this problem is solved in version 2.6.0.
In my test with springfox 2.6.0, the following code still have error:
````
Docket docket =  new Docket(DocumentationType.SWAGGER_2)  
          .select()                                  
          .apis(RequestHandlerSelectors.any())              
          .paths(PathSelectors.any())
          .build()
          .apiInfo(apiInfo())
          .alternateTypeRules(
  AlternateTypeRules.newRule(typeResolver.resolve(List.class,  typeResolver.resolve(Link.class, String.class)),
   typeResolver.resolve(Map.class, String.class, BugsController.LinkAlternate.class)))
````
the error happens when I start the project, it is as follows:
````
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'api' defined in class path resource [com/siemens/isb/rest/hateoas/configuration/SwaggerConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [springfox.documentation.spring.web.plugins.Docket]: Factory method 'api' threw exception; nested exception is java.lang.IllegalArgumentException: Can not create TypeBinding for class org.springframework.hateoas.Link with 1 type parameter: class expects 0
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599) ~[spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1123) ~[spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1018) ~[spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510) ~[spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482) ~[spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772) ~[spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:839) ~[spring-context-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538) ~[spring-context-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118) ~[spring-boot-1.3.3.RELEASE.jar:1.3.3.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:766) [spring-boot-1.3.3.RELEASE.jar:1.3.3.RELEASE]
	at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:361) [spring-boot-1.3.3.RELEASE.jar:1.3.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307) [spring-boot-1.3.3.RELEASE.jar:1.3.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1191) [spring-boot-1.3.3.RELEASE.jar:1.3.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1180) [spring-boot-1.3.3.RELEASE.jar:1.3.3.RELEASE]
	at com.siemens.isb.rest.hateoas.Application.main(Application.java:32) [bin/:na]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [springfox.documentation.spring.web.plugins.Docket]: Factory method 'api' threw exception; nested exception is java.lang.IllegalArgumentException: Can not create TypeBinding for class org.springframework.hateoas.Link with 1 type parameter: class expects 0
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189) ~[spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588) ~[spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	... 18 common frames omitted
Caused by: java.lang.IllegalArgumentException: Can not create TypeBinding for class org.springframework.hateoas.Link with 1 type parameter: class expects 0
	at com.fasterxml.classmate.TypeBindings.create(TypeBindings.java:91) ~[classmate-1.3.1.jar:1.3.1]
	at com.fasterxml.classmate.TypeResolver.resolve(TypeResolver.java:145) ~[classmate-1.3.1.jar:1.3.1]
	at com.siemens.isb.rest.hateoas.configuration.SwaggerConfig.api(SwaggerConfig.java:43) ~[bin/:na]
	at com.siemens.isb.rest.hateoas.configuration.SwaggerConfig$$EnhancerBySpringCGLIB$$ba7d6166.CGLIB$api$0(<generated>) ~[bin/:na]
	at com.siemens.isb.rest.hateoas.configuration.SwaggerConfig$$EnhancerBySpringCGLIB$$ba7d6166$$FastClassBySpringCGLIB$$7975f738.invoke(<generated>) ~[bin/:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:355) ~[spring-context-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at com.siemens.isb.rest.hateoas.configuration.SwaggerConfig$$EnhancerBySpringCGLIB$$ba7d6166.api(<generated>) ~[bin/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_65]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_65]
````

What should I do in the new version?

**Comment by dilipkrish** [comment]
Looks like your rule is setup incorrectly

```java
  AlternateTypeRules.newRule(typeResolver.resolve(List.class,   Link.class),
   typeResolver.resolve(Map.class, String.class, BugsController.LinkAlternate.class)))
```

**Comment by jiangchuan1220** [comment]
Hi dilipkrish,
Your solution works and the links type is changed to Map.
But I need to add the BugsController class manually, this class is not included in the springfox library.
My build.gradle is:
````
    compile("io.springfox:springfox-swagger2:2.6.0")
    compile("io.springfox:springfox-swagger-ui:2.6.0")
````
In the added springfox library, I cannot find the BugsController class. How can I add it from gradle?

**Comment by dilipkrish** [comment]
You cant. Its a test library

**Comment by skrooks** [comment]
So...
```
newRule(typeResolver.resolve(List.class, Link.class),
        typeResolver.resolve(Map.class, String.class, Link.class))
```
You could possibly also apply a similar alternate type rule for APIs returning collections using HAL, e.g. as mentioned in #2709 
```
// Collection<Resource<MyType>> to Map<String, List<Resource<MyType>>>
newRule(typeResolver.resolve(Collection.class, typeResolver.resolve(Resource.class, MyType.class)),
        typeResolver.resolve(Map.class, typeResolver.resolve(String.class), typeResolver.resolve(List.class, typeResolver.resolve(Resource.class, MyType.class))), HIGHEST_PRECEDENCE)
```
