### ISSUE TITLE
swagger ui issue - unable to display spring REST ws operations -  Uncaught TypeError: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by sbelvadi** [springfox/springfox#1581]
I am new to swagger ui, springfox - so request your help/suggestions

I am trying to integrate swagger ui with a spring rest web service (not spring boot app)
What I have noticed is the following
1. With one of the web services - I can see both the api-docs (json) and the swagger-ui without any issue
2. With the second web service - I was able to get the json to render on the screen when trying to access http://localhost:8080/.../v2/api-docs. However I am unable to view the REST ws operations in swagger-ui. 

Both web services are spring rest web services.

Swagger versions/rependencies - maven pom
Versions I am using 

		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger2</artifactId>
			<version>2.6.0</version>
		</dependency>

		
		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger-ui</artifactId>
			<version>2.6.0</version>
		</dependency>

When I try to view Developer Tools/Chrome I see the following error:

swagger-ui.min.js:1 Uncaught TypeError: Cannot read property 'type' of undefined(…)

The complete error is:

ncaught TypeError: Cannot read property 'type' of undefined
    at Object.<anonymous> (http://localhost:8080/DalbumREST/webjars/springfox-swagger-ui/swagger-ui.min.js:1:6327)
    at Object.12 (http://localhost:8080/DalbumREST/webjars/springfox-swagger-ui/swagger-ui.min.js:1:31662)
    at Object.f [as inverse] (http://localhost:8080/DalbumREST/webjars/springfox-swagger-ui/lib/handlebars-2.0.0.js:27:6595)
    at Object.<anonymous> (http://localhost:8080/DalbumREST/webjars/springfox-swagger-ui/lib/handlebars-2.0.0.js:27:2823)
    at Object.9 (http://localhost:8080/DalbumREST/webjars/springfox-swagger-ui/swagger-ui.min.js:1:31051)
    at Object.f [as inverse] (http://localhost:8080/DalbumREST/webjars/springfox-swagger-ui/lib/handlebars-2.0.0.js:27:6595)
    at Object.<anonymous> (http://localhost:8080/DalbumREST/webjars/springfox-swagger-ui/lib/handlebars-2.0.0.js:27:2823)
    at Object.main (http://localhost:8080/DalbumREST/webjars/springfox-swagger-ui/swagger-ui.min.js:2:208)
    at e (http://localhost:8080/DalbumREST/webjars/springfox-swagger-ui/lib/handlebars-2.0.0.js:27:6198)
    at s.render (http://localhost:8080/DalbumREST/webjars/springfox-swagger-ui/swagger-ui.min.js:10:30507)

I am not sure what this error means and how to resolve.
Appreciate your help

**Comment by sbelvadi** [comment]
trying to get some advise on the above. if anyone can help. much appreciated

**Comment by dilipkrish** [comment]
@sbelvadi Try debugging the javascript. It should give you clues about which model/property is causing this issue. Also please use 2.6.1, it may or may not help.
