### ISSUE TITLE
StackOverflowError on swagger generation

### ISSUE THREAD

**Issue by jmattheis** [springfox/springfox#1603]
Version 2.6.1
Example at https://github.com/jmattheis/springfox-demos/tree/stackoverfloeexception/spring-java-swagger
When having class A which has as attribute class B. And class B has as attribute class A, a ``StackOverflowError`` is thrown
```
public class CustomType {
	private OtherCustomType otherCustomType;
	public OtherCustomType getOtherCustomType() {
		return otherCustomType;
	}
	public void setOtherCustomType(final OtherCustomType otherCustomType) {
		this.otherCustomType = otherCustomType;
	}
}
public class OtherCustomType {
	private CustomType parent;
	public CustomType getParent() {
		return parent;
	}
	public void setParent(final CustomType parent) {
		this.parent = parent;
	}
}
@RestController
public class Controller {
	@RequestMapping(value = "get", method = RequestMethod.GET)
	public ResponseEntity<Void> get(final CustomType test) {
		return ResponseEntity.ok().build();
	}
}
```

**Comment by dmarcaida** [comment]
Hi @dilipkrish! I'm still experiencing this bug when one of the types has a collection attribute of the other.

Thank you guys for writing this awesome library!

**Comment by kopax** [comment]
Hi, I have installed swagger 2.7.0, it is my first installation following this guide : http://www.baeldung.com/swagger-2-documentation-for-spring-rest-api

I have the following error : 

Application startup failed

```
org.springframework.context.ApplicationContextException: Failed to start bean 'documentationPluginsBootstrapper'; nested exception is com.google.common.util.concurrent.ExecutionError: java.lang.StackOverflowError
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178)
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:50)
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:348)
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:151)
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:114)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:880)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:144)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107)
	at com.domain.api.ApiApplication.main(ApiApplication.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
```

Is this supposed to be fixed?

**Comment by dilipkrish** [comment]
It is but this might be a different condition that causes it. Is it possible for you to create a new issue with steps to reproduce.

**Comment by kopax** [comment]
@dilipkrish I have craeted issue https://github.com/springfox/springfox/issues/2100

**Comment by dilipkrish** [comment]
@kopax thank you!
