### ISSUE TITLE
Spring context loading gets stuck after caching

### ISSUE THREAD

**Issue by ahmednasir91** [springfox/springfox#1618]
We've a spring boot app with ~1200 APIs in 160 Controllers, using Swagger2 for generating API docs, but we are facing a problem during context loading we see a lot of log lines

```
2016-12-29 12:23:25.309  INFO 6748 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: testAPIXYZPOST_5
2016-12-29 12:23:25.327  INFO 6748 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: testAPIXYZPOST_2
2016-12-29 12:23:25.336  INFO 6748 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: testAPIXYZPOST_3
2016-12-29 12:23:29.460  INFO 6748 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: testAPIXYZPOST_1
2016-12-29 12:23:29.468  INFO 6748 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: testAPIXYZPOST_4
2016-12-29 12:23:29.475  INFO 6748 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: testAPIXYZPOST_5
2016-12-29 12:23:29.505  INFO 6748 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: testAPIXYZPOST_1
```

It stops here and the context loading doesn't proceed, the configuration class is following

```java
@EnableSwagger2
@Configuration
@Profile("internal")
public class SwaggerConfiguration {

    @Value("${info.app.name}")
    private String appName;

    @Value("${info.app.description}")
    private String appDescription;

    @Autowired
    private TypeResolver typeResolver;

    @Bean
    public Docket coreServiceApi() {
        return new Docket(DocumentationType.SWAGGER_2)
                .select()
                .apis(RequestHandlerSelectors.withClassAnnotation(Controller.class))
                .build();
    }

}
```
We tried with marking a few API `@RestController` and used `.apis(RequestHandlerSelectors.withClassAnnotation(RestController.class))` it worked in the same project as there are only 4 Controller marked with `@RestController`.
Any pointers on what can be going wrong?

I suspended the main thread when it was stuck and found the following 

```
"main@1" prio=5 tid=0x1 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at java.util.AbstractList.<init>(AbstractList.java:77)
	  at java.util.ArrayList.<init>(ArrayList.java:176)
	  at com.google.common.collect.Lists.newArrayList(Lists.java:144)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedDependencies(DefaultModelDependencyProvider.java:103)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.maybeFromRegularType(DefaultModelDependencyProvider.java:169)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedPropertiesAndFields(DefaultModelDependencyProvider.java:145)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedDependencies(DefaultModelDependencyProvider.java:105)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.maybeFromCollectionElementType(DefaultModelDependencyProvider.java:182)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedPropertiesAndFields(DefaultModelDependencyProvider.java:143)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedDependencies(DefaultModelDependencyProvider.java:105)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.maybeFromRegularType(DefaultModelDependencyProvider.java:169)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedPropertiesAndFields(DefaultModelDependencyProvider.java:145)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedDependencies(DefaultModelDependencyProvider.java:105)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.maybeFromRegularType(DefaultModelDependencyProvider.java:169)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedPropertiesAndFields(DefaultModelDependencyProvider.java:145)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedDependencies(DefaultModelDependencyProvider.java:105)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.maybeFromCollectionElementType(DefaultModelDependencyProvider.java:182)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedPropertiesAndFields(DefaultModelDependencyProvider.java:143)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedDependencies(DefaultModelDependencyProvider.java:105)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.maybeFromRegularType(DefaultModelDependencyProvider.java:169)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedPropertiesAndFields(DefaultModelDependencyProvider.java:145)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedDependencies(DefaultModelDependencyProvider.java:105)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.maybeFromCollectionElementType(DefaultModelDependencyProvider.java:182)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedPropertiesAndFields(DefaultModelDependencyProvider.java:143)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedDependencies(DefaultModelDependencyProvider.java:105)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.maybeFromCollectionElementType(DefaultModelDependencyProvider.java:182)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedPropertiesAndFields(DefaultModelDependencyProvider.java:143)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedDependencies(DefaultModelDependencyProvider.java:105)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.maybeFromRegularType(DefaultModelDependencyProvider.java:169)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedPropertiesAndFields(DefaultModelDependencyProvider.java:145)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedDependencies(DefaultModelDependencyProvider.java:105)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.maybeFromCollectionElementType(DefaultModelDependencyProvider.java:182)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedPropertiesAndFields(DefaultModelDependencyProvider.java:143)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedDependencies(DefaultModelDependencyProvider.java:105)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.maybeFromRegularType(DefaultModelDependencyProvider.java:169)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedPropertiesAndFields(DefaultModelDependencyProvider.java:145)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedDependencies(DefaultModelDependencyProvider.java:105)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.maybeFromRegularType(DefaultModelDependencyProvider.java:169)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedPropertiesAndFields(DefaultModelDependencyProvider.java:145)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedDependencies(DefaultModelDependencyProvider.java:105)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.maybeFromRegularType(DefaultModelDependencyProvider.java:169)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedPropertiesAndFields(DefaultModelDependencyProvider.java:145)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedDependencies(DefaultModelDependencyProvider.java:105)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.maybeFromCollectionElementType(DefaultModelDependencyProvider.java:182)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedPropertiesAndFields(DefaultModelDependencyProvider.java:143)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedDependencies(DefaultModelDependencyProvider.java:105)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.maybeFromRegularType(DefaultModelDependencyProvider.java:169)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedPropertiesAndFields(DefaultModelDependencyProvider.java:145)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedDependencies(DefaultModelDependencyProvider.java:105)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.maybeFromRegularType(DefaultModelDependencyProvider.java:169)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedPropertiesAndFields(DefaultModelDependencyProvider.java:145)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedDependencies(DefaultModelDependencyProvider.java:105)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.maybeFromRegularType(DefaultModelDependencyProvider.java:169)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedPropertiesAndFields(DefaultModelDependencyProvider.java:145)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedDependencies(DefaultModelDependencyProvider.java:105)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.maybeFromRegularType(DefaultModelDependencyProvider.java:169)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedPropertiesAndFields(DefaultModelDependencyProvider.java:145)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedDependencies(DefaultModelDependencyProvider.java:105)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.maybeFromCollectionElementType(DefaultModelDependencyProvider.java:182)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedPropertiesAndFields(DefaultModelDependencyProvider.java:143)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedDependencies(DefaultModelDependencyProvider.java:105)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.maybeFromRegularType(DefaultModelDependencyProvider.java:169)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedPropertiesAndFields(DefaultModelDependencyProvider.java:145)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedDependencies(DefaultModelDependencyProvider.java:105)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.maybeFromCollectionElementType(DefaultModelDependencyProvider.java:182)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedPropertiesAndFields(DefaultModelDependencyProvider.java:143)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedDependencies(DefaultModelDependencyProvider.java:105)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.maybeFromRegularType(DefaultModelDependencyProvider.java:169)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedPropertiesAndFields(DefaultModelDependencyProvider.java:145)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedDependencies(DefaultModelDependencyProvider.java:105)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.maybeFromCollectionElementType(DefaultModelDependencyProvider.java:182)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedPropertiesAndFields(DefaultModelDependencyProvider.java:143)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedDependencies(DefaultModelDependencyProvider.java:105)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.maybeFromRegularType(DefaultModelDependencyProvider.java:169)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedPropertiesAndFields(DefaultModelDependencyProvider.java:145)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedDependencies(DefaultModelDependencyProvider.java:105)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.maybeFromRegularType(DefaultModelDependencyProvider.java:169)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedPropertiesAndFields(DefaultModelDependencyProvider.java:145)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedDependencies(DefaultModelDependencyProvider.java:105)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.maybeFromRegularType(DefaultModelDependencyProvider.java:169)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedPropertiesAndFields(DefaultModelDependencyProvider.java:145)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedDependencies(DefaultModelDependencyProvider.java:105)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.maybeFromCollectionElementType(DefaultModelDependencyProvider.java:182)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedPropertiesAndFields(DefaultModelDependencyProvider.java:143)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedDependencies(DefaultModelDependencyProvider.java:105)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.maybeFromRegularType(DefaultModelDependencyProvider.java:169)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedPropertiesAndFields(DefaultModelDependencyProvider.java:145)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedDependencies(DefaultModelDependencyProvider.java:105)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.maybeFromRegularType(DefaultModelDependencyProvider.java:169)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedPropertiesAndFields(DefaultModelDependencyProvider.java:145)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedDependencies(DefaultModelDependencyProvider.java:105)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.maybeFromRegularType(DefaultModelDependencyProvider.java:169)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedPropertiesAndFields(DefaultModelDependencyProvider.java:145)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedDependencies(DefaultModelDependencyProvider.java:105)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.maybeFromRegularType(DefaultModelDependencyProvider.java:169)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedPropertiesAndFields(DefaultModelDependencyProvider.java:145)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedDependencies(DefaultModelDependencyProvider.java:105)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedTypeParameters(DefaultModelDependencyProvider.java:127)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedDependencies(DefaultModelDependencyProvider.java:103)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedTypeParameters(DefaultModelDependencyProvider.java:127)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedDependencies(DefaultModelDependencyProvider.java:103)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.dependentModels(DefaultModelDependencyProvider.java:66)
	  at springfox.documentation.schema.CachingModelDependencyProvider$1.load(CachingModelDependencyProvider.java:50)
	  at springfox.documentation.schema.CachingModelDependencyProvider$1.load(CachingModelDependencyProvider.java:48)
	  at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
	  at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
	  at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
	  - locked <0x4861> (a com.google.common.cache.LocalCache$StrongAccessWriteEntry)
	  at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
	  at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
	  at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941)
	  at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
	  at springfox.documentation.schema.CachingModelDependencyProvider.dependentModels(CachingModelDependencyProvider.java:58)
	  at springfox.documentation.schema.DefaultModelProvider.dependencies(DefaultModelProvider.java:113)
	  at springfox.documentation.schema.CachingModelProvider.dependencies(CachingModelProvider.java:68)
	  at springfox.documentation.spring.web.scanners.ApiModelReader.populateDependencies(ApiModelReader.java:133)
	  at springfox.documentation.spring.web.scanners.ApiModelReader.read(ApiModelReader.java:76)
	  at springfox.documentation.spring.web.scanners.ApiListingScanner.scan(ApiListingScanner.java:88)
	  at springfox.documentation.spring.web.scanners.ApiDocumentationScanner.scan(ApiDocumentationScanner.java:70)
	  at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.scanDocumentation(DocumentationPluginsBootstrapper.java:85)
	  at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.start(DocumentationPluginsBootstrapper.java:127)
	  at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:173)
	  at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:51)
	  at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:346)
	  at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:149)
	  at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:112)
	  at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:874)
	  at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:144)
	  at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:544)
	  - locked <0x4862> (a java.lang.Object)
	  at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	  at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:761)
	  at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:371)
	  at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	  at org.springframework.boot.SpringApplication.run(SpringApplication.java:1186)
	  at org.springframework.boot.SpringApplication.run(SpringApplication.java:1175)
```

**Comment by dilipkrish** [comment]
Most likely you have a model what has recursive definitions. This may be an edge case, cannot really say without more information. Obviously its tripping up on some model definition involving generics. Could you perhaps try and debug one of these lines

```log
	  at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedDependencies(DefaultModelDependencyProvider.java:105)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.maybeFromRegularType(DefaultModelDependencyProvider.java:169)
	  at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedPropertiesAndFields(DefaultModelDependencyProvider.java:145)
```
and see which model is acting up and perhaps post that usage pattern.

**Comment by ahmednasir91** [comment]
@dilipkrish thanks for your reply, yes it was due to one bad API, returning DB entity model in response which has relations with other entities. 
I was able to debug and find that API and solved the problem.

**Comment by dilipkrish** [comment]
@ahmednasir91 would be useful if you can share the example of your DB objects, if not the objects themselves, a fake entity model with dependencies that reproduces this issue. That way this error doesnt occur even if the entities are not modeled correctly

**Comment by ahmednasir91** [comment]
@dilipkrish sure will try to help as much as i can.

So when debugging what i found was, it was iterating through the whole chain of entity models, there are more 300 entity models. The return type of the action method was returning an entity that had one of them linked to almost all of majority of other entities, so it's like a link to a nest :) 

I checked `DefaultModelDependencyProvider` it was like going through the entities again and again, may be we can define a threshold on how level deep it should go? or keep track of the entities visited (i saw some logic related to this when debugging) but doesn't seem to be working in my case.

Let me know if you need more help in debugging this.. I can reproduce this easily on my project.

**Comment by dilipkrish** [comment]
I'm looking for a simple model setup, even pseudo code that demonstrates the problem you're seeing

**Comment by dilipkrish** [comment]
@ahmednasir91 did you get around to finding an example that can cause this kind of recursion?

**Comment by dilipkrish** [comment]
Moving to complete, as I haven't heard back. Feel free to re-open

**Comment by cesarreyesa** [comment]
Hi, I recently came across the same issue, but I was using Groovy.

It was caused by the MetaClass from Groovy.

This configuration did the trick
`docket.ignoredParameterTypes(groovy.lang.MetaClass.class)`

Hope this helps someone else.
