### ISSUE TITLE
[DataRest] documentationPluginsBootstrapper NPE on startup

### ISSUE THREAD

**Issue by raquelrag** [springfox/springfox#1710]
**Versions:**
SpringFox = 2.6.+
Spring Boot Gradle Plugin = 1.5.+ (Spring v4.3.7.RELEASE)

I have recently added spring data rest as a dependency on my project and haven't been able to make springfox work. Initially it was a simple normal spring controllers application and springfox integration working fine. After adding `@RepositoryRestResource` repositories and following the documentation for integrating springfox with data-rest I am seeing the following error:

```
2017-03-08 16:49:14.424 ERROR 22959 --- [           main] o.s.boot.SpringApplication               : Application startup failed

org.springframework.context.ApplicationContextException: Failed to start bean 'documentationPluginsBootstrapper'; nested exception is java.lang.NullPointerException
        at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178)
        at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:50)
        at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:348)
        at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:151)
        at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:114)
        at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:879)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:144)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:545)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:737)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:370)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:314)
        at [...].ServiceMain.main(ServiceMain.java:12)
Caused by: java.lang.NullPointerException: null
        at springfox.documentation.schema.WildcardType.wildcardMatch(WildcardType.java:50)
        at springfox.documentation.schema.AlternateTypeRule.appliesTo(AlternateTypeRule.java:80)
        at springfox.documentation.spi.schema.AlternateTypeProvider$1.apply(AlternateTypeProvider.java:57)
        at springfox.documentation.spi.schema.AlternateTypeProvider$1.apply(AlternateTypeProvider.java:54)
        at com.google.common.collect.Iterators$7.computeNext(Iterators.java:652)
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
        at com.google.common.collect.Iterators.tryFind(Iterators.java:752)
        at com.google.common.collect.Iterables.tryFind(Iterables.java:675)
        at com.google.common.collect.FluentIterable.firstMatch(FluentIterable.java:236)
        at springfox.documentation.spi.schema.AlternateTypeProvider.alternateFor(AlternateTypeProvider.java:42)
        at springfox.documentation.spi.service.contexts.RequestMappingContext.alternateFor(RequestMappingContext.java:118)
        at springfox.documentation.spring.web.readers.operation.OperationModelsProvider.collectFromReturnType(OperationModelsProvider.java:75)
        at springfox.documentation.spring.web.readers.operation.OperationModelsProvider.apply(OperationModelsProvider.java:56)
        at springfox.documentation.spring.web.plugins.DocumentationPluginsManager.modelContexts(DocumentationPluginsManager.java:139)
        at springfox.documentation.spring.web.scanners.ApiModelReader.read(ApiModelReader.java:63)
        at springfox.documentation.spring.web.scanners.ApiListingScanner.scan(ApiListingScanner.java:88)
        at springfox.documentation.spring.web.scanners.ApiDocumentationScanner.scan(ApiDocumentationScanner.java:70)
        at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.scanDocumentation(DocumentationPluginsBootstrapper.java:85)
        at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.start(DocumentationPluginsBootstrapper.java:127)
        at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:175)
        ... 12 common frames omitted
```

My SpringFox Configuration: (Error happens after I added the `@Import`)

```
@Configuration
@EnableSwagger2
@Import({springfox.documentation.spring.data.rest.configuration.SpringDataRestConfiguration.class})
public class SwaggerConfiguration {

    @Bean
    public Docket api() {
        return new Docket(DocumentationType.SWAGGER_2)
                .apiInfo(metadata())
                .useDefaultResponseMessages(false)
                .select()
                .apis(RequestHandlerSelectors.any())
                .paths(regex("/api.*"))
                .build();
    }

    private ApiInfo metadata() {
        return new ApiInfoBuilder()
                .title("Swagger Service")
                .description("Data Service")
                .build();
    }
}
```

Also, my main class is annotated with `@SpringBootApplication`

During my investigations, I tried to see if it could be related to the ObjectMapper issue mentioned on the documentation, but it doesn't seem to be the case

I have been trying to figure what could be happening for a while now, can somebody point me to a new direction? Would be much appreciated ;)

**Comment by dilipkrish** [comment]
Would you mind putting a breakpoint @ `at springfox.documentation.schema.AlternateTypeRule.appliesTo(AlternateTypeRule.java:80)` and see the values of `type` & `original`are. That should give you a clue as to which model is failing.

**Comment by raquelrag** [comment]
I am afraid I am still not understanding what is happening...

Adding the breakpoint showed me that the exception is thrown when the `type` variable is `null` and `original` is a `ResolvedObjectType` of `org.springframework.http.HttpEntity<springfox.documentation.schema.WildcardType>`

I tried walking a bit on the call stack but couldn't quite find which of my models could be the root cause. 

If it helps, the entities which repositories are annotated with `@RepositoryRestResource` are as follows: (kept only relevant annotations)

```
public class Building {

    private Long id;
    private String buildingId;
    private String name;
    private String spaceId;

    @JoinColumn
    @ManyToOne
    private Customer customer;

    // ...
}

public class Customer {

    private Long id;
    private String customerId;
    private String name;

    @OneToMany(mappedBy = "customer")
    private List<Building> buildings;

    // ...
}
```

Like I mentioned, there are other entities in the codebase but they have simple `@Repository` and respective `@RestController` 

PS: Thanks for the fast response @dilipkrish !

**Comment by dilipkrish** [comment]
Will take a look and let u know thanks for providing the additional info.

**Comment by raquelrag** [comment]
Ok, So I managed to kinda make it work with a workaround using multiple Dockets (our v1 api is using the simple spring controller and v2 uses spring-data).

Maybe this helps with your investigation..

Here's how it looks right now:
```
    @Bean
    public Docket apiVersion1() {
        return new Docket(DocumentationType.SWAGGER_2)
                .groupName("v1")
                .apiInfo(metadata())
                .useDefaultResponseMessages(false)
                .select()
                .apis(withClassAnnotation(RestController.class))
                .paths(regex("/api/v1.*"))
                .build();
    }

    @Bean
    public Docket apiVersion2() {
        return new Docket(DocumentationType.SWAGGER_2)
                .groupName("v2")
                .apiInfo(metadata())
                .useDefaultResponseMessages(false)
                .select()
                .apis(withClassAnnotations(RepositoryRestResource.class, RepositoryRestController.class))
                .paths(regex("/api/v2.*"))
                .build();
    }

   // Had to create this because needed an `or` on the annotations
    @SafeVarargs
    private final Predicate<RequestHandler> withClassAnnotations(final Class<? extends Annotation>... annotation) {
        return input -> Arrays.stream(annotation)
                .anyMatch(aClass -> input.declaringClass().isAnnotationPresent(aClass));
    }
```

**Comment by dilipkrish** [comment]
Its not clear how doing this fixed it 😕

**Comment by liudonghua123** [comment]
I have similar problem

```
org.springframework.context.ApplicationContextException: Failed to start bean 'documentationPluginsBootstrapper'; nested exception is java.lang.NullPointerException
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178) ~[spring-context-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:50) ~[spring-context-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:348) ~[spring-context-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:151) ~[spring-context-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:114) ~[spring-context-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:879) ~[spring-context-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:144) ~[spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:545) ~[spring-context-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:737) [spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:370) [spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) [spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1162) [spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1151) [spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at com.sight_spot_trip.Application.main(Application.java:10) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_112]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_112]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_112]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_112]
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) [spring-boot-devtools-1.5.3.RELEASE.jar:1.5.3.RELEASE]
Caused by: java.lang.NullPointerException: null
	at springfox.documentation.schema.WildcardType.wildcardMatch(WildcardType.java:50) ~[springfox-core-2.7.0-SNAPSHOT.jar:2.7.0-SNAPSHOT]
	at springfox.documentation.schema.AlternateTypeRule.appliesTo(AlternateTypeRule.java:79) ~[springfox-core-2.7.0-SNAPSHOT.jar:2.7.0-SNAPSHOT]
	at springfox.documentation.spi.schema.AlternateTypeProvider$1.apply(AlternateTypeProvider.java:57) ~[springfox-spi-2.7.0-SNAPSHOT.jar:2.7.0-SNAPSHOT]
	at springfox.documentation.spi.schema.AlternateTypeProvider$1.apply(AlternateTypeProvider.java:54) ~[springfox-spi-2.7.0-SNAPSHOT.jar:2.7.0-SNAPSHOT]
	at com.google.common.collect.Iterators$7.computeNext(Iterators.java:652) ~[guava-18.0.jar:na]
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143) ~[guava-18.0.jar:na]
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138) ~[guava-18.0.jar:na]
	at com.google.common.collect.Iterators.tryFind(Iterators.java:752) ~[guava-18.0.jar:na]
	at com.google.common.collect.Iterables.tryFind(Iterables.java:675) ~[guava-18.0.jar:na]
	at com.google.common.collect.FluentIterable.firstMatch(FluentIterable.java:236) ~[guava-18.0.jar:na]
	at springfox.documentation.spi.schema.AlternateTypeProvider.alternateFor(AlternateTypeProvider.java:41) ~[springfox-spi-2.7.0-SNAPSHOT.jar:2.7.0-SNAPSHOT]
	at springfox.documentation.spi.service.contexts.RequestMappingContext.alternateFor(RequestMappingContext.java:118) ~[springfox-spi-2.7.0-SNAPSHOT.jar:2.7.0-SNAPSHOT]
	at springfox.documentation.spring.web.readers.operation.OperationModelsProvider.collectFromReturnType(OperationModelsProvider.java:75) ~[springfox-spring-web-2.7.0-SNAPSHOT.jar:2.7.0-SNAPSHOT]
	at springfox.documentation.spring.web.readers.operation.OperationModelsProvider.apply(OperationModelsProvider.java:56) ~[springfox-spring-web-2.7.0-SNAPSHOT.jar:2.7.0-SNAPSHOT]
	at springfox.documentation.spring.web.plugins.DocumentationPluginsManager.modelContexts(DocumentationPluginsManager.java:136) ~[springfox-spring-web-2.7.0-SNAPSHOT.jar:2.7.0-SNAPSHOT]
	at springfox.documentation.spring.web.scanners.ApiModelReader.read(ApiModelReader.java:63) ~[springfox-spring-web-2.7.0-SNAPSHOT.jar:2.7.0-SNAPSHOT]
	at springfox.documentation.spring.web.scanners.ApiListingScanner.scan(ApiListingScanner.java:89) ~[springfox-spring-web-2.7.0-SNAPSHOT.jar:2.7.0-SNAPSHOT]
	at springfox.documentation.spring.web.scanners.ApiDocumentationScanner.scan(ApiDocumentationScanner.java:70) ~[springfox-spring-web-2.7.0-SNAPSHOT.jar:2.7.0-SNAPSHOT]
	at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.scanDocumentation(DocumentationPluginsBootstrapper.java:95) ~[springfox-spring-web-2.7.0-SNAPSHOT.jar:2.7.0-SNAPSHOT]
	at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.start(DocumentationPluginsBootstrapper.java:154) ~[springfox-spring-web-2.7.0-SNAPSHOT.jar:2.7.0-SNAPSHOT]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:175) ~[spring-context-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	... 19 common frames omitted
```

And I have put a breakpoint @ at springfox.documentation.schema.AlternateTypeRule.appliesTo(AlternateTypeRule.java:80), but it never went there.
