### ISSUE TITLE
2.7.0-SNAPSHOT breaks @Value placeholder replacement

### ISSUE THREAD

**Issue by stacysimpson** [springfox/springfox#1770]
I was trying to verify the fix for #1767 ; however, I'm seeing problems with @Value placeholder replacement using the HEAD of the 'master' branch. 

I build and published a 2.7.0-SNAPSHOT release to my local maven repo using the following command:
`./gradlew clean build publishToMavenLocal`

I've thoroughly reviewed #1621 and tried manipulating the order of our configuration bean; however, it doesn't seem to help.

```
@Configuration
@EnableConfigurationProperties
@ConfigurationProperties("premiseServer")
@Slf4j
public class ServletContainerConfiguration implements EmbeddedServletContainerCustomizer {
    ...
    @Value("${server.port}")
    int port;
    ...
}
```

Of course, going back to 2.6.1 works fine. Not sure where to go from here.

**Comment by dilipkrish** [comment]
Are you using spring boot?

**Comment by stacysimpson** [comment]
Yes, sorry...meant to mention that we are using spring boot v1.2.5

**Comment by dilipkrish** [comment]
:( 

Could you try adding a property sources configurer and see if that fixes your issue.

```java

@Bean
  public static PropertySourcesPlaceholderConfigurer springProperties() {
    return new PropertySourcesPlaceholderConfigurer();
  }

```

**Comment by stacysimpson** [comment]
Yeah, I started looking at that a bit earlier and get the following exception.

```
Exception in thread "main" org.springframework.context.ApplicationContextException: Failed to start bean 'documentationPluginsBootstrapper'; nested exception is java.util.ConcurrentModificationException
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:176)
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:51)
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:346)
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:149)
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:112)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:770)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:140)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:483)
...
Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at springfox.documentation.spring.web.plugins.DefaultRequestHandlerCombiner.combined(DefaultRequestHandlerCombiner.java:57)
	at springfox.documentation.spring.web.plugins.DefaultRequestHandlerCombiner.combine(DefaultRequestHandlerCombiner.java:44)
	at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.defaultContextBuilder(DocumentationPluginsBootstrapper.java:109)
	at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.buildContext(DocumentationPluginsBootstrapper.java:91)
	at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.start(DocumentationPluginsBootstrapper.java:154)
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:173)
	... 17 more
```
Didn't want to waste time digging into; however, if you think that is the correct path, I may need to roll up my sleeves.

**Comment by stacysimpson** [comment]
OK, I had some time this afternoon to look further into this issue. Below are the results of my investigation.

Here is the problematic commit: 9b254575ed9a399ec92470f715c38165e464d8ed. The description is 'Fixed the property resolution regression in spring boot'. Not sure why the migration from PropertyPlaceholderConfigurer to PropertySourcesPlaceholderConfigurer. I tried to revert this logic and ran into the 'ConcurrentModificationException' issue I described earlier. 

Furthermore, I tracked the 'ConcurrentModificationException' problem down to commit: bb764d4e2c48209f454c4afcc55161557f9af15d. The description is 'Added tests around path combination of same operations' and is part of a series of changes related to #1367. 

I haven't had a chance to dissect that series of changes or their purpose.

**Comment by stacysimpson** [comment]
May I ask why this issue was closed? I pulled down the HEAD of master and @Value placeholder replacement is still busted.

**Comment by dilipkrish** [comment]
It was bulk close, sorry

**Comment by dilipkrish** [comment]
Curious if just adding this bean fixes your problem. Will see how to fix this depending on your answer

```java
@Bean
  public static PropertySourcesPlaceholderConfigurer swaggerProperties() {
    PropertySourcesPlaceholderConfigurer properties = new PropertySourcesPlaceholderConfigurer();
    return properties;
  }
```

**Comment by stacysimpson** [comment]
Adding that bean results in the ConcurrentModificationException issue I described [earlier](https://github.com/springfox/springfox/issues/1770#issuecomment-293982810).

**Comment by dilipkrish** [comment]
You're still seeing that bug? I fixed that bug in #1780

**Comment by stacysimpson** [comment]
Sorry, I didn't catch that; yes, the concurrent modification exception seems to be resolved with the HEAD of master.

Adding that bean resolves the original @Value replacement problem; however, it causes additional issues with replacement of SPRINGFOX properties.

Reference:
![image](https://cloud.githubusercontent.com/assets/3578049/25340317/56c3056a-28d3-11e7-83c0-76512af60b5b.png)

**Comment by dilipkrish** [comment]
gah! 😭  Thanks for checking that.

**Comment by dilipkrish** [comment]
@stacysimpson Would be awesome if you could give it a whirl and see if its fixed. You shouldn't have to add any `PropertySources...` anymore.

**Comment by stacysimpson** [comment]
Looks good!
