### ISSUE TITLE
java.lang.NoClassDefFoundError: com/google/common/util/concurrent/FutureFallback

### ISSUE THREAD

**Issue by loxal** [springfox/springfox#1854]
I am using 

    compile "io.springfox:springfox-swagger2:${swaggerVersion}"
    compile "io.springfox:springfox-swagger-ui:${swaggerVersion}"

Am I the only one, or am I the only one reporting that when switching from 

        swaggerVersion = '2.6.1'
to

        swaggerVersion = '2.7.0'

I am getting:

> Caused by: java.lang.NoClassDefFoundError: com/google/common/util/concurrent/FutureFallback
	at org.springframework.cassandra.config.CassandraCqlClusterFactoryBean.newClusterBuilder(CassandraCqlClusterFactoryBean.java:251) ~[spring-cql-1.5.3.RELEASE.jar:na]
	at org.springframework.cassandra.config.CassandraCqlClusterFactoryBean.afterPropertiesSet(CassandraCqlClusterFactoryBean.java:145) ~[spring-cql-1.5.3.RELEASE.jar:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1687) ~[spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1624) ~[spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	... 77 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.google.common.util.concurrent.FutureFallback
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_131]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_131]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335) ~[na:1.8.0_131]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_131]
	... 81 common frames omitted

Could you include this an explicit runtime dependency in your library to resolve this issue?

**Comment by dilipkrish** [comment]
This is because the [datastax driver](https://github.com/datastax/java-driver/blob/3.x/pom.xml#L54) uses guava 19.0 and springfox uses 20.0. If you're not using [this convention](https://github.com/springfox/springfox/blob/master/springfox-spring-web/src/main/java/springfox/documentation/spring/web/plugins/JacksonSerializerConvention.java) it is safe to force your application to use v19.0 of guava.

**Comment by loxal** [comment]
Adding 

    // to enable Datastax’ Cassandra driver running alongside Swagger 2.7.0
    runtimeOnly 'com.google.guava:guava:19.0'

…to my Gradle configuration worked fine for me.
