### ISSUE TITLE
NullPointerException with Spring Data Rest integration

### ISSUE THREAD

**Issue by drenda** [springfox/springfox#1876]
I'm using springfox-swagger2, springfox-swagger-ui and springfox-data-rest versione 2.7.0 to document Spring Data Rest repositories.

I created my configuration class:

```java
@Configuration
@EnableSwagger2
@Import({ springfox.documentation.spring.data.rest.configuration.SpringDataRestConfiguration.class })
public class SwaggerConfig {
	@Bean
	public Docket api() {
		return new Docket(DocumentationType.SWAGGER_2).select().apis(RequestHandlerSelectors.basePackage("com.test.rest"))
				.paths(PathSelectors.any()).build();
	}
```

Unfortunately I've a NullPointerException:

```stacktrace 
org.springframework.context.ApplicationContextException: Failed to start bean 'documentationPluginsBootstrapper'; nested exception is java.lang.NullPointerException
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178) ~[spring-context-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:50) ~[spring-context-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:348) ~[spring-context-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:151) ~[spring-context-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:114) ~[spring-context-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:880) ~[spring-context-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:144) ~[spring-boot-1.5.4.RELEASE.jar:1.5.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546) ~[spring-context-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.4.RELEASE.jar:1.5.4.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) [spring-boot-1.5.4.RELEASE.jar:1.5.4.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) [spring-boot-1.5.4.RELEASE.jar:1.5.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) [spring-boot-1.5.4.RELEASE.jar:1.5.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [spring-boot-1.5.4.RELEASE.jar:1.5.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [spring-boot-1.5.4.RELEASE.jar:1.5.4.RELEASE]
	at com.test.rest.BusletApplication.main(BusletApplication.java:12) [classes/:na]
Caused by: java.lang.NullPointerException: null
	at springfox.documentation.builders.RequestHandlerSelectors$4.apply(RequestHandlerSelectors.java:97) ~[springfox-core-2.7.0.jar:2.7.0]
	at springfox.documentation.builders.RequestHandlerSelectors$4.apply(RequestHandlerSelectors.java:94) ~[springfox-core-2.7.0.jar:2.7.0]
	at com.google.common.base.Present.transform(Present.java:71) ~[guava-18.0.jar:na]
	at springfox.documentation.builders.RequestHandlerSelectors$5.apply(RequestHandlerSelectors.java:113) ~[springfox-core-2.7.0.jar:2.7.0]
	at springfox.documentation.builders.RequestHandlerSelectors$5.apply(RequestHandlerSelectors.java:110) ~[springfox-core-2.7.0.jar:2.7.0]
	at com.google.common.base.Predicates$AndPredicate.apply(Predicates.java:359) ~[guava-18.0.jar:na]
	at com.google.common.base.Predicates$AndPredicate.apply(Predicates.java:359) ~[guava-18.0.jar:na]
	at com.google.common.collect.Iterators$7.computeNext(Iterators.java:652) ~[guava-18.0.jar:na]
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143) ~[guava-18.0.jar:na]
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138) ~[guava-18.0.jar:na]
	at springfox.documentation.spring.web.scanners.ApiListingReferenceScanner.scan(ApiListingReferenceScanner.java:48) ~[springfox-spring-web-2.7.0.jar:2.7.0]
	at springfox.documentation.spring.web.scanners.ApiDocumentationScanner.scan(ApiDocumentationScanner.java:67) ~[springfox-spring-web-2.7.0.jar:2.7.0]
	at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.scanDocumentation(DocumentationPluginsBootstrapper.java:95) ~[springfox-spring-web-2.7.0.jar:2.7.0]
	at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.start(DocumentationPluginsBootstrapper.java:154) ~[springfox-spring-web-2.7.0.jar:2.7.0]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:175) ~[spring-context-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	... 14 common frames omitted`
```

Removing the inclusion of SpringDataRestConfiguration.class Swagger starts correctly (but of course it doesn't display resourses of Spring data rest repositories).

I tried to debug the point where the exception happens and I found the input variable is a proxy: springfox.documentation.builders.RequestHandlerSelectors$4@7210f559 class com.sun.proxy.$Proxy167

and the call to getPackage() return an error.

Is this a bug? Should this exception be handled? How could I fix the problem meanwhile?

Thanks

**Comment by JimAllanson** [comment]
The simplest solution I found to this issue was to omit the base path selector from the Docket configuration, and filter using only PathSelectors instead.

**Comment by dilipkrish** [comment]
I think this is a bug.

**Comment by dilipkrish** [comment]
Do you have a controller perhaps that doesnt belong to a package?

**Comment by JimAllanson** [comment]
If I recall correctly, in my case this seemed to be caused by using the @RepositoryRestController annotation, which causes Spring to use default controllers to wrap a repository. The request handlers for these were Proxy classes and as such did not have packages.

**Comment by dtsey** [comment]
If I use AOP advice on my method within **@RestController** I face this issue too because Spring creates proxy class to wrap controller's method call. To avoid this issue I have to downgrade to swagger-ui 2.5.0

I see absolutely the same exception stack trace so there is no need to publish it here. ;)

Thank you.

**Comment by dilipkrish** [comment]
Will will be out in the next release

**Comment by iPhotoner** [comment]
unresolved in boot 2.0.0RC1 / springfox[2.8.0,2.7.0,2.6.1]

**Comment by cc4dogman** [comment]
Spring Boot 2.0.5 Spring fox 2.9.2 not yet fix

**Comment by KobeAndLebron** [comment]
Downgrade springfox to 2.5.0 will resolve this issue temporarily.

**Comment by nicodmt** [comment]
Same issue still alive!  Spring Boot 2.6.0 with SpringFox 3.0.0

		

		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger2</artifactId>
			<version>3.0.0</version>
		</dependency>

		
		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger-ui</artifactId>
			<version>3.0.0</version>
		</dependency>

		
		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-boot-starter</artifactId>
			<version>3.0.0</version>
		</dependency>




@SpringBootApplication
@EnableSwagger2
public class XXXApplication {
	public static void main(String[] args) {
		SpringApplication.run(XXXApplication.class, args);
	}

	@Bean
	public Docket swaggerConfiguration(){
		// Return a prepared Docket instance
		return new Docket(DocumentationType.SWAGGER_2)
				.select()
				.paths(PathSelectors.ant("/api/*"))
				.apis(RequestHandlerSelectors.basePackage("my.package.path.to.controller"))
				.build();
	}
}



@RestController
@RequestMapping("/api")
public class XXXController {

    @GetMapping(value = {"/status"})
    public @ResponseBody
    String response() {
        return "{\"status\":\"UP\"}";
    }
}

Logs:

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2021-11-30 09:10:09.462 ERROR 13200 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.context.ApplicationContextException: Failed to start bean 'documentationPluginsBootstrapper'; nested exception is java.lang.NullPointerException
