### ISSUE TITLE
Springfox support for open API 

### ISSUE THREAD

**Issue by rohitdev** [springfox/springfox#2124]
I'm trying to use:
Springfox :2.7.0
Swagger annotations, models : 2.0.0-rc2
Spring : 5
Java : 8

I've annotated using OpenAPI specs (package name : io.swagger.oas.annotations) it doesn't seem to be working.
As i understand that support for OpenAPI is work in progress? Any timelines as to when it would be available?

Let me know if this is a bug or feature request.

<details>
	<summary>Stacktrace</summary>

```log
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'licenseMapperImpl': Lookup method resolution failed; nested exception is java.lang.IllegalStateException: Failed to introspect Class [springfox.documentation.swagger2.mappers.LicenseMapper] from ClassLoader [sun.misc.Launcher$AppClassLoader@4e25154f]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.determineCandidateConstructors(AutowiredAnnotationBeanPostProcessor.java:262)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineConstructorsFromBeanPostProcessors(AbstractAutowireCapableBeanFactory.java:1197)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1122)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:502)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:312)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:310)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:756)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:868)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
	at org.springframework.web.servlet.FrameworkServlet.configureAndRefreshWebApplicationContext(FrameworkServlet.java:676)
	at org.springframework.web.servlet.FrameworkServlet.initWebApplicationContext(FrameworkServlet.java:545)
	at org.springframework.web.servlet.FrameworkServlet.initServletBean(FrameworkServlet.java:499)
	at org.springframework.web.servlet.HttpServletBean.init(HttpServletBean.java:172)
	at javax.servlet.GenericServlet.init(GenericServlet.java:244)
	at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:117)
	at io.undertow.servlet.core.ManagedServlet$DefaultInstanceStrategy.start(ManagedServlet.java:250)
	at io.undertow.servlet.core.ManagedServlet.getServlet(ManagedServlet.java:171)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:84)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:211)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:809)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Failed to introspect Class [springfox.documentation.swagger2.mappers.LicenseMapper] from ClassLoader [sun.misc.Launcher$AppClassLoader@4e25154f]
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:659)
	at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:556)
	at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:569)
	at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:541)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.determineCandidateConstructors(AutowiredAnnotationBeanPostProcessor.java:245)
	... 46 common frames omitted
Caused by: java.lang.NoClassDefFoundError: io/swagger/models/License
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethods(Class.java:1975)
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:641)
	... 50 common frames omitted
Caused by: java.lang.ClassNotFoundException: io.swagger.models.License
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 54 common frames omitted
```
</details>

**Comment by dilipkrish** [comment]
Swagger/OAS 3.0 isn't yet supported

**Comment by rnavarropiris** [comment]
what is the planed roadmap for oas3 support? Any release date or version?
Any hope this is going to be part of 2.9.0?

**Comment by dilipkrish** [comment]
@rnavarropiris yes that is the plan for sure

**Comment by renannprado** [comment]
I tried to search for support for oas3 in #2372 but couldn't find it.
@dilipkrish do you know when will it happen?
Thanks for the amazing work so far!

**Comment by dilipkrish** [comment]
@renannprado It will be supported in the next version. 

I dont understand what you mean. 

"setup the openapi generator" "without a dependency on springfox"? Are you talking about of just taking in the generated 2.0 but transforming it to OAS 3.0? 

>  I was migrating jax-rs application to MVC and bumped into this :(

Not clear what you bumped into.

**Comment by renannprado** [comment]
@dilipkrish by next version do you mean `2.9.0`?

Let me clarify: I'm migrating an application from JAX-RS to Spring MVC.
However, there's official support for JAX-RS from swagger, and that's what's being used right now. So when I was migrating to Spring MVC (using springfox) I realized that the same annotations couldn't be used as springfox still depends on swagger-core 1.5.x.
So my question is: can I setup swagger-core 2.x without springfox (I don't care about MVC integration at this time) to generate the openapi spec? If yes then I would be able to keep most of the existing annotations (which are swagger-core 2.x) instead of downgrading them to swagger-core 1.5.x to be compatible to springfox.

**Comment by dilipkrish** [comment]
Next version I mean 3.0

**Comment by renannprado** [comment]
I understand that, but at this moment I'm willing to annotate everything the without help from speingfox just so that I can keep the existing annotations. Do you think that's possible?
Also, when is version 3 out?

**Comment by dilipkrish** [comment]
Thats definitely possible.Out of curiosity why are you moving from JAX-rs to spring?

**Comment by renannprado** [comment]
That is possible, but do you know how can I generate the openapi spec out of it?
Let's say I just annotate a regular class with swagger annotations, how do I generate the openapi spec out of it? I understand that this kind of question is more for the swagger guys than to you, but as you've developed springfox, I thought you'd able to help me with this.

Talking about why I'm migrating: if you are using spring, I don't see a reason not to use spring MVC (or webflux now) instead of JAX-RS mostly because it much better integrated with the framework and it's easier to test spring MVC (`@WebMvcTest`) than JAX-RS

**Comment by dilipkrish** [comment]
>  if you are using spring, I don't see a reason not to use spring MVC (or webflux now) 

That provides some context.

> Let's say I just annotate a regular class (non @RestController, etc) with swagger annotations, how do I generate the openapi spec out of it? I

Currently, you can only generate Swagger 2.0 spec using springfox. However there are other tools you can use in combination that can do the translation [like this](https://github.com/Mermade/swagger2openapi). The idea is to use springfox as-is. Create an integration test that generates the `spec.json` and you can transform that to open-api-spec.json. That is the same technique used by [swagger2markup](https://github.com/Swagger2Markup/swagger2markup)

**Comment by nbeucler** [comment]
Hello,

Any new about supporting OAS3?

**Comment by raderio** [comment]
Is there a branch where we can test or contribute for OAS3?

**Comment by rajashekarreddybobbili** [comment]
@dilipkrish I am using (springfox-swagger2:2.9.2), I am not able to use swagger 2.x Annotations. but i am able to use 1.5 Annotations. In the 1.5x Annotions few things are not working for me.
for example: @ApiParam in this unable to use allowableValues. My eventual goal is OAS 3.0.
can you suggest something, how can i overcome ?
