### ISSUE TITLE
SpringBootTest context cannot be built with SpringBootTest.WebEnvironment.NONE

### ISSUE THREAD

**Issue by d53dave** [springfox/springfox#2141]
With SpringFox 2.7 and Spring Boot 2.0.0.M7 (and M5) I encounter the following issue:

If I want to create a test context without the web environment, i.e.

```java
@RunWith(SpringRunner.class)
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.NONE)
public class DemoApplicationTests {

	@Test
	public void contextLoads() {
	}

}
```

it fails to create the context with the following stack trace (snippet):
```
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'documentationPluginsManager': Unsatisfied dependency expressed through field 'documentationPlugins'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.plugin.core.PluginRegistry<springfox.documentation.spi.service.DocumentationPlugin, springfox.documentation.spi.DocumentationType>' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true), @org.springframework.beans.factory.annotation.Qualifier(value=documentationPluginRegistry)}
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:586)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:91)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:372)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1344)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:502)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:312)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:310)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:251)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1135)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1062)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:815)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:721)
	... 71 more
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.plugin.core.PluginRegistry<springfox.documentation.spi.service.DocumentationPlugin, springfox.documentation.spi.DocumentationType>' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true), @org.springframework.beans.factory.annotation.Qualifier(value=documentationPluginRegistry)}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1504)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1101)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1062)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:583)
	... 85 more
```

I tried disabling the `@EnableSwagger2` class with `@ConditionalOnBean(WebMvcAutoConfiguration.class)` but that didn't fix the issue.

When enabling debug output, it seems that my `SwaggerConfig` should not be taken into consideration, because the `@ConditionalOnBean` correctly does not match:

```
 SwaggerConfig:
      Did not match:
         - @ConditionalOnBean (types: org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration; SearchStrategy: all) did not find any beans of type org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration (OnBeanCondition)
```

I created a minimal spring boot project (from Spring Initializr) that has a failing test here: [springfox-failing-spring-boot.zip](https://github.com/springfox/springfox/files/1548328/springfox-failing-spring-boot.zip)

**Comment by dilipkrish** [comment]
Thanks for reporting it! Thats super useful to have an example failing scenario!

**Comment by dilipkrish** [comment]
I looked at your sample, and I commented out the following lines

`DemoApplicationTests.java`
```java
//@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.NONE)
```

`DemoApplication.java
```java
//@ConditionalOnBean(WebMvcAutoConfiguration.class)
//@AutoConfigureAfter(WebMvcAutoConfiguration.class)
```

And everything seems to work. So it sounds like you need to configure your application correctly in order to test what you intend to test.

**Comment by d53dave** [comment]
Thanks for looking into that!

The point is to not comment out

```java
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.NONE)
```

since there are a lot of cases where one would want to test some things but doesn't want the whole web context started, which adds significant overhead to the tests. 

In short, I think springfox should only register it's endpoints if the MVC stack is loaded. Or in other words, it should not break when I decide to to start without SpringMVC.

**Comment by dilipkrish** [comment]
Agreed, I'll see if it can be fixed, but spring has ways of doing those kinds of tests (controller tests). In this case we're trying to run an integration tests without loading up the web environment

**Comment by d53dave** [comment]
Let me know if I can help (i.e. some pointers where I might find the right spots for a fix). Since we are using springfox, my company might be fine with me spending a bit of time with fixing that bug.

**Comment by dilipkrish** [comment]
@d53dave actually Im curious why you aren't using an `@WebMvcTest` instead

**Comment by markandirene** [comment]
I'm still getting the same issue as reported by d53dave. I'm using version 2.8.0.
I need @EnableSwagger2 when @SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.NONE)

**Comment by dilipkrish** [comment]
It should be fixed in the next release ... or you could try 2.8.1-SNAPSHOT and let me know if its still broken
