### ISSUE TITLE
Failed to start bean 'documentationPluginsBootstrapper'

### ISSUE THREAD

**Issue by jearton** [springfox/springfox#2152]
I encounter an occasional exception which can not be exactly reproduce. The stacktrace is below:

```
Application startup failed

org.springframework.context.ApplicationContextException: Failed to start bean 'documentationPluginsBootstrapper'; nested exception is java.lang.IllegalArgumentException: Multiple entries with same key: springfox.documentation.spring.web.plugins.PathAndParametersEquivalence@4da7cf6b.wrap(springfox.documentation.spring.web.WebMvcRequestHandler@5c7daea0)=[springfox.documentation.spring.web.WebMvcRequestHandler@5c7daea0] and springfox.documentation.spring.web.plugins.PathAndParametersEquivalence@4da7cf6b.wrap(springfox.documentation.spring.web.WebMvcRequestHandler@381402f3)=[springfox.documentation.spring.web.WebMvcRequestHandler@381402f3]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178) ~[spring-context-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:50) ~[spring-context-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:348) ~[spring-context-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:151) ~[spring-context-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:114) ~[spring-context-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:880) ~[spring-context-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:144) ~[spring-boot-1.5.9.RELEASE.jar:1.5.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546) ~[spring-context-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.9.RELEASE.jar:1.5.9.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) ~[spring-boot-1.5.9.RELEASE.jar:1.5.9.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) ~[spring-boot-1.5.9.RELEASE.jar:1.5.9.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) ~[spring-boot-1.5.9.RELEASE.jar:1.5.9.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) ~[spring-boot-1.5.9.RELEASE.jar:1.5.9.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) ~[spring-boot-1.5.9.RELEASE.jar:1.5.9.RELEASE]
	at com.qianbao.vinci.registry.VinciRegistryApp.main(VinciRegistryApp.java:31) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) ~[spring-boot-devtools-1.5.9.RELEASE.jar:1.5.9.RELEASE]
Caused by: java.lang.IllegalArgumentException: Multiple entries with same key: springfox.documentation.spring.web.plugins.PathAndParametersEquivalence@4da7cf6b.wrap(springfox.documentation.spring.web.WebMvcRequestHandler@5c7daea0)=[springfox.documentation.spring.web.WebMvcRequestHandler@5c7daea0] and springfox.documentation.spring.web.plugins.PathAndParametersEquivalence@4da7cf6b.wrap(springfox.documentation.spring.web.WebMvcRequestHandler@381402f3)=[springfox.documentation.spring.web.WebMvcRequestHandler@381402f3]
	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:190) ~[guava-22.0.jar:?]
	at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:109) ~[guava-22.0.jar:?]
	at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:95) ~[guava-22.0.jar:?]
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:357) ~[guava-22.0.jar:?]
	at com.google.common.collect.ImmutableListMultimap.copyOf(ImmutableListMultimap.java:372) ~[guava-22.0.jar:?]
	at com.google.common.collect.ImmutableMultimap.copyOf(ImmutableMultimap.java:320) ~[guava-22.0.jar:?]
	at com.google.common.collect.ImmutableMultimap$Builder.build(ImmutableMultimap.java:296) ~[guava-22.0.jar:?]
	at com.google.common.collect.ImmutableListMultimap$Builder.build(ImmutableListMultimap.java:328) ~[guava-22.0.jar:?]
	at com.google.common.collect.Multimaps.index(Multimaps.java:1639) ~[guava-22.0.jar:?]
	at com.google.common.collect.Multimaps.index(Multimaps.java:1590) ~[guava-22.0.jar:?]
	at springfox.documentation.spring.web.plugins.DefaultRequestHandlerCombiner.combined(DefaultRequestHandlerCombiner.java:59) ~[springfox-spring-web-2.7.0.jar:2.7.0]
	at springfox.documentation.spring.web.plugins.DefaultRequestHandlerCombiner.combine(DefaultRequestHandlerCombiner.java:49) ~[springfox-spring-web-2.7.0.jar:2.7.0]
	at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.defaultContextBuilder(DocumentationPluginsBootstrapper.java:106) ~[springfox-spring-web-2.7.0.jar:2.7.0]
	at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.buildContext(DocumentationPluginsBootstrapper.java:91) ~[springfox-spring-web-2.7.0.jar:2.7.0]
	at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.start(DocumentationPluginsBootstrapper.java:154) ~[springfox-spring-web-2.7.0.jar:2.7.0]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:175) ~[spring-context-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	... 19 more

```

I'm using springfox2.7 + spring cloud config server 1.4.0. I config docket paths regex to /.*

**Comment by dilipkrish** [comment]
I suspect this may have been fixed. Would you mind testing with 2.7.0-SNAPSHOT?
