### ISSUE TITLE
@ApiParam list renders first element only, List<LocalDate>

### ISSUE THREAD

**Issue by sddakoty** [springfox/springfox#2192]
```
@ApiParam(allowMultiple = true, value = "provide multiple dates")
private List<LocalDate> daterange;
```

Renders as:
```
daterange[0].year
daterange[0].month
(both as integer)
```

Expected: the LocalDate should not render as year/month portion, but as one parameter. Also it's not possible to input multiple values here for the list.

Using springfox 2.8.0

**Comment by dilipkrish** [comment]
List is unbounded so it just does a best effort to generate schema for adding atleast one element. This is working as designed.

**Comment by sddakoty** [comment]
Ok, but wouldn't it be possible to add some kind of flag to the annotation so that the springfox interprets the element of the list as a "normal String" in yyyy-MM-dd format?

And what do you mean with "unbounded"? I think a list will always be a collection of multiple elements, so I'd assume this should always be clear to swagger that there is not only a single element expected?

**Comment by MaksimOrlov** [comment]
@sddakoty, you can use *alternate type rule* to substitute **LocalDate** with **String** 

>  I think a list will always be a collection of multiple elements, so I'd assume this should always be clear to swagger that there is not only a single element expected?

There is limitation for Swagger Spec and Swagger-ui, it is impossible to add as many Array/List items as possible to test endpoint.

**Comment by sddakoty** [comment]
@MaksimOrlov could you give an example on how to replace LocalDate with String.class using AlternateTypeRule?

**Comment by MaksimOrlov** [comment]
@sddakoty, sure:

```
@Configuration
@EnableSwagger2
public class SwaggerConfig extends WebMvcConfigurerAdapter {
    @Bean
    public Docket restApiDocket() {
        return new Docket(DocumentationType.SWAGGER_2)
                 //here is the line that you need
                .directModelSubstitute(LocalDate.class, String.class)
                .select()
                .apis(RequestHandlerSelectors.any())
                .paths(PathSelectors.regex("/.*"))
                .build()
                .pathMapping("/");
    }
}
```

**Comment by sddakoty** [comment]
Unfortunately the ```LocalDate``` is still shown as year/month integer:
```
daterange[0].year
daterange[0].month
(both as integer)
```

**Comment by MaksimOrlov** [comment]
Could you try with alternateTypeRyles:

```
@Configuration
@EnableSwagger2
public class SwaggerConfig extends WebMvcConfigurerAdapter {
 
    @Autowired
    private TypeResolver typeResolver;

    @Bean
    public Docket restApiDocket() {
        return new Docket(DocumentationType.SWAGGER_2)
                 //here is the line that you need
                .alternateTypeRules(
                        newRule(typeResolver.resolve(LocalDate.class),
                            typeResolver.resolve(String.class)))
                .select()
                .apis(RequestHandlerSelectors.any())
                .paths(PathSelectors.regex("/.*"))
                .build()
                .pathMapping("/");
    }
}
```

**Comment by sddakoty** [comment]
Neither did that change anything...

**Comment by dilipkrish** [comment]
The rule needs to be ...

```java
                 //here is the line that you need
                .alternateTypeRules(
                        newRule(typeResolver.resolve(List.class, LocalDate.class),
                            typeResolver.resolve(List.class, String.class)))
```
OR
```java
                 //here is the line that you need
                .alternateTypeRules(
                        newRule(typeResolver.resolve(List.class, LocalDate.class),
                            typeResolver.resolve(List.class, java.util.Date.class)))
```

**Comment by sddakoty** [comment]
Both results in the following error:

The webpage shows:
```
Failed to load API definition.
undefined http://localhost:8080/api-docs
```

The stacktrace shows:
```
java.lang.NullPointerException: the Function passed to Optional.transform() must not return null.
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:805) ~[guava-23.0.jar:?]
	at com.google.common.base.Present.transform(Present.java:76) ~[guava-23.0.jar:?]
	at springfox.documentation.schema.ModelRef.getItemType(ModelRef.java:76) ~[springfox-core-2.8.0.jar:2.8.0]
	at springfox.documentation.swagger2.mappers.ParameterMapper.fromModelRef(ParameterMapper.java:61) ~[springfox-swagger2-2.8.0.jar:2.8.0]
	at springfox.documentation.swagger2.mappers.ParameterMapper.bodyParameter(ParameterMapper.java:46) ~[springfox-swagger2-2.8.0.jar:2.8.0]
	at springfox.documentation.swagger2.mappers.ParameterMapper.mapParameter(ParameterMapper.java:41) ~[springfox-swagger2-2.8.0.jar:2.8.0]
```

**Comment by MaksimOrlov** [comment]
@sddakoty, the rules are correct, but, unfortunately, here is a bug, details are in this [issue](https://github.com/springfox/springfox/issues/2231).

**Comment by MaksimOrlov** [comment]
@sddakoty, the bug was fixed at the 2.8.1-SNAPSHOT.  Would be awesome to get your feedback.
