### ISSUE TITLE
Schema error: should NOT have additional properties allowEmptyValue

### ISSUE THREAD

**Issue by igorko** [springfox/springfox#2204]
Please take the time to search the repository, if your question has already been asked or answered.

- [ ] Version 2.8

What kind of issue is this?
 - [ ] Bug report.

 - [ ] I guess this is a regression between 2.7 and 2.8, related to this issue https://github.com/springfox/springfox/issues/2021.

When I put auto-generated swagger into online swagger editor I get next error

> Schema error at definitions['MyClass'].properties['id']
> should NOT have additional properties
> additionalProperty: allowEmptyValue
> Jump to line 1523

and

> Schema error at definitions['MyClass'].properties['description']
> should NOT have additional properties
> additionalProperty: allowEmptyValue
> Jump to line 1523

And class definition is next
```
public final class MyClass {
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @ApiModelProperty(readOnly = true)
    @Setter
    @Getter
    private String id;

    @NotNull
    @ApiModelProperty(required = true)
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @Setter
    @Getter
    private String description;
}
```

Definition in swagger is next

>    MyClass:
>     type: object
>     required:
>       - description
>     properties:
>       description:
>         type: string
>         allowEmptyValue: false
>       id:
>         type: string
>         readOnly: true
>         allowEmptyValue: false
>     title: Source

As I understand allowEmptyValue is not valid property for scheme property. Btw I am using MyClass as @RequestBody.
Is it possible to avoid adding allowEmptyValue to property definition? In my case I have @NotNull and required = true, but none of them says value cannot be empty. I am using swagger-ui 2.8.0

**Comment by svenhofstede** [comment]
+1 

Once you set @ApiModelProperty() for a entity field, the YARM generation adds allowEmptyValue to Entity schema definition. It does this regardless if you actually set the allowEmptyValue field in the @ApiModelProperty or not.

**Comment by stoutfiles** [comment]
This regression is a huge breaking change, how did this pass tests?

**Comment by amfine-soft-drault** [comment]
Hi 
any (even rough) idea when a release with this fix could be made available ?
thanks
David

**Comment by dilipkrish** [comment]
@amfine-soft-drault end of this month

**Comment by amfine-soft-drault** [comment]
Hi
just to be sure, did you mean end-of-march or end-of-april ?

**Comment by dilipkrish** [comment]
@amfine-soft-drault end of march... trying to wrap up a few more fixes

**Comment by vikramsetty** [comment]
When can we expect to have this correction available?

**Comment by josebrandao13** [comment]
Hey, how is the state of this issue?

**Comment by dilipkrish** [comment]
Its been fixed and will be released shortly

**Comment by geik** [comment]
Thanks!  Much appreciated!

**Comment by dnavarro** [comment]
I have just tried the 2.9.0 Release from JCenter and it seems that this regression is still there.

If I anotate my class with:

```
public class XXXX {

	private String name;

	@ApiModelProperty(required = true,value = "name",dataType="String")
	public String getName() {
		return name;
	}
```

The resultant swagger documentation for the correspondant definition includes:

```
		"XXX": {
			"type": "object",
			"required": ["name"],
			"properties": {
				"name": {
					"type": "string",
					"description": "name",
					"allowEmptyValue": false
				},
```

**Such _allowEmptyValue_ is uncompliant with the API scheme.

So I think this issue should be reopened.**

**Comment by dilipkrish** [comment]
@dnavarro Could you perhaps create a breaking test. Im unable to reproduce it.

**Comment by dnavarro** [comment]
Forgive @dilipkrish.

I was about to add another comment explaining that having done further tests I can confirm that 2.9.0 corrects this issue.

I had messed my pom and despite thinking I was using 2.9.0, I was actually still using 2.8.0 during the application execution.

**Comment by ChandrasekharRajoli** [comment]
Good. But, unfortunately, this fix is not available in Maven. Looking forward to 2.9.1 release for Maven. Could you please release the 2.9.1 version to Maven central. Thank you.

**Comment by dilipkrish** [comment]
It is available in jcenter.

**Comment by josebrandao13** [comment]
I followed this tutorial : http://www.baeldung.com/swagger-2-documentation-for-spring-rest-api
and I'm using 2.9.1 maven version.
The swagger-UI works fine and presents no errors but when I try to use the generated json with the [swagger editor](https://editor.swagger.io/) or with the [swagger-confluence-plugin](https://github.com/starlightknight/swagger-confluence) the schema looks invalid.

### **Swagger Editor Errors:**

Schema error at info.license
**should have required property 'name'**
missingProperty: name

Schema error at paths['/xxx/xxx'].get.parameters[0]
**should NOT have additional properties**
additionalProperty: items, name, in, description, required

Schema error at paths['/xxx/xxx'].get.parameters[0].in
**should be equal to one of the allowed values**
allowedValues: body, formData, query, path
...

And a lot more errors like this.

### **Swagger Confluence Plugin:**

Error when converting swagger schema to Ascii Doc... Tryied with valid schemas on the editor and works perfectly.

`2018-07-09 14:31:07.832  INFO - [main] n.s.s.c.s.i.SwaggerToAsciiDocServiceImpl : Converting Swagger Schema to Ascii Doc...
Exception in thread "main" java.lang.NullPointerException: The validated character sequence is blank
	at org.apache.commons.lang3.Validate.notBlank(Validate.java:448)
	at org.apache.commons.lang3.Validate.notBlank(Validate.java:476)
	at io.github.swagger2markup.internal.type.BasicType.<init>(BasicType.java:41)
	at io.github.swagger2markup.internal.utils.ParameterUtils.getType(ParameterUtils.java:64)
	at io.github.swagger2markup.internal.document.builder.PathsDocumentBuilder.buildParametersSection(PathsDocumentBuilder.java:435)
	at io.github.swagger2markup.internal.document.builder.PathsDocumentBuilder.buildOperation(PathsDocumentBuilder.java:275)
	at io.github.swagger2markup.internal.document.builder.PathsDocumentBuilder.buildOperation(PathsDocumentBuilder.java:254)
	at io.github.swagger2markup.internal.document.builder.PathsDocumentBuilder.buildsPathsSection(PathsDocumentBuilder.java:152)
	at io.github.swagger2markup.internal.document.builder.PathsDocumentBuilder.build(PathsDocumentBuilder.java:140)
	at io.github.swagger2markup.Swagger2MarkupConverter.toString(Swagger2MarkupConverter.java:234)
	at net.slkdev.swagger.confluence.service.impl.SwaggerToAsciiDocServiceImpl.convertSwaggerToAsciiDoc(SwaggerToAsciiDocServiceImpl.java:67)
	at net.slkdev.swagger.confluence.service.impl.SwaggerToConfluenceServiceImpl.convertSwaggerToConfluence(SwaggerToConfluenceServiceImpl.java:73)
	at net.slkdev.swagger.confluence.cli.SwaggerConfluence.runCLI(SwaggerConfluence.java:63)
	at net.slkdev.swagger.confluence.cli.SwaggerConfluence.main(SwaggerConfluence.java:39)`


Does anyone have an idea of what it could be?
Thanks in advance.

**Comment by dilipkrish** [comment]
@josebrandao13  Seems like a bug in [swagger2markup](https://github.com/Swagger2Markup/swagger2markup). Also please you springfox 2.9.2

**Comment by josebrandao13** [comment]
@dilipkrish just tried 2.9.2 and keep having the same errors on swagger editor online with the json output. Anything else I could try?

**Comment by dilipkrish** [comment]
@josebrandao13 2.9.2 doesnt fix the swagger2markup bug, it just the latest version

**Comment by dilipkrish** [comment]
@falknerdominik what issue are you referring to?

**Comment by samqhr** [comment]
My only solution for this was to roll back to 2.7.0 where this invalid property was not being generated; and "allowEmptyValue " is not valid OpenAPI spec as far as I can tell, 

The editor.swagger.io will reject these files (We have automated processes that validate swagger files).

**Comment by taddygrrr** [comment]
@dilipkrish, please reopen this.    In 2.9.2, spring fox still producing "allowEmptyValue" in generated spec for @ApiModelProperty annotation.  Thanks.

**Comment by shuchitaprasad** [comment]
Upgrading below versions removed the error in gradle for me

compile group: 'io.springfox', name: 'springfox-swagger2', version: '2.9.2'
compile group: 'io.springfox', name: 'springfox-swagger-ui', version: '2.9.2'
