### ISSUE TITLE
java.lang.StackOverflowError

### ISSUE THREAD

**Issue by ddmonk** [springfox/springfox#2232]
Version : 2.7.0
My bean model like this:
```
class A {
     B b;
}

class B {
    List<A> as;
}
```

The application server fail to start with the following error :
`org.springframework.context.ApplicationContextException: Failed to start bean 'documentationPluginsBootstrapper'; nested exception is com.google.common.util.concurrent.ExecutionError: java.lang.StackOverflowError
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178) ~[spring-context-4.3.10.RELEASE.jar:4.3.10.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:50) ~[spring-context-4.3.10.RELEASE.jar:4.3.10.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:348) ~[spring-context-4.3.10.RELEASE.jar:4.3.10.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:151) ~[spring-context-4.3.10.RELEASE.jar:4.3.10.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:114) ~[spring-context-4.3.10.RELEASE.jar:4.3.10.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:880) ~[spring-context-4.3.10.RELEASE.jar:4.3.10.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:144) ~[spring-boot-1.5.6.RELEASE.jar:1.5.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546) ~[spring-context-4.3.10.RELEASE.jar:4.3.10.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.6.RELEASE.jar:1.5.6.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) [spring-boot-1.5.6.RELEASE.jar:1.5.6.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) [spring-boot-1.5.6.RELEASE.jar:1.5.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) [spring-boot-1.5.6.RELEASE.jar:1.5.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [spring-boot-1.5.6.RELEASE.jar:1.5.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [spring-boot-1.5.6.RELEASE.jar:1.5.6.RELEASE]
	at com.chinamobile.cmss.Application.main(Application.java:53) [classes/:?]
Caused by: com.google.common.util.concurrent.ExecutionError: java.lang.StackOverflowError
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201) ~[guava-18.0.jar:?]
	at com.google.common.cache.LocalCache.get(LocalCache.java:3937) ~[guava-18.0.jar:?]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941) ~[guava-18.0.jar:?]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824) ~[guava-18.0.jar:?]
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4830) ~[guava-18.0.jar:?]
	at springfox.documentation.spring.web.scanners.CachingOperationReader.read(CachingOperationReader.java:57) ~[springfox-spring-web-2.7.0.jar:2.7.0]
	at springfox.documentation.spring.web.scanners.ApiDescriptionReader.read(ApiDescriptionReader.java:66) ~[springfox-spring-web-2.7.0.jar:2.7.0]
	at springfox.documentation.spring.web.scanners.ApiListingScanner.scan(ApiListingScanner.java:89) ~[springfox-spring-web-2.7.0.jar:2.7.0]
	at springfox.documentation.spring.web.scanners.ApiDocumentationScanner.scan(ApiDocumentationScanner.java:71) ~[springfox-spring-web-2.7.0.jar:2.7.0]
	at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.scanDocumentation(DocumentationPluginsBootstrapper.java:95) ~[springfox-spring-web-2.7.0.jar:2.7.0]
	at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.start(DocumentationPluginsBootstrapper.java:154) ~[springfox-spring-web-2.7.0.jar:2.7.0]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:175) ~[spring-context-4.3.10.RELEASE.jar:4.3.10.RELEASE]
	... 14 more
Caused by: java.lang.StackOverflowError
	at java.util.Currency.getInstance(Currency.java:318) ~[?:1.8.0_121]
	at java.util.Currency.getInstance(Currency.java:399) ~[?:1.8.0_121]
	at java.text.DecimalFormatSymbols.initialize(DecimalFormatSymbols.java:638) ~[?:1.8.0_121]
	at java.text.DecimalFormatSymbols.<init>(DecimalFormatSymbols.java:113) ~[?:1.8.0_121]
	at sun.util.locale.provider.DecimalFormatSymbolsProviderImpl.getInstance(DecimalFormatSymbolsProviderImpl.java:85) ~[?:1.8.0_121]
	at java.text.DecimalFormatSymbols.getInstance(DecimalFormatSymbols.java:180) ~[?:1.8.0_121]
	at java.util.Formatter.getZero(Formatter.java:2283) ~[?:1.8.0_121]
	at java.util.Formatter.<init>(Formatter.java:1892) ~[?:1.8.0_121]
	at java.util.Formatter.<init>(Formatter.java:1914) ~[?:1.8.0_121]
	at java.lang.String.format(String.java:2940) ~[?:1.8.0_121]
	at springfox.documentation.spring.web.readers.parameter.ExpandedParameterBuilder.apply(ExpandedParameterBuilder.java:62) ~[springfox-spring-web-2.7.0.jar:2.7.0]
	at springfox.documentation.spring.web.plugins.DocumentationPluginsManager.expandParameter(DocumentationPluginsManager.java:113) ~[springfox-spring-web-2.7.0.jar:2.7.0]
	at springfox.documentation.spring.web.readers.parameter.ModelAttributeParameterExpander.simpleFields(ModelAttributeParameterExpander.java:155) ~[springfox-spring-web-2.7.0.jar:2.7.0]
	at springfox.documentation.spring.web.readers.parameter.ModelAttributeParameterExpander.expand(ModelAttributeParameterExpander.java:118) ~[springfox-spring-web-2.7.0.jar:2.7.0]
	at springfox.documentation.spring.web.readers.parameter.ModelAttributeParameterExpander.expand(ModelAttributeParameterExpander.java:107) ~[springfox-spring-web-2.7.0.jar:2.7.0]
	at springfox.documentation.spring.web.readers.parameter.ModelAttributeParameterExpander.expand(ModelAttributeParameterExpander.java:107) ~[springfox-spring-web-2.7.0.jar:2.7.0]
	at springfox.documentation.spring.web.readers.parameter.ModelAttributeParameterExpander.expand(ModelAttributeParameterExpander.java:107) ~[springfox-spring-web-2.7.0.jar:2.7.0]
	at springfox.documentation.spring.web.readers.parameter.ModelAttributeParameterExpander.expand(ModelAttributeParameterExpander.java:107) ~[springfox-spring-web-2.7.0.jar:2.7.0]
	at springfox.documentation.spring.web.readers.parameter.ModelAttributeParameterExpander.expand(ModelAttributeParameterExpander.java:107) ~[springfox-spring-web-2.7.0.jar:2.7.0]
	at springfox.documentation.spring.web.readers.parameter.ModelAttributeParameterExpander.expand(ModelAttributeParameterExpander.java:107) ~[springfox-spring-web-2.7.0.jar:2.7.0]
	at springfox.documentation.spring.web.readers.parameter.ModelAttributeParameterExpander.expand(ModelAttributeParameterExpander.java:107) ~[springfox-spring-web-2.7.0.jar:2.7.0]`

**Comment by dilipkrish** [comment]
Please upgrade to 2.8.0

**Comment by Seven4X** [comment]
my bean like this  
class A extends B {
}
class B{
  U u;
} 
class U {
  O o;
}
class O {
 U u ;
}
still error in 2.8.0

**Comment by dilipkrish** [comment]
Are you seeing a log statement or is your app crashing @Seven4X

**Comment by Seven4X** [comment]
logs
`09:00:48.091 ERROR springfox.documentation.spring.web.scanners.ApiDescriptionReader 84 read - Skipping process path[/lq/mixplant/allMixplant], method[index] as it has an error. com.google.common.util.concurrent.ExecutionError:   java.lang.StackOverflowError  
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2216) ~[guava-22.0.jar:?]
	at com.google.common.cache.LocalCache.get(LocalCache.java:4147) ~[guava-22.0.jar:?]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4151) ~[guava-22.0.jar:?]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5140) ~[guava-22.0.jar:?]
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5146) ~[guava-22.0.jar:?]
	at springfox.documentation.spring.web.scanners.CachingOperationReader.read(CachingOperationReader.java:57) ~[springfox-spring-web-2.8.0.jar:2.8.0]
	at springfox.documentation.spring.web.scanners.ApiDescriptionReader.read(ApiDescriptionReader.java:70) [springfox-spring-web-2.8.0.jar:2.8.0]
	at springfox.documentation.spring.web.scanners.ApiListingScanner.scan(ApiListingScanner.java:90) [springfox-spring-web-2.8.0.jar:2.8.0]
	at springfox.documentation.spring.web.scanners.ApiDocumentationScanner.scan(ApiDocumentationScanner.java:71) [springfox-spring-web-2.8.0.jar:2.8.0]
	at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.scanDocumentation(DocumentationPluginsBootstrapper.java:96) [springfox-spring-web-2.8.0.jar:2.8.0]
	at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.start(DocumentationPluginsBootstrapper.java:158) [springfox-spring-web-2.8.0.jar:2.8.0]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:173) [spring-context-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:51) [spring-context-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:346) [spring-context-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:149) [spring-context-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:112) [spring-context-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:874) [spring-context-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.__refresh(AbstractApplicationContext.java:544) [spring-context-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java) [spring-context-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:444) [spring-web-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:326) [spring-web-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107) [spring-web-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4643) [catalina.jar:9.0.0.M26]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5105) [catalina.jar:9.0.0.M26]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [catalina.jar:9.0.0.M26]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:740) [catalina.jar:9.0.0.M26]
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:716) [catalina.jar:9.0.0.M26]
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:703) [catalina.jar:9.0.0.M26]
	at org.apache.catalina.startup.HostConfig.manageApp(HostConfig.java:1729) [catalina.jar:9.0.0.M26]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.__invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:287) [tomcat-coyote.jar:9.0.0.M26]
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819) [?:1.8.0_51]
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801) [?:1.8.0_51]
	at org.apache.catalina.mbeans.MBeanFactory.createStandardContext(MBeanFactory.java:456) [catalina.jar:9.0.0.M26]
	at org.apache.catalina.mbeans.MBeanFactory.createStandardContext(MBeanFactory.java:405) [catalina.jar:9.0.0.M26]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.__invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:287) [tomcat-coyote.jar:9.0.0.M26]
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819) [?:1.8.0_51]
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801) [?:1.8.0_51]
	at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1470) [?:1.8.0_51]
	at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:76) [?:1.8.0_51]
	at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1311) [?:1.8.0_51]
	at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1403) [?:1.8.0_51]
	at javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:832) [?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.__invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:323) [?:1.8.0_51]
	at sun.rmi.transport.Transport$1.run(Transport.java:200) [?:1.8.0_51]
	at sun.rmi.transport.Transport$1.run(Transport.java:197) [?:1.8.0_51]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_51]
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196) [?:1.8.0_51]
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568) [?:1.8.0_51]
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826) [?:1.8.0_51]
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$255(TCPTransport.java:683) [?:1.8.0_51]
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler$$Lambda$10/752092656.run(Unknown Source) [?:1.8.0_51]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_51]
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_51]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.StackOverflowError
	at com.fasterxml.classmate.TypeBindings.equals(TypeBindings.java:197) ~[classmate-1.1.0.jar:?]
	at com.fasterxml.classmate.ResolvedType.equals(ResolvedType.java:278) ~[classmate-1.1.0.jar:?]
	at com.fasterxml.classmate.TypeBindings.equals(TypeBindings.java:197) ~[classmate-1.1.0.jar:?]
	at com.fasterxml.classmate.ResolvedType.equals(ResolvedType.java:278) ~[classmate-1.1.0.jar:?]
	at com.fasterxml.classmate.TypeBindings.equals(TypeBindings.java:197) ~[classmate-1.1.0.jar:?]
	at com.fasterxml.classmate.ResolvedType.equals(ResolvedType.java:278) ~[classmate-1.1.0.jar:?]
	at com.fasterxml.classmate.TypeBindings.equals(TypeBindings.java:197) ~[classmate-1.1.0.jar:?]
	at com.fasterxml.classmate.ResolvedType.equals(ResolvedType.java:278) ~[classmate-1.1.0.jar:?]
	at com.fasterxml.classmate.TypeBindings.equals(TypeBindings.java:197) ~[classmate-1.1.0.jar:?]
	at com.fasterxml.classmate.ResolvedType.equals(ResolvedType.java:278) ~[classmate-1.1.0.jar:?]
	at com.fasterxml.classmate.TypeBindings.equals(TypeBindings.java:197) ~[classmate-1.1.0.jar:?]
	at com.fasterxml.classmate.ResolvedType.equals(ResolvedType.java:278) ~[classmate-1.1.0.jar:?]
	at com.fasterxml.classmate.TypeBindings.equals(TypeBindings.java:197) ~[classmate-1.1.0.jar:?]
	at com.fasterxml.classmate.ResolvedType.equals(ResolvedType.java:278) ~[classmate-1.1.0.jar:?]
	at com.fasterxml.classmate.TypeBindings.equals(TypeBindings.java:197) ~[classmate-1.1.0.jar:?]
	at com.fasterxml.classmate.ResolvedType.equals(ResolvedType.java:278) ~[classmate-1.1.0.jar:?]
	at com.fasterxml.classmate.TypeBindings.equals(TypeBindings.java:197) ~[classmate-1.1.0.jar:?]
	at com.fasterxml.classmate.ResolvedType.equals(ResolvedType.java:278) ~[classmate-1.1.0.jar:?]
	at com.fasterxml.classmate.TypeBindings.equals(TypeBindings.java:197) ~[classmate-1.1.0.jar:?]
	at com.fasterxml.classmate.ResolvedType.equals(ResolvedType.java:278) ~[classmate-1.1.0.jar:?]
	at com.fasterxml.classmate.TypeBindings.equals(TypeBindings.java:197) ~[classmate-1.1.0.jar:?]
	at com.fasterxml.classmate.ResolvedType.equals(ResolvedType.java:278) ~[classmate-1.1.0.jar:?]
	at com.fasterxml.classmate.TypeBindings.equals(TypeBindings.java:197) ~[classmate-1.1.0.jar:?]
	at com.fasterxml.classmate.ResolvedType.equals(ResolvedType.java:278) ~[classmate-1.1.0.jar:?]
	at com.fasterxml.classmate.TypeBindings.equals(TypeBindings.java:197) ~[classmate-1.1.0.jar:?]
	at com.fasterxml.classmate.ResolvedType.equals(ResolvedType.java:278) ~[classmate-1.1.0.jar:?]
	at com.fasterxml.classmate.TypeBindings.equals(TypeBindings.java:197) ~[classmate-1.1.0.jar:?]
	at com.fasterxml.classmate.ResolvedType.equals(ResolvedType.java:278) ~[classmate-1.1.0.jar:?]
	at com.fasterxml.classmate.TypeBindings.equals(TypeBindings.java:197) ~[classmate-1.1.0.jar:?]
	at com.fasterxml.classmate.ResolvedType.equals(ResolvedType.java:278) ~[classmate-1.1.0.jar:?]
	at com.fasterxml.classmate.TypeBindings.equals(TypeBindings.java:197) ~[classmate-1.1.0.jar:?]
	at com.fasterxml.classmate.ResolvedType.equals(ResolvedType.java:278) ~[classmate-1.1.0.jar:?]
	at com.fasterxml.classmate.TypeBindings.equals(TypeBindings.java:197) ~[classmate-1.1.0.jar:?]
	at com.fasterxml.classmate.ResolvedType.equals(ResolvedType.java:278) ~[classmate-1.1.0.jar:?]
	at com.fasterxml.classmate.TypeBindings.equals(TypeBindings.java:197) ~[classmate-1.1.0.jar:?]`

**Comment by jiangshanwe** [comment]
2.8.0 help me
