### ISSUE TITLE
@ApiModelProperty throwing NumberFormatException if example value is not set 

### ISSUE THREAD

**Issue by nikunjundhad** [springfox/springfox#2265]
Hi,

When we don't set example value in @ApiModelProperty for Wrapper class, its try to set empty string ("") as an example and during parsing its throw NumberFormatException, can't we have something which set default value for those wrapper class like for Integer it set 0 in JSON example.
We are facing this issue for IntegerProperty, DecimalProperty, BaseIntegerProperty.
Below i attached Exception log, 

NumberFormatException: For input string: ""
      	at java.lang.Integer.parseInt(String)
      	at io.swagger.models.properties.IntegerProperty.setExample(Object)
      	at io.swagger.models.properties.AbstractProperty.setExample(String)
      	at springfox.documentation.swagger2.mappers.ModelMapper.mapProperty(ModelProperty)
      	at springfox.documentation.swagger2.mappers.ModelMapper.mapProperties(SortedMap)
      	at springfox.documentation.swagger2.mappers.ModelMapper.mapProperties(Model)
      	at springfox.documentation.swagger2.mappers.ModelMapper.mapModels(Map)
      	at springfox.documentation.swagger2.mappers.ModelMapper.modelsFromApiListings(Multimap)
      	at springfox.documentation.swagger2.mappers.ServiceModelToSwagger2MapperImpl.mapDocumentation(Documentation)
      	at springfox.documentation.swagger2.web.Swagger2Controller.getDocumentation(String, HttpServletRequest)
      	at sun.reflect.NativeMethodAccessorImpl.invoke0(Method, Object, Object[])
      	at sun.reflect.NativeMethodAccessorImpl.invoke(Object, Object[])
      	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Object, Object[])
      	at java.lang.reflect.Method.invoke(Object, Object[])
      	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(Object[])
      	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(NativeWebRequest, ModelAndViewContainer, Object[])
      	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletWebRequest, ModelAndViewContainer, Object[])
      	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(HttpServletRequest, HttpServletResponse, HandlerMethod)
      	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(HttpServletRequest, HttpServletResponse, HandlerMethod)
      	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(HttpServletRequest, HttpServletResponse, Object)
      	at org.springframework.web.servlet.DispatcherServlet.doDispatch(HttpServletRequest, HttpServletResponse)
      	at org.springframework.web.servlet.DispatcherServlet.doService(HttpServletRequest, HttpServletResponse)
      	at org.springframework.web.servlet.FrameworkServlet.processRequest(HttpServletRequest, HttpServletResponse)
      	at org.springframework.web.servlet.FrameworkServlet.doGet(HttpServletRequest, HttpServletResponse)
      	at javax.servlet.http.HttpServlet.service(HttpServletRequest, HttpServletResponse)
      	at org.springframework.web.servlet.FrameworkServlet.service(HttpServletRequest, HttpServletResponse)
      	at javax.servlet.http.HttpServlet.service(ServletRequest, ServletResponse)
      	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ServletRequest, ServletResponse)
      	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ServletRequest, ServletResponse)
      	at org.apache.tomcat.websocket.server.WsFilter.doFilter(ServletRequest, ServletResponse, FilterChain)
      	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ServletRequest, ServletResponse)
      	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ServletRequest, ServletResponse)
      	at com.accelevents.security.AuthenticationTokenProcessingFilter.doFilter(ServletRequest, ServletResponse, FilterChain)
      	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ServletRequest, ServletResponse)
      	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ServletRequest, ServletResponse)
      	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(ServletRequest, ServletResponse)
      	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterInvocation)
      	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(ServletRequest, ServletResponse, FilterChain)
      	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(ServletRequest, ServletResponse)
      	at com.accelevents.security.AuthenticationTokenProcessingFilter.doFilter(ServletRequest, ServletResponse, FilterChain)
      	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(ServletRequest, ServletResponse)
      	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ServletRequest, ServletResponse, FilterChain)
      	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(ServletRequest, ServletResponse)
      	at org.springframework.security.web.session.SessionManagementFilter.doFilter(ServletRequest, ServletResponse, FilterChain)
      	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(ServletRequest, ServletResponse)
      	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(ServletRequest, ServletResponse, FilterChain)
      	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(ServletRequest, ServletResponse)
      	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(ServletRequest, ServletResponse, FilterChain)
      	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(ServletRequest, ServletResponse)
      	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(ServletRequest, ServletResponse, FilterChain)
      	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(ServletRequest, ServletResponse)
      	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(ServletRequest, ServletResponse, FilterChain)
      	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(ServletRequest, ServletResponse)
      	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(ServletRequest, ServletResponse, FilterChain)
      	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(ServletRequest, ServletResponse)
      	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HttpServletRequest, HttpServletResponse, FilterChain)
      	at org.springframework.web.filter.OncePerRequestFilter.doFilter(ServletRequest, ServletResponse, FilterChain)
      	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(ServletRequest, ServletResponse)
      	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(ServletRequest, ServletResponse, FilterChain)
      	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(ServletRequest, ServletResponse)
      	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(HttpServletRequest, HttpServletResponse, FilterChain)
      	at org.springframework.web.filter.OncePerRequestFilter.doFilter(ServletRequest, ServletResponse, FilterChain)
      	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(ServletRequest, ServletResponse)
      	at org.springframework.security.web.FilterChainProxy.doFilterInternal(ServletRequest, ServletResponse, FilterChain)
      	at org.springframework.security.web.FilterChainProxy.doFilter(ServletRequest, ServletResponse, FilterChain)
      	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(Filter, ServletRequest, ServletResponse, FilterChain)
      	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(ServletRequest, ServletResponse, FilterChain)
      	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ServletRequest, ServletResponse)
      	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ServletRequest, ServletResponse)
      	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(HttpServletRequest, HttpServletResponse, FilterChain)
      	at org.springframework.web.filter.OncePerRequestFilter.doFilter(ServletRequest, ServletResponse, FilterChain)
      	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ServletRequest, ServletResponse)
      	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ServletRequest, ServletResponse)
      	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpServletRequest, HttpServletResponse, FilterChain)
      	at org.springframework.web.filter.OncePerRequestFilter.doFilter(ServletRequest, ServletResponse, FilterChain)
      	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ServletRequest, ServletResponse)
      	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ServletRequest, ServletResponse)
      	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HttpServletRequest, HttpServletResponse, FilterChain)
      	at org.springframework.web.filter.OncePerRequestFilter.doFilter(ServletRequest, ServletResponse, FilterChain)
      	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ServletRequest, ServletResponse)
      	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ServletRequest, ServletResponse)
      	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(HttpServletRequest, HttpServletResponse, FilterChain)
      	at org.springframework.web.filter.OncePerRequestFilter.doFilter(ServletRequest, ServletResponse, FilterChain)
      	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ServletRequest, ServletResponse)
      	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ServletRequest, ServletResponse)
      	at org.springframework.boot.web.support.ErrorPageFilter.doFilter(HttpServletRequest, HttpServletResponse, FilterChain)
      	at org.springframework.boot.web.support.ErrorPageFilter.access$000(ErrorPageFilter, HttpServletRequest, HttpServletResponse, FilterChain)
      	at org.springframework.boot.web.support.ErrorPageFilter$1.doFilterInternal(HttpServletRequest, HttpServletResponse, FilterChain)
      	at org.springframework.web.filter.OncePerRequestFilter.doFilter(ServletRequest, ServletResponse, FilterChain)
      	at org.springframework.boot.web.support.ErrorPageFilter.doFilter(ServletRequest, ServletResponse, FilterChain)
      	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ServletRequest, ServletResponse)
      	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ServletRequest, ServletResponse)
      	at org.apache.catalina.core.StandardWrapperValve.invoke(Request, Response)
      	at org.apache.catalina.core.StandardContextValve.invoke(Request, Response)
      	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(Request, Response)
      	at org.apache.catalina.core.StandardHostValve.invoke(Request, Response)
      	at org.apache.catalina.valves.ErrorReportValve.invoke(Request, Response)
      	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(Request, Response)
      	at org.apache.catalina.core.StandardEngineValve.invoke(Request, Response)
      	at org.apache.catalina.connector.CoyoteAdapter.service(Request, Response)
      	at org.apache.coyote.http11.AbstractHttp11Processor.process(SocketWrapper)
      	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(SocketWrapper, SocketStatus)
      	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun()
      	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run()
      	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor$Worker)
      	at java.util.concurrent.ThreadPoolExecutor$Worker.run()
      	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run()
      	at java.lang.Thread.run()

**Comment by nikunjundhad** [comment]
@dilipkrish for this annotation @APIModelProperty we are receiving another exception ClassNotFound.
Here i am attaching exception log please check that as well.
ClassNotFoundException
      	at java.lang.Class.forName(String)
      	at springfox.documentation.swagger.schema.ApiModelProperties$7.apply(ApiModelProperty)
      	at springfox.documentation.swagger.schema.ApiModelProperties$7.apply(Object)
      	at com.google.common.base.Present.transform(Function)
      	at springfox.documentation.swagger.schema.ApiModelPropertyPropertyBuilder.apply(ModelPropertyContext)
      	at springfox.documentation.schema.plugins.SchemaPluginsManager.property(ModelPropertyContext)
      	at springfox.documentation.schema.property.OptimizedModelPropertiesProvider.beanModelProperty(ResolvedMethod, BeanPropertyDefinition, ModelContext)
      	at springfox.documentation.schema.property.OptimizedModelPropertiesProvider.access$100(OptimizedModelPropertiesProvider, ResolvedMethod, BeanPropertyDefinition, ModelContext)
      	at springfox.documentation.schema.property.OptimizedModelPropertiesProvider$2.apply(ResolvedMethod)
      	at springfox.documentation.schema.property.OptimizedModelPropertiesProvider$2.apply(Object)
      	at com.google.common.base.Present.transform(Function)
      	at springfox.documentation.schema.property.OptimizedModelPropertiesProvider.candidateProperties(ResolvedType, AnnotatedMember, BeanPropertyDefinition, ModelContext)
      	at springfox.documentation.schema.property.OptimizedModelPropertiesProvider.propertiesFor(ResolvedType, ModelContext)
      	at springfox.documentation.schema.property.CachingModelPropertiesProvider$1.load(ModelContext)
      	at springfox.documentation.schema.property.CachingModelPropertiesProvider$1.load(Object)
      	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(Object, CacheLoader)
      	at com.google.common.cache.LocalCache$Segment.loadSync(Object, int, LocalCache$LoadingValueReference, CacheLoader)
      	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(Object, int, CacheLoader)
      	at com.google.common.cache.LocalCache$Segment.get(Object, int, CacheLoader)
      	at com.google.common.cache.LocalCache.get(Object, CacheLoader)
      	at com.google.common.cache.LocalCache.getOrLoad(Object)
      	at com.google.common.cache.LocalCache$LocalLoadingCache.get(Object)
      	at springfox.documentation.schema.property.CachingModelPropertiesProvider.propertiesFor(ResolvedType, ModelContext)
      	at springfox.documentation.schema.DefaultModelDependencyProvider.propertiesFor(ModelContext, ResolvedType)
      	at springfox.documentation.schema.DefaultModelDependencyProvider.nonTrivialProperties(ModelContext, ResolvedType)
      	at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedPropertiesAndFields(ModelContext, ResolvedType)
      	at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedDependencies(ModelContext)
      	at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedTypeParameters(ModelContext, ResolvedType)
      	at springfox.documentation.schema.DefaultModelDependencyProvider.resolvedDependencies(ModelContext)
      	at springfox.documentation.schema.DefaultModelDependencyProvider.dependentModels(ModelContext)
      	at springfox.documentation.schema.CachingModelDependencyProvider$1.load(ModelContext)
      	at springfox.documentation.schema.CachingModelDependencyProvider$1.load(Object)
      	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(Object, CacheLoader)
      	at com.google.common.cache.LocalCache$Segment.loadSync(Object, int, LocalCache$LoadingValueReference, CacheLoader)
      	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(Object, int, CacheLoader)
      	at com.google.common.cache.LocalCache$Segment.get(Object, int, CacheLoader)
      	at com.google.common.cache.LocalCache.get(Object, CacheLoader)
      	at com.google.common.cache.LocalCache.getOrLoad(Object)
      	at com.google.common.cache.LocalCache$LocalLoadingCache.get(Object)
      	at springfox.documentation.schema.CachingModelDependencyProvider.dependentModels(ModelContext)
      	at springfox.documentation.schema.DefaultModelProvider.dependencies(ModelContext)
      	at springfox.documentation.schema.CachingModelProvider.dependencies(ModelContext)
      	at springfox.documentation.spring.web.scanners.ApiModelReader.populateDependencies(ModelContext, Map)
      	at springfox.documentation.spring.web.scanners.ApiModelReader.read(RequestMappingContext)
      	at springfox.documentation.spring.web.scanners.ApiListingScanner.scan(ApiListingScanningContext)
      	at springfox.documentation.spring.web.scanners.ApiDocumentationScanner.scan(DocumentationContext)
      	at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.scanDocumentation(DocumentationContext)
      	at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.start()
      	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(Map, String, boolean)
      	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor, Map, String, boolean)
      	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start()
      	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(boolean)
      	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh()
      	at org.springframework.context.support.AbstractApplicationContext.finishRefresh()
      	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh()
      	at org.springframework.context.support.AbstractApplicationContext.refresh()
      	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh()
      	at org.springframework.boot.SpringApplication.refresh(ApplicationContext)
      	at org.springframework.boot.SpringApplication.refreshContext(ConfigurableApplicationContext)
      	at org.springframework.boot.SpringApplication.run(String[])
      	at org.springframework.boot.web.support.SpringBootServletInitializer.run(SpringApplication)
      	at org.springframework.boot.web.support.SpringBootServletInitializer.createRootApplicationContext(ServletContext)
      	at org.springframework.boot.web.support.SpringBootServletInitializer.onStartup(ServletContext)
      	at org.springframework.web.SpringServletContainerInitializer.onStartup(Set, ServletContext)
      	at org.apache.catalina.core.StandardContext.startInternal()
      	at org.apache.catalina.util.LifecycleBase.start()
      	at org.apache.catalina.core.ContainerBase.addChildInternal(Container)
      	at org.apache.catalina.core.ContainerBase.addChild(Container)
      	at org.apache.catalina.core.StandardHost.addChild(Container)
      	at org.apache.catalina.startup.HostConfig.deployWAR(ContextName, File)
      	at org.apache.catalina.startup.HostConfig$DeployWar.run()
      	at java.util.concurrent.Executors$RunnableAdapter.call()
      	at java.util.concurrent.FutureTask.run()
      	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor$Worker)
      	at java.util.concurrent.ThreadPoolExecutor$Worker.run()
      	at java.lang.Thread.run()

**Comment by dilipkrish** [comment]
@nikunjundhad That seems like you've got an `ApiModelProperty#dataType` that is not a fully qualified class name

**Comment by dilipkrish** [comment]
@nikunjundhad what version of springfox are u using?

**Comment by nikunjundhad** [comment]
@dilipkrish i am using latest version 2.8.0

**Comment by dilipkrish** [comment]
Would be great if you could try 2.8.1-SNAPSHOT and confirm if its fixed.

**Comment by kyleki** [comment]
I'm experiencing the exact same thing as the OP with the NumberFormatException in 2.8.1-SNAPSHOT.  Is there a fix in the works for this or should I just ignore the warning via my log config?

**Comment by dilipkrish** [comment]
Possibly a slightly different stack trace? Or perhaps a breaking test would be useful. I have a feeling It should be fixed @kyleki

**Comment by dilipkrish** [comment]
@kyleki Oh I assumed it was an exception that was thrown... I didnt realize you meant a warning log message with stack trace. Is the issue that we want to not show the stack trace?

**Comment by dilipkrish** [comment]
@kyleki I dug into that some, unfortunately thats not in the library we control. Its probably better that the [swagger-core library](https://github.com/swagger-api/swagger-core) handles it appropriately, or we have to use your solution. I'd rather not have a bunch of code in this library that conditionally sets the example.

**Comment by HADB** [comment]
I encountered this problem after I upgraded springfox from 2.8.0 to 2.9.2.

**Comment by ajcRodrigues** [comment]
Hi everybody,

I solved this issue removing old dependencies and add new one.

In pom.xml

```xml
	<dependency>
		<groupId>io.springfox</groupId>
		<artifactId>springfox-swagger2</artifactId>
		<version>2.9.2</version>
		<exclusions>
			<exclusion>
				<groupId>io.swagger</groupId>
				<artifactId>swagger-annotations</artifactId>
			</exclusion>
			<exclusion>
				<groupId>io.swagger</groupId>
				<artifactId>swagger-models</artifactId>
			</exclusion>
		</exclusions>
	</dependency>
	<dependency>
		<groupId>io.springfox</groupId>
		<artifactId>springfox-swagger-ui</artifactId>
		<version>2.9.2</version>
	</dependency>
	<dependency>
		<groupId>io.swagger</groupId>
		<artifactId>swagger-annotations</artifactId>
		<version>1.5.21</version>
	</dependency>
	<dependency>
		<groupId>io.swagger</groupId>
		<artifactId>swagger-models</artifactId>
		<version>1.5.21</version>
	</dependency>
```

**Comment by dilipkrish** [comment]
@ajcRodrigues Thanks!

**Comment by jaychang9** [comment]
@ajcRodrigues It works! Greate job!

**Comment by binakot** [comment]
@ajcRodrigues Thanks! It works like a charm 🍸 

For Gradle's users:

```groovy
compile("io.springfox:springfox-swagger2:2.9.2") {
    exclude module: 'swagger-annotations'
    exclude module: 'swagger-models'
}
compile("io.swagger:swagger-annotations:1.5.21")
compile("io.swagger:swagger-models:1.5.21")
```

**Comment by dustinbrown** [comment]
@ajcRodrigues Thank you very much, works great.

**Comment by sf-jyk** [comment]
Thank you 👍 It was nice solution to me.

**Comment by chrisinmtown** [comment]
If I understood this correctly, springfox version 2.9.2 references swagger-models and swagger-annotations libraries at version 1.5.20; to squelch this annoying warning springfox POM needs to use versions 1.15.21 instead.  Did I get that right? Is this change scheduled for a future version of springfox?

**Comment by sev7e0** [comment]
@ajcRodrigues Thanks!!! 👍

**Comment by hokkun-dayo** [comment]
JFYI, this issue was resolved at https://github.com/swagger-api/swagger-core/pull/2865

**Comment by Abhirajs89** [comment]
@ajcRodrigues Thanks!

**Comment by myhgc** [comment]
@ajcRodrigues   Thanks! 2.9.2 the version still 1.5.20

**Comment by amitgupta143** [comment]
Hi All,
I have the following configuration in my build.gradle file : 

        compile("io.springfox:springfox-swagger2:2.9.2") {
		exclude module: 'swagger-annotations'
		exclude module: 'swagger-models'
	}
	compile group: 'io.springfox', name: 'springfox-swagger-ui', version: '2.9.2'
	compile group: 'io.swagger', name: 'swagger-annotations', version: '1.5.21'
	compile group: 'io.swagger', name: 'swagger-models', version: '1.5.21'

   http://localhost:9090/v2/api-docs : This link is working fine but while accessing 
   http://localhost:9090/swagger-ui.html/  , i am getting the below error trace on the page.
{
status: 404,
error: "Not Found",
message: "/WEB-INF/Views/Shared/Error/ServerError.jsp",
timeStamp: "Sun Sep 08 15:49:25 IST 2019",
trace: "java.lang.NumberFormatException: null at java.lang.Integer.parseInt(Integer.java:542) at java.lang.Integer.parseInt(Integer.java:615) at com.sdl.webapp.common.util.LocalizationUtils.findPageByPath(LocalizationUtils.java:158) at com.hp.kaas.repository.content.providers.IshContentProvider.getPageModel(IshContentProvider.java:103) at com.sdl.webapp.common.controller.PageController.getPageModel(PageController.java:296) at com.sdl.webapp.common.controller.PageController.handleGetPage(PageController.java:120) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133) at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97) at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827) at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738) at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967) at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901) at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861) at javax.servlet.http.HttpServlet.service(HttpServlet.java:635) at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846) at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) at com.tridion.ambientdata.web.AbstractAmbientDataServletFilter.doFilter(AbstractAmbientDataServletFilter.java:291) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197) at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199) at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478) at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803) at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459) at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) at java.lang.Thread.run(Thread.java:748) "
}

**Comment by yanaair** [comment]
@ajcRodrigues hello! Will there be a newer version of springfox that will include 1.5.21 version of swagger-annotations and swagger-models?

**Comment by porfirioribeiro** [comment]
This problem still exists in springfox 3.0.0
