### ISSUE TITLE
StackoverflowException

### ISSUE THREAD

**Issue by miwoe** [springfox/springfox#2339]
Related to:[https://github.com/springfox/springfox/issues/1513]( https://github.com/springfox/springfox/issues/1513) 

Still getting StackOverflowException

```
Caused by: java.lang.StackOverflowError: null
.......
	at springfox.documentation.spring.web.readers.parameter.ExpandedParameterBuilder.apply(ExpandedParameterBuilder.java:62)
	at springfox.documentation.spring.web.plugins.DocumentationPluginsManager.expandParameter(DocumentationPluginsManager.java:113)
	at springfox.documentation.spring.web.readers.parameter.ModelAttributeParameterExpander.simpleFields(ModelAttributeParameterExpander.java:155)
	at springfox.documentation.spring.web.readers.parameter.ModelAttributeParameterExpander.expand(ModelAttributeParameterExpander.java:118)
	at springfox.documentation.spring.web.readers.parameter.ModelAttributeParameterExpander.expand(ModelAttributeParameterExpander.java:107)
	at springfox.documentation.spring.web.readers.parameter.ModelAttributeParameterExpander.expand(ModelAttributeParameterExpander.java:107)
	at springfox.documentation.spring.web.readers.parameter.ModelAttributeParameterExpander.expand(ModelAttributeParameterExpander.java:107)
```

```
            <dependency>
                <groupId>io.springfox</groupId>
                <artifactId>springfox-swagger2</artifactId>
                <version>2.7.0</version>
            </dependency>
            <dependency>
                <groupId>io.springfox</groupId>
                <artifactId>springfox-swagger-ui</artifactId>
                <version>2.7.0</version>
            </dependency>
```

```
    @ApiOperation("Reactivate Odoo campaign project")
    @RequestMapping(value = "/campaigns/{id}/erp/reactivate", method = RequestMethod.POST)
    public List<Map> reactivateCampaign(@PathVariable("id") Campaign campaign) {
        return odooCampaignService.reactivateCampaign(campaign);
    }
```

Campaign has a reference to a Job and Job has "parent"-Job cyclic reference.

According to the mentioned ticket it is a bug.

**Comment by dilipkrish** [comment]
Please upgrade to 2.8.0

**Comment by miwoe** [comment]
Ok. In 2.8.0 it works.
