### ISSUE TITLE
Void type in @ModelAttribute annotated classes.

### ISSUE THREAD

**Issue by MaksimOrlov** [springfox/springfox#2368]
The example is:

```

    @RequestMapping(value = "/getpayees", method = RequestMethod.GET)
    public GenericResponse<List<Payee>> getPayees(@ModelAttribute @Valid GenericRequest<Void> request) {
        return new GenericResponse<List<Payee>>("ok", service.getPayeeList(request.getLang()));
    }
```

And request wrapper:

```
public class GenericRequest<T> {

    @NotNull
    private T parameters;

    public T getParameters() {
        return parameters;
    }

    public void setParameters(T parameters) {
        this.parameters = parameters;
    }

}
```

will lead to NullPointerException

StackTrace is:

```
java.lang.NullPointerException
	at springfox.documentation.swagger2.mappers.SerializableParameterFactories.create(SerializableParameterFactories.java:96)
	at springfox.documentation.swagger2.mappers.ParameterMapper.mapParameter(ParameterMapper.java:42)
	at springfox.documentation.swagger2.mappers.ServiceModelToSwagger2MapperImpl.parameterListToParameterList(ServiceModelToSwagger2MapperImpl.java:223)
	at springfox.documentation.swagger2.mappers.ServiceModelToSwagger2MapperImpl.mapOperation(ServiceModelToSwagger2MapperImpl.java:153)
	at springfox.documentation.swagger2.mappers.ServiceModelToSwagger2Mapper.mapOperations(ServiceModelToSwagger2Mapper.java:173)
	at springfox.documentation.swagger2.mappers.ServiceModelToSwagger2Mapper.mapApiListings(ServiceModelToSwagger2Mapper.java:155)
	at springfox.documentation.swagger2.mappers.ServiceModelToSwagger2MapperImpl.mapDocumentation(ServiceModelToSwagger2MapperImpl.java:56)
	at springfox.documentation.swagger2.web.Swagger2Controller.getDocumentation(Swagger2Controller.java:92)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)

```

The main reason is in `SerializableParameterFactories` class. For Void types we will calculate ***NULL*** instead of property and then will try to return type from it.

**Comment by dilipkrish** [comment]
Is this a real world scenario. I have never seen a void bean property on an input parameter :)

**Comment by MaksimOrlov** [comment]
That is the full code example:
```
public class GenericRequest<T> {

    //common parameter
    private String lang;

    //common parameter
    private String answerType;

    //special parameters
    @NotNull(groups = {default.class})
    private T parameters;

    public T getParameters() {
        return parameters;
    }

    public void setParameters(T parameters) {
        this.parameters = parameters;
    }

}
```

One of mappings doesn't have any special parameters, just common (`lang`, `answerType`)

```
    public GenericResponse<List<Payee>> getPayees(@ModelAttribute @Valid GenericRequest<Void> request)
```

So, the type of property `T` is set to `Void`

**Comment by MaksimOrlov** [comment]
Thanks a lot for fixing that!

**Comment by dilipkrish** [comment]
You have a much bigger fix waiting in line 😉
