### ISSUE TITLE
swagger-ui - API Rest call to download zip file, downloads corrupted zip file 

### ISSUE THREAD

**Issue by prem-jason** [springfox/springfox#2371]
Hi,

Rest call has now problem downloading zip file in browser URL.

With swagger-ui, downloading zip file with extra underscore appended to filename in prefix and suffix (of extension) _XXXApplication-1524222675972.zip_ and its corrupt. Can you please address this issue?

Response header as following:
{
"pragma": "no-cache",
"date": "Fri, 20 Apr 2018 11:11:21 GMT",
"access-control-allow-headers": "Content-Type, attachment",
"content-type": "application/octet-stream",
"access-control-allow-origin": "*",
"cache-control": "no-cache, no-store, must-revalidate",
"content-disposition": "attachment; filename="XXXApplication-1524222675972.zip"",
"attachment": "XXXApplication-1524222675972.zip",
"content-length": "6415",
"expires": "Thu, 01 Jan 1970 00:00:00 GMT"
}

swagger dependencies:
<dependency>
<groupId>io.springfox</groupId>
<artifactId>springfox-swagger2</artifactId>
<version>2.8.0</version>
</dependency>
<dependency>
<groupId>io.springfox</groupId>
<artifactId>springfox-swagger-ui</artifactId>
<version>2.8.0</version>
</dependency>

Please let me know if requires more details.

Thanks

**Comment by prem-jason** [comment]
Adding more details as following:

ours is springboot application, sometimes at startup also gets the error as::
2018-04-20 13:34:33 AM-LOG: level=INFO  thread='main' class=XYZApplication line=57 - Started XYZApplication in 16.426 seconds (JVM running for 17.955)
2018-04-20 13:34:43 AM-LOG: level=WARN  thread='qtp1402433372-16' class=ServletHandler line=632 - /application-manager/swagger-ui.html
java.util.zip.ZipException: invalid code lengths set
        at java.util.zip.InflaterInputStream.read(Unknown Source)
        at org.springframework.boot.loader.jar.ZipInflaterInputStream.read(ZipInflaterInputStream.java:52)
        at java.io.FilterInputStream.read(Unknown Source)
        at org.springframework.util.StreamUtils.copy(StreamUtils.java:127)
        at org.springframework.http.converter.ResourceHttpMessageConverter.writeContent(ResourceHttpMessageConverter.java:115)
        at org.springframework.http.converter.ResourceHttpMessageConverter.writeInternal(ResourceHttpMessageConverter.java:107)
        at org.springframework.http.converter.ResourceHttpMessageConverter.writeInternal(ResourceHttpMessageConverter.java:50)
        at org.springframework.http.converter.AbstractHttpMessageConverter.write(AbstractHttpMessageConverter.java:227)
        at org.springframework.web.servlet.resource.ResourceHttpRequestHandler.handleRequest(ResourceHttpRequestHandler.java:376)
        at org.springframework.web.servlet.mvc.HttpRequestHandlerAdapter.handle(HttpRequestHandlerAdapter.java:51)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)

on browser url: localhost:6868/AM/swagger-ui.html
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Fri Apr 20 13:34:43 BST 2018
There was an unexpected error (type=Internal Server Error, status=500).
java.util.zip.ZipException: invalid code lengths set

**Comment by dilipkrish** [comment]
This has nothing to do with this project. Unfortunately neither the stack trace has any elements of this library, nor does swagger-ui code belong to this library
