### ISSUE TITLE
Spring Boot 1.5.12 application doesn't start with 2.9.0

### ISSUE THREAD

**Issue by d-baer** [springfox/springfox#2388]
It fails to load the Application Context. Maybe there is a missing dependency in springfox?

`
java.lang.IllegalStateException: Failed to load ApplicationContext

	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:124)
	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:83)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:117)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:83)
	at org.springframework.boot.test.autoconfigure.SpringBootDependencyInjectionTestExecutionListener.prepareTestInstance(SpringBootDependencyInjectionTestExecutionListener.java:44)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:230)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTest(SpringJUnit4ClassRunner.java:228)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner$1.runReflectiveCall(SpringJUnit4ClassRunner.java:287)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.methodBlock(SpringJUnit4ClassRunner.java:289)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:247)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: org.springframework.context.ApplicationContextException: Failed to start bean 'documentationPluginsBootstrapper'; nested exception is com.google.common.util.concurrent.ExecutionError: java.lang.NoSuchMethodError: com.google.common.collect.FluentIterable.concat(Ljava/lang/Iterable;Ljava/lang/Iterable;)Lcom/google/common/collect/FluentIterable;
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:176)
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:50)
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:346)
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:149)
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:112)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:880)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:144)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:120)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:98)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:116)
	... 25 more
Caused by: com.google.common.util.concurrent.ExecutionError: java.lang.NoSuchMethodError: com.google.common.collect.FluentIterable.concat(Ljava/lang/Iterable;Ljava/lang/Iterable;)Lcom/google/common/collect/FluentIterable;
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
	at springfox.documentation.schema.CachingModelDependencyProvider.dependentModels(CachingModelDependencyProvider.java:58)
	at springfox.documentation.schema.DefaultModelProvider.dependencies(DefaultModelProvider.java:128)
	at springfox.documentation.schema.CachingModelProvider.dependencies(CachingModelProvider.java:68)
	at springfox.documentation.spring.web.scanners.ApiModelReader.populateDependencies(ApiModelReader.java:136)
	at springfox.documentation.spring.web.scanners.ApiModelReader.read(ApiModelReader.java:78)
	at springfox.documentation.spring.web.scanners.ApiListingScanner.scan(ApiListingScanner.java:133)
	at springfox.documentation.spring.web.scanners.ApiDocumentationScanner.scan(ApiDocumentationScanner.java:71)
	at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.scanDocumentation(DocumentationPluginsBootstrapper.java:101)
	at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.start(DocumentationPluginsBootstrapper.java:167)
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:173)
	... 39 more
Caused by: java.lang.NoSuchMethodError: com.google.common.collect.FluentIterable.concat(Ljava/lang/Iterable;Ljava/lang/Iterable;)Lcom/google/common/collect/FluentIterable;
	at springfox.documentation.schema.DefaultModelDependencyProvider.dependentModels(DefaultModelDependencyProvider.java:79)
	at springfox.documentation.schema.CachingModelDependencyProvider$1.load(CachingModelDependencyProvider.java:50)
	at springfox.documentation.schema.CachingModelDependencyProvider$1.load(CachingModelDependencyProvider.java:48)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
	... 52 more
`

**Comment by dilipkrish** [comment]
Sounds like a mismatch in guava versions? Are you using guava 20?

**Comment by d-baer** [comment]
No. a mvn dependency:tree shows that only guava 18.0 is on the classpath and this is only referenced from springfox 2.9.0

```
[INFO] |  +- io.springfox:springfox-spi:jar:2.9.0:compile
[INFO] |  |  \- io.springfox:springfox-core:jar:2.9.0:compile
[INFO] |  |     \- net.bytebuddy:byte-buddy:jar:1.8.8:compile
[INFO] |  +- io.springfox:springfox-schema:jar:2.9.0:compile
[INFO] |  +- io.springfox:springfox-swagger-common:jar:2.9.0:compile
[INFO] |  +- io.springfox:springfox-spring-web:jar:2.9.0:compile
[INFO] |  +- com.google.guava:guava:jar:18.0:compile
[INFO] |  +- com.fasterxml:classmate:jar:1.3.4:compile
[INFO] |  +- org.springframework.plugin:spring-plugin-core:jar:1.2.0.RELEASE:compile
[INFO] |  +- org.springframework.plugin:spring-plugin-metadata:jar:1.2.0.RELEASE:compile
[INFO] |  \- org.mapstruct:mapstruct:jar:1.2.0.Final:compile
[INFO] +- io.springfox:springfox-swagger-ui:jar:2.9.0:compile
```

**Comment by dilipkrish** [comment]
Sounds like a an issue with your dependency management in maven, [this is the dependency](https://jcenter.bintray.com/io/springfox/springfox-swagger2/2.9.0/:springfox-swagger2-2.9.0.pom) that is advertised

**Comment by d-baer** [comment]
Maybe, but why does a simple switch back to 2.8.0 solve the problem? Maybe it is an issue with one of the other dependencies that have been upgraded with 2.9.0?

**Comment by dilipkrish** [comment]
Based on your stack trace its the guava dependency and maven is resolving to a different version.

**Comment by a1dutch** [comment]
Fixing the version to 20 in dependency management fixes the issue

```
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.google.guava</groupId>
                <artifactId>guava</artifactId>
                <version>20.0</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
```

**Comment by joelroyer** [comment]
The problem still persist in release 2.9.2 (with Sprinb Boot 1.5.13.RELEASE).

**Comment by dilipkrish** [comment]
@joelroyer you need to ensure you have the right version of guava in your class path.

**Comment by d-baer** [comment]
I saw that spring-cloud-dependencies, Edgware.SR3 has that older Guava version. This causes the error in my case. Was not able to upgrade from 2.8.0 until now.

**Comment by d-baer** [comment]
Great news!

**Comment by alonWang** [comment]
have this problem too,wait for new version

**Comment by fraggle222** [comment]
Same issue here with Spring Boot 1.5.2 Release and springfox-swagger 2.9.2 and springfox-ui 2.9.2, Guava version shows as 20.0 (compile).

**Comment by d-baer** [comment]
Some more details on this issue:

**For Spring Boot 1.5.x**
- spring-cloud-dependencies:Edgware.SR3 has a dependency on com.google.guava:guava:jar:18.0:compile
- spring-cloud-dependencies:Edgware.SR4 has a dependency on com.google.guava:guava:jar:20.0:compile
So an update to SR4 should fix the issue

**For Spring Boot 2.0.x**
If you are on Spring Boot 2 you should probably use spring-cloud-dependencies:Finchley.SR1. this resolves to com.google.guava:guava:jar:20.0:compile in `mvn dependency:tree`

**Comment by binakot** [comment]
@d-baer The same error on Spring Boot 1.5.16.RELEASE and Spring Cloud Edgware.RELEASE.
@fraggle222 Downgrade to 2.8.0 works 👍

**Comment by d-baer** [comment]
> 
> 
> @d-baer The same error on Spring Boot 1.5.16.RELEASE and Spring Cloud Edgware.RELEASE.
> @fraggle222 Downgrade to 2.8.0 works 👍

Yes, all spring-cloud-dependencies below Edgware.SR4 (including Edgware.RELEASE) have that dependency to com.google.guava:guava:jar:18.0. Updating to Edgware.SR4 should work.

**Comment by binakot** [comment]
@d-baer Yeah, sorry. I was confusing about release table on maven central, RELEASE is first then SR*. Tomorrow I will try update to SR4 and write here.

**Comment by binakot** [comment]
This works like a charm:

```groovy
dependencyManagement {
    imports {
        mavenBom("org.springframework.boot:spring-boot-dependencies:${springBootVersion}")
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
    }
}

// ...

compile("io.springfox:springfox-swagger2:${property('springFoxSwaggerVersion')}") {
    exclude module: 'swagger-annotations'
    exclude module: 'swagger-models'
 }
compile("io.swagger:swagger-annotations:${property('ioSwaggerVersion')}")
compile("io.swagger:swagger-models:${property('ioSwaggerVersion')}")
```

```properties
springBootVersion=1.5.16.RELEASE
springCloudVersion=Edgware.SR4
springFoxSwaggerVersion=2.8.0
ioSwaggerVersion=1.5.21
```

But springfox-swagger2 `2.9+` don't work even on `Edgware.SR4`

**Comment by Devskv** [comment]
test

**Comment by Devskv** [comment]
> This works like a charm:
> 
> ```groovy
> dependencyManagement {
>     imports {
>         mavenBom("org.springframework.boot:spring-boot-dependencies:${springBootVersion}")
>         mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
>     }
> }
> 
> // ...
> 
> compile("io.springfox:springfox-swagger2:${property('springFoxSwaggerVersion')}") {
>     exclude module: 'swagger-annotations'
>     exclude module: 'swagger-models'
>  }
> compile("io.swagger:swagger-annotations:${property('ioSwaggerVersion')}")
> compile("io.swagger:swagger-models:${property('ioSwaggerVersion')}")
> ```
> 
> ```ini
> springBootVersion=1.5.16.RELEASE
> springCloudVersion=Edgware.SR4
> springFoxSwaggerVersion=2.8.0
> ioSwaggerVersion=1.5.21
> ```
> 
> But springfox-swagger2 `2.9+` don't work even on `Edgware.SR4`

test

**Comment by Devskv** [comment]
> This works like a charm:
> 
> ```groovy
> dependencyManagement {
>     imports {
>         mavenBom("org.springframework.boot:spring-boot-dependencies:${springBootVersion}")
>         mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
>     }
> }
> 
> // ...
> 
> compile("io.springfox:springfox-swagger2:${property('springFoxSwaggerVersion')}") {
>     exclude module: 'swagger-annotations'
>     exclude module: 'swagger-models'
>  }
> compile("io.swagger:swagger-annotations:${property('ioSwaggerVersion')}")
> compile("io.swagger:swagger-models:${property('ioSwaggerVersion')}")
> ```
> 
> ```ini
> springBootVersion=1.5.16.RELEASE
> springCloudVersion=Edgware.SR4
> springFoxSwaggerVersion=2.8.0
> ioSwaggerVersion=1.5.21
> ```
> 
> But springfox-swagger2 `2.9+` don't work even on `Edgware.SR4`

After all the changed entries, your solution perfectly worked for me..Thanks
My versions : 
		springBootVersion = '1.5.19.RELEASE'
		springFoxSwaggerVersion = '2.8.0'
		ioSwaggerVersion = '1.5.21'

**Comment by salvadornava01** [comment]
> Same issue here with Spring Boot 1.5.2 Release and springfox-swagger 2.9.2 and springfox-ui 2.9.2, Guava version shows as 20.0 (compile).
> 
> Downgrading to 2.8.0 seems to work.

This absolutely worked for me! Thank you so much 😊
