### ISSUE TITLE
Spring Boot - Log4j2 - Swagger UI 

### ISSUE THREAD

**Issue by softwareguidancechintala** [springfox/springfox#2410]
I'm using Swagger 2 and Swagger UI version 2.8.0

My Spring Boot Version - 1.5.9 RELEASE

Log4j2 - 1.5.9 RELEASE

Log4j Core -2.5
Log4j API - 2.5

What kind of issue is this?

I'm trying to implement Swagger into my microservice which is a spring boot app.
I'd like to have the JSON Swagger and the Swagger UI as well.

So I started with adding a couple of dependencies and some config files as below.

Dependencies: (build.gradle)
`dependencies {
	compile("org.springframework.boot:spring-boot-starter-web"){
     exclude group: 'org.springframework.boot', module: 'spring-boot-starter-logging'
  }
	compile ("org.springframework.boot:spring-boot-starter"){
     exclude group: 'org.springframework.boot', module: 'spring-boot-starter-logging'
  }
  	compile ("org.springframework.boot:spring-boot-starter-test"){
     exclude group: 'org.springframework.boot', module: 'spring-boot-starter-logging'
  }
 	compile("org.springframework.boot:spring-boot-starter-jdbc")
 	compile ("org.springframework.boot:spring-boot-actuator")
	compile ("org.springframework.boot:spring-boot-starter-mail")
	
	// Log4j2 Dependenices
	compile ("org.springframework.boot:spring-boot-starter-log4j2")
	compile ("org.apache.logging.log4j:log4j-core:2.5")
	compile ("org.apache.logging.log4j:log4j-api:2.5")
	
	compile ("org.apache.httpcomponents:httpclient:4.5.5")
	compile ("org.apache.httpcomponents:httpcore:4.4.9")	
	
	compile ("com.fasterxml.jackson.core:jackson-databind")
	compile ("com.fasterxml.jackson.core:jackson-annotations:2.9.0")

	
	compile ("javax.xml.bind:jaxb-api:2.3.0")
	compile ("com.sun.xml.bind:jaxb-impl:2.2.7")
	compile("org.json:json:20170516")

	compile ("javax.servlet:javax.servlet-api:3.1.0")
	
	compile ("com.ibm.db2:db2jcc4:1.0")
	compile ("com.ibm.db2:db2jcc4_license_cisuz:1.0")
	
    
	compile ("org.apache.commons:commons-lang3:3.4")
	compile ("org.apache.directory.studio:org.apache.commons.io:2.4")
	
	//Swagger2
	compile ("io.springfox:springfox-swagger2:2.8.0")
	compile ("io.springfox:springfox-swagger-ui:2.8.0")
	
    
}`

SwaggerConfig.java
`import java.util.Collections;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import springfox.documentation.builders.PathSelectors;
import springfox.documentation.builders.RequestHandlerSelectors;
import springfox.documentation.service.ApiInfo;
import springfox.documentation.service.Contact;
import springfox.documentation.spi.DocumentationType;
import springfox.documentation.spring.web.plugins.Docket;
import springfox.documentation.swagger2.annotations.EnableSwagger2;

@Configuration
@EnableSwagger2
public class SwaggerConfig {
	
	@Bean
	public Docket api() {
		return new Docket(DocumentationType.SWAGGER_2)
				.select().apis(RequestHandlerSelectors.any())
				.paths(PathSelectors.any())
				.build().apiInfo(apiInfo());
		}
	

private ApiInfo apiInfo() {
     return new ApiInfo(
       "APIs", 
       "Various Data Services", 
       "1.0", 
       "Terms of service", 
       new Contact("Enterprise Integration", "www.example.com", "support@example.com"), 
       "License of API", "API license URL", Collections.emptyList());
}
	
}`

Upon adding these, I add some annotations to my controller

CANCompanyController.java

`package com.mbusa.customer.controller;

import java.util.List;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Required;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import com.mbusa.customer.model.CANCompanyCustomer;
import com.mbusa.customer.model.CANInfo;
import com.mbusa.customer.service.CANCompanyService;

import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiResponse;

/** Author: Sai Chintala **/

@RestController
public class CANCompanyController {
	
	@Autowired
	CANCompanyService canCompanyService;
	
	private Logger logger=LogManager.getLogger(CANCompanyController.class);
	
	/** API to retrieve Customers by VIN **/
	@ApiOperation("Reteive CAN Company Information by CAN Number")
	@RequestMapping("/api/data/services/info/{canNumber}")
	@ApiResponse( code = 200, message = "OK", response = CANCompanyCustomer.class)
	public ResponseEntity<?> getInfomation(@PathVariable(value="canNumber") String canNumber) throws Exception{
		
		logger.info("Input>>/api/customer/services/cancompanyinformation/"+canNumber);
		return canCompanyService.getInformationService(canNumber);
	}

}
`

When I build and deploy this war on my IBM Liberty, I get the below errors:
`Caused by: org.springframework.context.ApplicationContextException: Failed to start bean 'documentationPluginsBootstrapper'; nested exception is java.lang.NoSuchMethodError: org.apache.logging.log4j.spi.ExtendedLogger.logIfEnabled(Ljava/lang/String;Lorg/apache/logging/log4j/Level;Lorg/apache/logging/log4j/Marker;Ljava/lang/String;Ljava/lang/Object;)V
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178)
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:50)
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:348)
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:151)
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:114)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:880)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:120)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:98)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:116)
	... 47 more
Caused by: java.lang.NoSuchMethodError: org.apache.logging.log4j.spi.ExtendedLogger.logIfEnabled(Ljava/lang/String;Lorg/apache/logging/log4j/Level;Lorg/apache/logging/log4j/Marker;Ljava/lang/String;Ljava/lang/Object;)V
	at org.apache.logging.slf4j.Log4jLogger.info(Log4jLogger.java:184)
	at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.start(DocumentationPluginsBootstrapper.java:154)
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:175)
	... 59 more`

Can someone please help me find what went wrong.

**Comment by dilipkrish** [comment]
Sounds like a [incompatible log4j dependency](https://github.com/spring-projects/spring-boot/issues/9172#issuecomment-300947074)
