### ISSUE TITLE
Could not resolve pointer: /definitions/List does not exist in document

### ISSUE THREAD

**Issue by dingziyang** [springfox/springfox#2563]
## ENV：
- springboot-2.0.2.RELEASE ， springfox-swagger-ui-2.8.0 ， springfox-swagger2-2.8.0

## Q:
- I encapsulated a unified return object. 
```
public class ResultVO<T> implements Serializable {
    // Omit content
}
```
- I used swagger-ui on Controller as API doc . He works in these places and works very well.
```
@ApiOperation(value = "pageList", notes = "paging select", httpMethod = "POST", produces = MediaType.APPLICATION_JSON_VALUE)
    @RequestMapping(value="/pageList",method={RequestMethod.GET,RequestMethod.POST})
    @CtlResultAnnotation
    public ResultVO<PageInfo<DicBase>> pageList(DicBase dicBase, @RequestParam(defaultValue="1") int pageNum,
                                             @RequestParam(defaultValue="10") int pageSize, HttpServletRequest request){
    // Omit content
}

@ApiOperation(value = "children", notes = "get children", httpMethod = "POST", produces = MediaType.APPLICATION_JSON_VALUE)
    @RequestMapping(value="/children",method={RequestMethod.GET,RequestMethod.POST})
    @CtlResultAnnotation
    public ResultVO<List<DicBase>> getChildren(@RequestBody(required=false) DicBase dicBase){
     // Omit content
}

@ApiOperation(value = "view", notes = "detail", httpMethod = "GET", produces = MediaType.APPLICATION_JSON_VALUE)
    @RequestMapping(value="/view",method=RequestMethod.GET)
    @CtlResultAnnotation
    public ResultVO<DicBase> view(@RequestParam Long id){
    // Omit content
}
```
- when I add this controller，I get an error on 'swagger-ui.html'.
```
@ApiOperation(value = "dicValues", notes = "keys-values", httpMethod = "POST", produces = MediaType.APPLICATION_JSON_VALUE)
    @RequestMapping(value="/dicValues",method=RequestMethod.POST)
    @CtlResultAnnotation
    public ResultVO<Map<String, List<DicBase>>> dicValues(@RequestParam(value = "keys[]") List<String> keys){
    // Omit content
}
```
```
Errors
Resolver error at definitions.Map«string,List«DicBase»».additionalProperties.$ref
Could not resolve reference because of: Could not resolve pointer: /definitions/List does not exist in document
```
- Here is my swagger configuation. I know I should add 'alternateTypeRules', but I can not found a full document about this.
```
 private ApiInfo setApiInfo(String title, String description, String teamService, String version) {
        return new ApiInfoBuilder().title(title).description(description).termsOfServiceUrl(teamService).version(version).build();
    }

    @Bean
    public Docket adminRestApi() {
        return new Docket(DocumentationType.SWAGGER_2)
                .apiInfo(setApiInfo("admin-api doc","(PMP)-system-api doc","https://blog.csdn.net/xu_san_duo", "1.0"))
                .alternateTypeRules(
                    newRule(
                        typeResolver.resolve(
                            DeferredResult.class,
                            typeResolver.resolve(GenericType.class, WildcardType.class)
                        ),
                        typeResolver.resolve(WildcardType.class)
                    )
                )
                .groupName("admin module")
                .select()
                .apis(RequestHandlerSelectors.basePackage("com.sdcm.web.controller.admin"))
                .paths(PathSelectors.any())
                .build();
    }
```
- **I want a standard or detailed way, I hope to get your help. Thanks.**

**Comment by dilipkrish** [comment]
Could you please try with 2.9.2 and report back

**Comment by dingziyang** [comment]
@dilipkrish 
I upgraded to 2.9.2 but found a new problem：```java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:601)
	at java.lang.Long.valueOf(Long.java:803)
	at io.swagger.models.parameters.AbstractSerializableParameter.getExample(AbstractSerializableParameter.java:412)
	at sun.reflect.GeneratedMethodAccessor466.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```
Then, I see #2568, #2528 , So, Before you can solve this, I decided to use 2.8.0, at least it just gives a warning in the api documentation instead of giving an exception in my log.
- Also, thanks for your help.

**Comment by prowave** [comment]
I want to report the same issue, and its happening on 2.9.2 for me.

This attribute: `private Map<String, Map<String, List<String>>> highlight;`
Resolves in the JSON as:
```
    "MapOfstringAndListOfstring": {
      "type": "object",
      "title": "MapOfstringAndListOfstring",
      "additionalProperties": {
        "$ref": "#/definitions/List"
      }
    }
```
And when trying to parse with tools like APIMATIC, Apiary and swagger2blueprint I get these errors respectively:
`Unable to resolve reference: #/definitions/List`
`Error resolving $ref pointer "#/definitions/List"`
`Error resolving $ref pointer "#/definitions/List".`

**Comment by prowave** [comment]
I was able to prevent the bad reference from being generated by adding this to my `Docket`.

```
        .alternateTypeRules( 
            AlternateTypeRules.newRule(
                typeResolver.resolve(Map.class, String.class,
                    typeResolver.resolve(Map.class, String.class, typeResolver.resolve(List.class, String.class))),
                typeResolver.resolve(Map.class, String.class, WildcardType.class), Ordered.HIGHEST_PRECEDENCE))
```
where my type was

`Map<String, Map<String, List<String>>>`

ButI still think an invalid spec should be created.  Perhaps a warning with instructions on how to handle nested Generics more than _n_ levels deep?  If that is the accurate description. :)

**Comment by dilipkrish** [comment]
@prowave thanks for the work around. There is a pr out there, but its not an ideal solution, will take a look at it.

**Comment by dingziyang** [comment]
@prowave 
It seems feasible, can you tell me which class the variable ‘typeResolver’ comes from?

**Comment by dingziyang** [comment]
@prowave

**Comment by draco1023** [comment]
@dingziyang Take a 
 look at [this](https://github.com/springfox/springfox/blob/d6c72bf8623b3efaebb3e276154cf98f5fdf8af6/springfox-spring-config/src/main/java/springfox/springconfig/Swagger2SpringBoot.java#L85).

**Comment by prowave** [comment]
@dingziyang `import com.fasterxml.classmate.TypeResolver;`

**Comment by prowave** [comment]
@dingziyang Just replace my `String.class` with your objects.  Something like this:

```
  .alternateTypeRules( 
            AlternateTypeRules.newRule(
                typeResolver.resolve(ResultVO.class, 
                    typeResolver.resolve(Map.class, String.class, typeResolver.resolve(List.class, DicBase.class))),
                typeResolver.resolve(ResultVO.class, WildcardType.class), Ordered.HIGHEST_PRECEDENCE))
```
I cannot test this, but you should be able to take it from here.

**Comment by dingziyang** [comment]
@prowave 
I do it， it's worked! Thank you very much!

**Comment by wangqichang** [comment]
> @prowave thanks for the work around. There is a pr out there, but its not an ideal solution, will take a look at it.

I encountered the same problem.but I don"t want fix it like add alternateTypeRules. If the problem is processed, please let us know.thanks！I encountered the same problem.but I don"t want fix it like add alternateTypeRules. If the problem is processed, please let us know.thanks！

**Comment by wangqichang** [comment]
> @prowave thanks for the work around. There is a pr out there, but its not an ideal solution, will take a look at it.

I encountered the same problem.but I don"t want fix it like add alternateTypeRules. If the problem is processed, please let us know.thanks！

**Comment by goodlux** [comment]
I'm having this same issue, the type I'm trying to resolve is this:

// in FieldValuesMap.class

    @JsonValue
    public Map<FieldName, List<String>> getMap() {
        return map;
    }

FieldName is an object that returns a string. 

I've tried many different iterations of alternateTypes.

The resulting .json file looks like this:

  FieldValuesMap:
    type: object
    title: FieldValuesMap
    additionalProperties:
      **$ref: '#/definitions/List'**

And it has an has the error: **Semantic error at definitions.FieldValuesMap.additionalProperties.$ref
$refs must reference a valid location in the document

----

**Any hints on what sort of AlternateType to feed Docket would help!** I feel like I've tried everything.

----

<img width="345" alt="Screen Shot 2019-11-15 at 5 11 39 PM" src="https://user-images.githubusercontent.com/31841/68985458-67d52980-07cb-11ea-8806-64ff9139675f.png">

<img width="431" alt="Screen Shot 2019-11-15 at 5 15 38 PM" src="https://user-images.githubusercontent.com/31841/68985478-93f0aa80-07cb-11ea-9494-386e0e7b5f1a.png">

**Comment by sherrif10** [comment]
i also got the same issue but for my case it seems every module has got it log error. forexample 
 Resolver error at paths./reportingrest/reportdata.post.parameters.0.schema.$ref
Could not resolve reference because of: Could not resolve pointer: /definitions/ReportingrestReportdataCreate does not exist in document. Could any one direct me of where they error may arose from.

**Comment by manishbit97** [comment]
Still facing this.any update on how can we fix this

**Comment by dilipkrish** [comment]
@manishbit97 is this happening in 3.0.0?

**Comment by manishbit97** [comment]
No, in version 2.8.2

**Comment by dilipkrish** [comment]
The current version is 3.0.0. If for some reason you aren't able to move to the latest version I'd recommend moving to 2.8.2

**Comment by manishbit97** [comment]
I am currently using version 2.8.2 and it exists in that version.

**Comment by adil1996** [comment]
how to resolve List<Map<String.Object>>
