### ISSUE TITLE
Spring boot project failing with NoSuchMethodError

### ISSUE THREAD

**Issue by ror6ax** [springfox/springfox#2651]
Please take the time to search the repository, if your question has already been asked or answered.

- [x] What version of the library are you using? 
2.9.2
What kind of issue is this?

 - [x] Bug report.

I've added class with the following contents to Spring Boot (version 1.5.10) project:

```
@Configuration
@EnableSwagger2
public class SwaggerConfig {                                    
    @Bean
    public Docket api() { 
        return new Docket(DocumentationType.SWAGGER_2)  
          .select()                                  
          .apis(RequestHandlerSelectors.any())              
          .paths(PathSelectors.any())                          
          .build();                                           
    }
}
```
Now build is failing with the following error message

```
com.google.common.util.concurrent.ExecutionError: java.lang.NoSuchMethodError: springfox.documentation.spi.service.contexts.OperationContext.getHandlerMethod()Lorg/springframework/web/method/HandlerMethod;
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2050) ~[guava-25.0-jre.jar:na]
        at com.google.common.cache.LocalCache.get(LocalCache.java:3948) ~[guava-25.0-jre.jar:na]
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3972) ~[guava-25.0-jre.jar:na]
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4957) ~[guava-25.0-jre.jar:na]
        at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4963) ~[guava-25.0-jre.jar:na]
        at springfox.documentation.spring.web.scanners.CachingOperationReader.read(CachingOperationReader.java:57) ~[springfox-spring-web-2.9.1.jar:null]
        at springfox.documentation.spring.web.scanners.ApiDescriptionReader.read(ApiDescriptionReader.java:70) ~[springfox-spring-web-2.9.1.jar:null]
        at springfox.documentation.spring.web.scanners.ApiListingScanner.scan(ApiListingScanner.java:134) [springfox-spring-web-2.9.1.jar:null]
        at springfox.documentation.spring.web.scanners.ApiDocumentationScanner.scan(ApiDocumentationScanner.java:71) [springfox-spring-web-2.9.1.jar:null]
        at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.scanDocumentation(DocumentationPluginsBootstrapper.java:101) [springfox-spring-web-2.9.1.jar:null]
        at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.start(DocumentationPluginsBootstrapper.java:167) [springfox-spring-web-2.9.1.jar:null]
        at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:175) [spring-context-4.3.14.RELEASE.jar:4.3.14.RELEASE]
        at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:50) [spring-context-4.3.14.RELEASE.jar:4.3.14.RELEASE]
        at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:348) [spring-context-4.3.14.RELEASE.jar:4.3.14.RELEASE]
        at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:151) [spring-context-4.3.14.RELEASE.jar:4.3.14.RELEASE]
        at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:114) [spring-context-4.3.14.RELEASE.jar:4.3.14.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:880) [spring-context-4.3.14.RELEASE.jar:4.3.14.RELEASE]
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:144) [spring-boot-1.5.10.RELEASE.jar:1.5.10.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546) [spring-context-4.3.14.RELEASE.jar:4.3.14.RELEASE]
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) [spring-boot-1.5.10.RELEASE.jar:1.5.10.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) [spring-boot-1.5.10.RELEASE.jar:1.5.10.RELEASE]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) [spring-boot-1.5.10.RELEASE.jar:1.5.10.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) [spring-boot-1.5.10.RELEASE.jar:1.5.10.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [spring-boot-1.5.10.RELEASE.jar:1.5.10.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [spring-boot-1.5.10.RELEASE.jar:1.5.10.RELEASE]
        at tech.osp.atm.chancellor.deployment.DeploymentApp.main(DeploymentApp.java:32) [main/:na]
Caused by: java.lang.NoSuchMethodError: springfox.documentation.spi.service.contexts.OperationContext.getHandlerMethod()Lorg/springframework/web/method/HandlerMethod;
        at com.lastmile.shared.jarjar.autoconfigure.aws.dynamodb.swagger.SwaggerDynamoDbCursorPlugin.apply(SwaggerDynamoDbCursorPlugin.java:31) ~[jar-jar-autoconfigure-4.18.11.jar:4.18.11]
        at springfox.documentation.spring.web.plugins.DocumentationPluginsManager.operation(DocumentationPluginsManager.java:120) ~[springfox-spring-web-2.9.1.jar:null]
        at springfox.documentation.spring.web.readers.operation.ApiOperationReader.read(ApiOperationReader.java:73) ~[springfox-spring-web-2.9.1.jar:null]
        at springfox.documentation.spring.web.scanners.CachingOperationReader$1.load(CachingOperationReader.java:50) ~[springfox-spring-web-2.9.1.jar:null]
        at springfox.documentation.spring.web.scanners.CachingOperationReader$1.load(CachingOperationReader.java:48) ~[springfox-spring-web-2.9.1.jar:null]
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529) ~[guava-25.0-jre.jar:na]
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278) ~[guava-25.0-jre.jar:na]
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2156) ~[guava-25.0-jre.jar:na]
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2046) ~[guava-25.0-jre.jar:na]
        ... 25 common frames omitted
```

**Comment by ror6ax** [comment]
ping @dilipkrish , just in case you did not get the notification

**Comment by dilipkrish** [comment]
Im going to try and release end of this month or early next month, time permitting. But to answer your question, it will be in 3.0.0
