### ISSUE TITLE
Been trying to sort this out for 10 hours +. @Configuration and @Import(SpringDataRestConfiguration.class) together

### ISSUE THREAD

**Issue by emanodame** [springfox/springfox#2695]
```java
    @Configuration
    @Primary
    @Import(SpringDataRestConfiguration.class)
    @EnableSwagger2
    public class SwaggerConfiguration extends WebMvcConfigurerAdapter  implements SwaggerResourcesProvider {
  //omitted variables  to make it shorter
        @Bean
        public Docket initialiseDocket() {
            return new Docket(DocumentationType.SWAGGER_2)
                    .apiInfo(getApiInfo()).select()
                    .paths(getPaths())
                    .build()
                    .useDefaultResponseMessages(false);
        }
    
        private ApiInfo getApiInfo() {
            return new ApiInfo(serviceTitle,
                    serviceDescription,
                    serviceVersion,
                    EMPTY_FIELD,
                    new Contact(
                            contactName,
                            contactUrl,
                            contactEmail),
                    EMPTY_FIELD,
                    EMPTY_FIELD,
                    Collections.emptyList());
        }
    
        private Predicate<String> getPaths() {
            return Predicates.or(regex(PATH_REGEX));
        }
    
        @Override
        public void addResourceHandlers(ResourceHandlerRegistry registry) {
            registry.addResourceHandler("/swagger.json").
                    addResourceLocations("classpath:/config");
        }
    
        @Bean
        public SwaggerResourcesProvider swaggerResourcesProvider(InMemorySwaggerResourcesProvider defaultResourcesProvider) {
            return () -> {
                SwaggerResource wsResource = new SwaggerResource();
                wsResource.setName("cars");
                wsResource.setSwaggerVersion("2.0");
                wsResource.setLocation("/swagger.json");
    
                List<SwaggerResource> resources = new ArrayList<>(defaultResourcesProvider.get());
                resources.add(wsResource);
                return resources;
            };
        }
    
        @Override
        public List<SwaggerResource> get() {
            SwaggerResource wsResource = new SwaggerResource();
            wsResource.setName("cars");
            wsResource.setSwaggerVersion("2.0");
            wsResource.setLocation("/swagger.json");
    
            return Collections.singletonList(wsResource);
        }
    }
```
Error is :

```logs
    Error creating bean with name 'documentationPluginsBootstrapper' defined in URL [jar:file:/Users/eodameasante/.m2/repository/io/springfox/springfox-spring-web/2.8.0/springfox-spring-web-2.8.0.jar!/springfox/documentation/spring/web/plugins/DocumentationPluginsBootstrapper.class]: Unsatisfied dependency expressed through constructor argument with index 1 of type [java.util.List]: Error creating bean with name 'basePathAwareServicesProvider' defined in URL [jar:file:/Users/eodameasante/.m2/repository/io/springfox/springfox-data-rest/2.8.0/springfox-data-rest-2.8.0.jar!/springfox/documentation/spring/data/rest/BasePathAwareServicesProvider.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [springfox.documentation.spring.data.rest.BasePathAwareServicesProvider]: No default constructor found; nested exception is java.lang.NoSuchMethodException: springfox.documentation.spring.data.rest.BasePathAwareServicesProvider.<init>(); nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'basePathAwareServicesProvider' defined in URL [jar:file:/Users/eodameasante/.m2/repository/io/springfox/springfox-data-rest/2.8.0/springfox-data-rest-2.8.0.jar!/springfox/documentation/spring/data/rest/BasePathAwareServicesProvider.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [springfox.documentation.spring.data.rest.BasePathAwareServicesProvider]: No default constructor found; nested exception is java.lang.NoSuchMethodException: springfox.documentation.spring.data.rest.BasePathAwareServicesProvider.<init>()
    	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:749) ~[spring-beans-4.2.8.RELEASE.jar:4.2.8.RELEASE]
    	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:185) ~[spring-beans-4.2.8.RELEASE.jar:4.2.8.RELEASE]
    	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1147) ~[spring-beans-4.2.8.RELEASE.jar:4.2.8.RELEASE]
    	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1050) ~[spring-beans-4.2.8.RELEASE.jar:4.2.8.RELEASE]
    	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510) ~[spring-beans-4.2.8.RELEASE.jar:4.2.8.RELEASE]
    	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482) ~[spring-beans-4.2.8.RELEASE.jar:4.2.8.RELEASE]
    	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.2.8.RELEASE.jar:4.2.8.RELEASE]
    	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.2.8.RELEASE.jar:4.2.8.RELEASE]
    	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.2.8.RELEASE.jar:4.2.8.RELEASE]
    	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.2.8.RELEASE.jar:4.2.8.RELEASE]
    	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:778) ~[spring-beans-4.2.8.RELEASE.jar:4.2.8.RELEASE]
    	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:839) ~[spring-context-4.2.8.RELEASE.jar:4.2.8.RELEASE]
    	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538) ~[spring-context-4.2.8.RELEASE.jar:4.2.8.RELEASE]
    	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118) ~[spring-boot-1.3.8.RELEASE.jar:1.3.8.RELEASE]
    	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:760) ~[spring-boot-1.3.8.RELEASE.jar:1.3.8.RELEASE]
    	at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:360) ~[spring-boot-1.3.8.RELEASE.jar:1.3.8.RELEASE]
    	at org.springframework.boot.SpringApplication.run(SpringApplication.java:306) ~[spring-boot-1.3.8.RELEASE.jar:1.3.8.RELEASE]
    	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1185) ~[spring-boot-1.3.8.RELEASE.jar:1.3.8.RELEASE]
    	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1174) ~[spring-boot-1.3.8.RELEASE.jar:1.3.8.RELEASE]
    	at com.expedia.www.reflex.service.Application.main(Application.java:18) ~[classes/:?]
    Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'basePathAwareServicesProvider' defined in URL [jar:file:/Users/eodameasante/.m2/repository/io/springfox/springfox-data-rest/2.8.0/springfox-data-rest-
    	
    	... 19 more

```

Been trying to figure this out for hours with no help. Can anyone help solve this.

**Comment by dilipkrish** [comment]
@emanodame what versions of spring/java are you using?
