### ISSUE TITLE
Swagger not support Recursive Generics now

### ISSUE THREAD

**Issue by Cytusvoid** [springfox/springfox#2700]
My code
``` java
@Data
public class ItemCatOptionDTO implements TreeNode<Long, ItemCatOptionDTO> {
...
}


@GetMapping("/api/test")
public Result<List<ItemCatOptionDTO>> test() {
        return Result.ok();
}
 ```

And then swagger error:
```
org.springframework.context.ApplicationContextException: Failed to start bean 'documentationPluginsBootstrapper'; nested exception is java.lang.reflect.MalformedParameterizedTypeException
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178) ~[spring-context-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:50) ~[spring-context-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:348) ~[spring-context-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:151) ~[spring-context-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:114) ~[spring-context-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:880) ~[spring-context-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:144) ~[spring-boot-1.5.10.RELEASE.jar:1.5.10.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546) ~[spring-context-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.10.RELEASE.jar:1.5.10.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) [spring-boot-1.5.10.RELEASE.jar:1.5.10.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) [spring-boot-1.5.10.RELEASE.jar:1.5.10.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) [spring-boot-1.5.10.RELEASE.jar:1.5.10.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [spring-boot-1.5.10.RELEASE.jar:1.5.10.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [spring-boot-1.5.10.RELEASE.jar:1.5.10.RELEASE]
	at com.qunhe.retail.operationsupport.Application.main(Application.java:58) [classes/:?]
Caused by: java.lang.reflect.MalformedParameterizedTypeException
	at sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl.validateConstructorArguments(ParameterizedTypeImpl.java:58) ~[?:1.8.0_45]
	at sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl.<init>(ParameterizedTypeImpl.java:51) ~[?:1.8.0_45]
	at sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl.make(ParameterizedTypeImpl.java:92) ~[?:1.8.0_45]
	at sun.reflect.generics.factory.CoreReflectionFactory.makeParameterizedType(CoreReflectionFactory.java:105) ~[?:1.8.0_45]
	at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:140) ~[?:1.8.0_45]
	at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49) ~[?:1.8.0_45]
	at sun.reflect.generics.repository.ClassRepository.getSuperInterfaces(ClassRepository.java:105) ~[?:1.8.0_45]
	at java.lang.Class.getGenericInterfaces(Class.java:913) ~[?:1.8.0_45]
	at com.fasterxml.classmate.TypeResolver._resolveSuperInterfaces(TypeResolver.java:425) ~[classmate-1.3.4.jar:1.3.4]
	at com.fasterxml.classmate.TypeResolver._constructType(TypeResolver.java:418) ~[classmate-1.3.4.jar:1.3.4]
	at com.fasterxml.classmate.TypeResolver._fromClass(TypeResolver.java:368) ~[classmate-1.3.4.jar:1.3.4]
	at com.fasterxml.classmate.TypeResolver._fromAny(TypeResolver.java:312) ~[classmate-1.3.4.jar:1.3.4]
	at com.fasterxml.classmate.TypeResolver._fromParamType(TypeResolver.java:466) ~[classmate-1.3.4.jar:1.3.4]
	at com.fasterxml.classmate.TypeResolver._fromAny(TypeResolver.java:315) ~[classmate-1.3.4.jar:1.3.4]
	at com.fasterxml.classmate.TypeResolver._fromParamType(TypeResolver.java:466) ~[classmate-1.3.4.jar:1.3.4]
	at com.fasterxml.classmate.TypeResolver._fromAny(TypeResolver.java:315) ~[classmate-1.3.4.jar:1.3.4]
	at com.fasterxml.classmate.TypeResolver.resolve(TypeResolver.java:174) ~[classmate-1.3.4.jar:1.3.4]
	at com.fasterxml.classmate.ResolvedTypeWithMembers.resolveMethod(ResolvedTypeWithMembers.java:571) ~[classmate-1.3.4.jar:1.3.4]
	at com.fasterxml.classmate.ResolvedTypeWithMembers.resolveMemberMethods(ResolvedTypeWithMembers.java:388) ~[classmate-1.3.4.jar:1.3.4]
	at com.fasterxml.classmate.ResolvedTypeWithMembers.getMemberMethods(ResolvedTypeWithMembers.java:201) ~[classmate-1.3.4.jar:1.3.4]
	at springfox.documentation.spring.web.readers.operation.HandlerMethodResolver.resolvedMethod(HandlerMethodResolver.java:148) ~[springfox-spring-web-2.6.1.jar:2.6.1]
	at springfox.documentation.spring.web.readers.operation.HandlerMethodResolver.methodReturnType(HandlerMethodResolver.java:64) ~[springfox-spring-web-2.6.1.jar:2.6.1]
	at springfox.documentation.spring.web.WebMvcRequestHandler.getReturnType(WebMvcRequestHandler.java:134) ~[springfox-spring-web-2.6.1.jar:2.6.1]
	at springfox.documentation.spi.service.contexts.RequestMappingContext.getReturnType(RequestMappingContext.java:205) ~[springfox-spi-2.6.1.jar:2.6.1]
	at springfox.documentation.spring.web.readers.operation.OperationModelsProvider.collectFromReturnType(OperationModelsProvider.java:74) ~[springfox-spring-web-2.6.1.jar:2.6.1]
	at springfox.documentation.spring.web.readers.operation.OperationModelsProvider.apply(OperationModelsProvider.java:56) ~[springfox-spring-web-2.6.1.jar:2.6.1]
	at springfox.documentation.spring.web.plugins.DocumentationPluginsManager.modelContexts(DocumentationPluginsManager.java:139) ~[springfox-spring-web-2.6.1.jar:2.6.1]
	at springfox.documentation.spring.web.scanners.ApiModelReader.read(ApiModelReader.java:63) ~[springfox-spring-web-2.6.1.jar:2.6.1]
	at springfox.documentation.spring.web.scanners.ApiListingScanner.scan(ApiListingScanner.java:88) ~[springfox-spring-web-2.6.1.jar:2.6.1]
	at springfox.documentation.spring.web.scanners.ApiDocumentationScanner.scan(ApiDocumentationScanner.java:70) ~[springfox-spring-web-2.6.1.jar:2.6.1]
	at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.scanDocumentation(DocumentationPluginsBootstrapper.java:85) ~[springfox-spring-web-2.6.1.jar:2.6.1]
	at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.start(DocumentationPluginsBootstrapper.java:127) ~[springfox-spring-web-2.6.1.jar:2.6.1]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:175) ~[spring-context-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	... 14 more
```

And when I remove the RequestMapping method above. The error disappear.
So I think may be the  recursive generics cause this problem.

**Comment by dilipkrish** [comment]
Could you provide the definition for `Result`. It is actually much easier if you can create a breaking test. Provide your new operation in the BugsController [like this example](https://github.com/springfox/springfox/blob/88f675ee68064f301dade26daea3843f73bb0898/springfox-spring-web/src/test/java/springfox/documentation/spring/web/dummy/controllers/BugsController.java#L473-L476).
