### ISSUE TITLE
Error: Missing ErrorCoded function

### ISSUE THREAD

**Issue by Cejkis** [springfox/springfox#2811]
Hey, I'm getting
```
ERROR [:] ContextLoader:312 - Context initialization failed java.lang.NoClassDefFoundError: org/springframework/core/ErrorCoded
```
when running apache with dependency on springfox 3.0.0 snapshot ( or even 2.9.2). I have spring 5.1.2. Is there anything I can do to fix it or do I have to wait for future release? If I have to wait, is there an estimate, when will it be published?

**Comment by Cejkis** [comment]
name change

**Comment by amutsch** [comment]
@Cejkis 

What bean/class is trying to refer to ErrorCoded?  

ErrorCoded has been removed in Spring 5, it was deprecated in spring 4.  It may not be a springfox library issue but just a general dependency issue.

**Comment by Cejkis** [comment]
@amutsch 
My app works, but once I add 
` <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger2</artifactId>
            <version>3.0.0-SNAPSHOT</version>
        </dependency>`

I'm getting 

`12-Dec-2018 09:13:42.909 SEVERE [RMI TCP Connection(2)-127.0.0.1] org.apache.catalina.core.StandardContext.startInternal One or more listeners failed to start. Full details will be found in the appropriate container log file
2018-12-12 09:13:42.902 ERROR [:] ContextLoader:312 - Context initialization failed java.lang.NoClassDefFoundError: org/springframework/core/ErrorCoded
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_192]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_192]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_192]
	at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:2352) ~[catalina.jar:9.0.12]
	at org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:833) ~[catalina.jar:9.0.12]
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1278) ~[catalina.jar:9.0.12]
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1138) ~[catalina.jar:9.0.12]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_192]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_192]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_192]
	at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:2352) ~[catalina.jar:9.0.12]
	at org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:833) ~[catalina.jar:9.0.12]
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1278) ~[catalina.jar:9.0.12]
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1138) ~[catalina.jar:9.0.12]
	at org.springframework.context.support.AbstractRefreshableApplicationContext.createBeanFactory(AbstractRefreshableApplicationContext.java:207) ~[spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.context.support.AbstractRefreshableApplicationContext.refreshBeanFactory(AbstractRefreshableApplicationContext.java:130) ~[spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.obtainFreshBeanFactory(AbstractApplicationContext.java:622) ~[spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:518) ~[spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:400) ~[spring-web-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:291) ~[spring-web-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:103) ~[spring-web-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4643) ~[catalina.jar:9.0.12]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5109) ~[catalina.jar:9.0.12]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[catalina.jar:9.0.12]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:743) ~[catalina.jar:9.0.12]
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:719) ~[catalina.jar:9.0.12]
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:703) ~[catalina.jar:9.0.12]
	at org.apache.catalina.startup.HostConfig.manageApp(HostConfig.java:1737) ~[catalina.jar:9.0.12]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_192]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_192]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_192]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_192]
	at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:287) ~[tomcat-coyote.jar:9.0.12]
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819) ~[?:1.8.0_192]
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801) ~[?:1.8.0_192]
	at org.apache.catalina.mbeans.MBeanFactory.createStandardContext(MBeanFactory.java:457) ~[catalina.jar:9.0.12]
	at org.apache.catalina.mbeans.MBeanFactory.createStandardContext(MBeanFactory.java:406) ~[catalina.jar:9.0.12]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_192]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_192]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_192]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_192]
	at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:287) ~[tomcat-coyote.jar:9.0.12]
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819) ~[?:1.8.0_192]
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801) ~[?:1.8.0_192]
	at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1468) ~[?:1.8.0_192]
	at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:76) ~[?:1.8.0_192]
	at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1309) ~[?:1.8.0_192]
	at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1401) ~[?:1.8.0_192]
	at javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:829) ~[?:1.8.0_192]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_192]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_192]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_192]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_192]
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:357) ~[?:1.8.0_192]
	at sun.rmi.transport.Transport$1.run(Transport.java:200) ~[?:1.8.0_192]
	at sun.rmi.transport.Transport$1.run(Transport.java:197) ~[?:1.8.0_192]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_192]
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196) ~[?:1.8.0_192]
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573) ~[?:1.8.0_192]
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:834) ~[?:1.8.0_192]
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688) ~[?:1.8.0_192]
	at java.security.AccessController.doPrivileged(Native Method) [?:1.8.0_192]
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687) [?:1.8.0_192]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_192]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_192]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]
Caused by: java.lang.ClassNotFoundException: org.springframework.core.ErrorCoded
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1309) ~[catalina.jar:9.0.12]
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1138) ~[catalina.jar:9.0.12]
	... 66 more

12-Dec-2018 09:13:42.915 SEVERE [RMI TCP Connection(2)-127.0.0.1] org.apache.catalina.core.StandardContext.startInternal Context [] startup failed due to previous errors
[2018-12-12 09:13:42,948] Artifact content-admin:war exploded: Error during artifact deployment. See server log for details.`

**Comment by amutsch** [comment]
@Cejkis 
Is you application available on github?
I would be glad to help work through the issue but classloading and dependencies are usually better done hands on.

I did take a quick look through the current springfox 3.0 snapshots and I didn't see any reference to spring 4 and ErrorCoded class

**Comment by Cejkis** [comment]
Hey, unfortunately our code is private. However, I found dependency on spring 4 when running mvn dependency:tree
`
[INFO] +- io.springfox:springfox-swagger2:jar:3.0.0-SNAPSHOT:compile
[INFO] |  +- io.swagger:swagger-annotations:jar:1.5.20:compile
[INFO] |  +- io.swagger:swagger-models:jar:1.5.20:compile
[INFO] |  +- io.springfox:springfox-spi:jar:3.0.0-SNAPSHOT:compile
[INFO] |  |  \- io.springfox:springfox-core:jar:3.0.0-SNAPSHOT:compile
[INFO] |  +- io.springfox:springfox-schema:jar:3.0.0-SNAPSHOT:compile
[INFO] |  +- io.springfox:springfox-swagger-common:jar:3.0.0-SNAPSHOT:compile
[INFO] |  +- io.springfox:springfox-spring-web:jar:3.0.0-SNAPSHOT:compile
[INFO] |  |  \- io.github.classgraph:classgraph:jar:4.1.7:compile
[INFO] |  +- com.fasterxml:classmate:jar:1.4.0:compile
[INFO] |  +- org.slf4j:slf4j-api:jar:1.7.25:compile
[INFO] |  +- org.springframework.plugin:spring-plugin-core:jar:1.2.0.RELEASE:compile
[INFO] |  |  \- org.springframework:spring-beans:jar:4.0.9.RELEASE:compile
`

**Comment by amutsch** [comment]
@Cejkis 
Can I get more of your pom?  I would expect maven to override the spring beans jar to 5.x unless that is your only reference to it.

I am testing this against a small microservice and I have spring-beans managed to 5.0.10.RELEASE and everything is starting up fine

**Comment by Cejkis** [comment]
Okay, so I added this to my POM next to the springfox swagger and it looks like its solved :)
```
<dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-beans</artifactId>
            <version>5.1.3.RELEASE</version>
        </dependency>
```
Thanks for now, lets hope its gonna be fine

**Comment by amutsch** [comment]
good to hear @Cejkis
