### ISSUE TITLE
When I hit swagger-ui.html getting error "No mapping found on controller class springfox.documentation.swagger2.web.Swagger2Controller!" My service is in Spring MVC 

### ISSUE THREAD

**Issue by debnandy1** [springfox/springfox#2830]
Please take the time to search the repository, if your question has already been asked or answered.

- [ ] What version of the library are you using? Is it the latest version? The latest released version is [ ![Download](https://api.bintray.com/packages/springfox/maven-repo/springfox/images/download.svg) ](https://bintray.com/springfox/maven-repo/springfox/_latestVersion)

What kind of issue is this?

 - [ ] Question. Is this a question about how to do a certain thing? 

 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests or 
       steps to reproduce get fixed faster. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9
    - [ ] spring xml/java config that is relevant
    - [ ] springfox specific configuration if it makes sense
    - [ ] include any output you've received; logs, json snippets etc.; and what the expected output should be
    - [ ] if you have a repo that demonstrates the issue for bonus points! See [this example](https://github.com/springfox/springfox/issues/494) 

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

Please do consider ***starring*** this repository if you do like this project and find it useful.

**Comment by debnandy1** [comment]
Hi @amutsch my code is not available in github. I am using Springfox swagger 2.2.2 and Spring 4.3. It is a Spring MVC project. My project is not maven build so I do not have pom.xml. I have added all the swagger jars manually. I have added an image of the jars added for swagger. Below I have also added the error log. Is it because of Spring hateoas? 
[12/19/18 0:28:58:446 EST] 00000001 WsServerImpl  A   WSVR0001I: Server server1 open for e-business
[12/19/18 0:29:35:955 EST] 00000075 ServletWrappe E com.ibm.ws.webcontainer.servlet.ServletWrapper service SRVE0014E: Uncaught service() exception root cause rentalrtlocsvc-dispatcher: org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.IllegalArgumentException: No mapping found on controller class springfox.documentation.swagger2.web.Swagger2Controller!
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:982)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:575)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:668)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1233)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:782)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:481)
	at com.ibm.ws.webcontainer.servlet.ServletWrapperImpl.handleRequest(ServletWrapperImpl.java:178)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1114)
	at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:3980)
	at com.ibm.ws.webcontainer.webapp.WebGroup.handleRequest(WebGroup.java:304)
	at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:1016)
	at com.ibm.ws.webcontainer.WSWebContainer.handleRequest(WSWebContainer.java:1817)
	at com.ibm.ws.webcontainer.channel.WCChannelLink.ready(WCChannelLink.java:200)
	at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:463)
	at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.handleNewRequest(HttpInboundLink.java:530)
	at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.processRequest(HttpInboundLink.java:316)
	at com.ibm.ws.http.channel.inbound.impl.HttpICLReadCallback.complete(HttpICLReadCallback.java:88)
	at com.ibm.ws.tcp.channel.impl.AioReadCompletionListener.futureCompleted(AioReadCompletionListener.java:175)
	at com.ibm.io.async.AbstractAsyncFuture.invokeCallback(AbstractAsyncFuture.java:217)
	at com.ibm.io.async.AsyncChannelFuture.fireCompletionActions(AsyncChannelFuture.java:161)
	at com.ibm.io.async.AsyncFuture.completed(AsyncFuture.java:138)
	at com.ibm.io.async.ResultHandler.complete(ResultHandler.java:204)
	at com.ibm.io.async.ResultHandler.runEventProcessingLoop(ResultHandler.java:775)
	at com.ibm.io.async.ResultHandler$2.run(ResultHandler.java:905)
	at com.ibm.ws.util.ThreadPool$Worker.run(ThreadPool.java:1892)
Caused by: java.lang.IllegalArgumentException: No mapping found on controller class springfox.documentation.swagger2.web.Swagger2Controller!
	at org.springframework.hateoas.mvc.ControllerLinkBuilder.linkTo(ControllerLinkBuilder.java:92)
	at org.springframework.hateoas.mvc.ControllerLinkBuilder.linkTo(ControllerLinkBuilder.java:72)
	at springfox.documentation.swagger2.web.Swagger2Controller.hostName(Swagger2Controller.java:82)
	at springfox.documentation.swagger2.web.Swagger2Controller.getDocumentation(Swagger2Controller.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:95)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	... 26 more

![swagger_jars](https://user-images.githubusercontent.com/45944023/50201913-0c37bd00-032a-11e9-847f-fa179b8d64ed.PNG)

**Comment by debnandy1** [comment]
Hi @amutsch Yesterday night I added mapstruct-1.2.0.jar and aopalliance-1.0.jar. So do you suggest I should change springfox-data-rest-2.9.2.jar?

**Code for service configuration :**
@EnableWebMvc
@Configuration
@Import(value={JndiDataSourceConfiguration.class, SwaggerConfig.class})
@ComponentScan(basePackages = {"com.penske.rentalservice.rateslocation"})
public class RentalServiceConfiguration extends WebMvcConfigurerAdapter {
	
	
    
    // equivalents for <mvc:resources/> tags
    @Override
    public void addResourceHandlers(ResourceHandlerRegistry registry) {
    	registry.addResourceHandler("**/**").addResourceLocations("classpath:/META-INF/resources/");
        registry.addResourceHandler("**/webjars/**").addResourceLocations("classpath:/META-INF/resources/webjars/");
    }
    
   
    
    
}

Code for swagger config:
package com.penske.rentalservice.spring.configuration;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.Configuration;
import org.springframework.web.servlet.config.annotation.DefaultServletHandlerConfigurer;
import org.springframework.web.servlet.config.annotation.EnableWebMvc;
import org.springframework.web.servlet.config.annotation.ResourceHandlerRegistry;
import org.springframework.web.servlet.config.annotation.WebMvcConfigurerAdapter;

import com.google.common.base.Predicate;
import com.google.common.base.Predicates;

import springfox.documentation.builders.PathSelectors;
import springfox.documentation.builders.RequestHandlerSelectors;
import springfox.documentation.spi.DocumentationType;
import springfox.documentation.spring.web.plugins.Docket;
import springfox.documentation.swagger2.annotations.EnableSwagger2;
import springfox.documentation.swagger2.configuration.Swagger2DocumentationConfiguration;

/**
 * @author 501918228
 *
 */
@Configuration
@EnableSwagger2
public class SwaggerConfig {
	@Bean
    public Docket apiDocket() {

       return new Docket(DocumentationType.SWAGGER_2)
                .select()
                .apis(RequestHandlerSelectors.any())
                .paths(PathSelectors.any())
                .build();
    }
    	
}

**Comment by amutsch** [comment]
@debnandy1 
I am suggesting all your springfox libraries should be 2.9.2.  
Also why do you need the springfox-data-rest library?  
Do you have controllers or are your repositories generating the api?

**Comment by debnandy1** [comment]
@amutsch I removed springfox-data-rest and all my springfox jars are now for 2.2.2 and still received the same error.

**Comment by amutsch** [comment]
@debnandy1 
your springfox libraries should be 2.9.2.

**Comment by debnandy1** [comment]
@amutsch After changing to 2.9.2 I am seeing below error:
Caused by: org.springframework.context.annotation.ConflictingBeanDefinitionException: Annotation-specified bean name 'swaggerParameterDescriptionReader' for bean class [springfox.documentation.swagger.readers.parameter.ApiParamParameterBuilder] conflicts with existing, non-compatible bean definition of same name and class [springfox.documentation.swagger.readers.parameter.ParameterDescriptionReader]
	at org.springframework.context.annotation.ClassPathBeanDefinitionScanner.checkCandidate(ClassPathBeanDefinitionScanner.java:345)
	at org.springframework.context.annotation.ClassPathBeanDefinitionScanner.doScan(ClassPathBeanDefinitionScanner.java:283)
	at org.springframework.context.annotation.ComponentScanAnnotationParser.parse(ComponentScanAnnotationParser.java:135)
	at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:287)
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:245)
	at org.springframework.context.annotation.ConfigurationClassParser.processImports(ConfigurationClassParser.java:606)
	... 44 more

**Comment by debnandy1** [comment]
@amutsch I have upgraded to Swagger 2.9.2 and the above error has been resolved too. But now while invoking /swagger-ui.html I am getting Error 404: SRVE0295E: Error reported: 404. When I am invoking /api-docs and /swagger-resources it is loading correctly. I have below code snippet to load swagger-ui.html.
registry.addResourceHandler("swagger-ui.html").addResourceLocations("classpath:/META-INF/resources/");
        registry.addResourceHandler("/webjars/**").addResourceLocations("classpath:/META-INF/resources/webjars/");

**Comment by debnandy1** [comment]
I was missing springfox-swagger-ui 2.9.2.jar. After adding that it worked.

**Comment by rohit-ash-choudhary** [comment]
Hibernate: select r1_0.user_user_id,r1_1.role_id,r1_1.role_name from user_roles r1_0 join roles r1_1 on r1_1.role_id=r1_0.roles_role_id where r1_0.user_user_id=?
2025-03-02T15:53:26.782+05:30  WARN 31284 --- [Electronic-Store] [nio-9090-exec-6] o.s.web.servlet.PageNotFound             : No mapping for GET /swagger-ui/index.html
2025-03-02T15:53:26.782+05:30  WARN 31284 --- [Electronic-Store] [nio-9090-exec-6] o.s.web.servlet.PageNotFound             : No endpoint GET /swagger-ui/index.html.

**Comment by rohit-ash-choudhary** [comment]
I am getting same error 

_**2025-03-02T15:53:26.782+05:30  WARN 31284 --- [Electronic-Store] [nio-9090-exec-6] o.s.web.servlet.PageNotFound             : No mapping for GET /swagger-ui/index.html
2025-03-02T15:53:26.782+05:30  WARN 31284 --- [Electronic-Store] [nio-9090-exec-6] o.s.web.servlet.PageNotFound             : No endpoint GET /swagger-ui/index.html.**_

I added this dependency & I am using spring 3 version
<dependency>
			<groupId>org.springdoc</groupId>
			<artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
			<version>2.8.5</version>
		</dependency>
