### ISSUE TITLE
Class springfox.documentation.schema.ModelReferenceProvider does not implement the requested interface java.util.function.Function

### ISSUE THREAD

**Issue by cloud4288** [springfox/springfox#2964]
What version of the library are you using? **2.9.2**

Spring Boot Version: **2.1.4**

**Problem:**
I'm unable to run a Spring Boot 2 application, here is the exception thrown at runtime.
`com.google.common.util.concurrent.ExecutionError: java.lang.IncompatibleClassChangeError: Class springfox.documentation.schema.ModelReferenceProvider does not implement the requested interface java.util.function.Function
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2212) ~[guava-20.0.jar:na]
	at com.google.common.cache.LocalCache.get(LocalCache.java:4053) ~[guava-20.0.jar:na]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4057) ~[guava-20.0.jar:na]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4986) ~[guava-20.0.jar:na]
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4992) ~[guava-20.0.jar:na]
	at springfox.documentation.spring.web.scanners.CachingOperationReader.read(CachingOperationReader.java:57) ~[springfox-spring-web-2.9.2.jar:null]
	at springfox.documentation.spring.web.scanners.ApiDescriptionReader.read(ApiDescriptionReader.java:70) ~[springfox-spring-web-2.9.2.jar:null]
	at springfox.documentation.spring.web.scanners.ApiListingScanner.scan(ApiListingScanner.java:134) ~[springfox-spring-web-2.9.2.jar:null]
	at ...`

**Solution:**
Update to the latest version of Google Guava: **27.1-jre**

**Comment by ulugbekrozimboyev** [comment]
I have also the same problem, If anyone found solution please share

**Comment by pipzgutz** [comment]
@ulugbekrozimboyev try updating the version of google guava
