### ISSUE TITLE
API Group Name contains '"' as '{', '}' and '|' is not being escaped.

### ISSUE THREAD

**Issue by bmistry13** [springfox/springfox#2981]
Please take the time to search the repository, if your question has already been asked or answered.

- [ ] What version of the library are you using? Is it the latest version? The latest released version is 2.9.2

What kind of issue is this?
 The issue is with Swagger Group name contain '"' as '{', '}' and '|' character.  It is not getting escaped in URL field.  The UI just takes a group name/url and create a selection box with api-doc. 

http://<ip>:<port>/<Context-Path>/swagger-resources
[{
	"name": "/v1/tenants/{tenant-uuid}/profiles/",
	"url": "/v2/api-docs?group=/v1/tenants/{tenant-uuid}/profiles/",
	"swaggerVersion": "2.0",
	"location": "/v2/api-docs?group=/v1/tenants/{tenant-uuid}/profiles/"
}]

 - [ ] Question. Is this a question about how to do a certain thing? 
No
 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests or 
       steps to reproduce get fixed faster. Here’s an example:  

1) Register Docket with Group name '/v1/tenants/{tenant-uuid}/profiles/'  as shown below.
2) Now go to http://<ip>:<port>/portalapi/swagger-ui.html
3) Select group name '/v1/tenants/{tenant-uuid}/profiles/'
4) Please note that UI makes call to http://<ip>:<port>/<context-path>/v2/api-docs?group=/v1/tenants/{tenant-uuid}/profiles/

5) Backed return 404 BAD REQUEST because  characters '"' as '{', '}' and '|' are invalid in
URL and Tomcat throws 404.

> 2019-04-30 18:40:34.708  INFO 5470 --- [nio-8448-exec-9] o.apache.coyote.http11.Http11Processor   : Error parsing HTTP request header
>  Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.
> 
> java.lang.IllegalArgumentException: Invalid character found in the request target. The valid characters are defined in RFC 7230 and RFC 3986
> 	at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:467)
> 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:294)
> 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
> 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:834)
> 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1415)
> 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
> 	at java.base/java.lang.Thread.run(Thread.java:834)
> 

```
public void postConstruct() throws ClassNotFoundException, UnsupportedEncodingException {
		
		
		ClassPathScanningCandidateComponentProvider provider = new ClassPathScanningCandidateComponentProvider(false);
		provider.addIncludeFilter(new AnnotationTypeFilter(RestController.class));
		Set<String> gorups = new HashSet<String>();
		for (BeanDefinition beanDef : provider.findCandidateComponents("x.y.z.rest.controller")) {
			Class<?> cl = Class.forName(beanDef.getBeanClassName());
			
			RequestMapping requestMapping = cl.getAnnotation(RequestMapping.class);
			if (null != requestMapping && null != requestMapping.value() && requestMapping.value().length > 0) {
				String resource_group = requestMapping.value()[0];
				if(gorups.contains(resource_group)) {
					Api api = cl.getAnnotation(Api.class);
					if(api != null && api.tags() != null && api.tags().length > 0) {
						resource_group = resource_group + "-"+api.tags()[0];
					}
				}
				gorups.add(resource_group);
				SingletonBeanRegistry beanRegistry = context.getBeanFactory();
				Docket docket = new Docket(DocumentationType.SWAGGER_2).groupName(resource_group).apiInfo(metaData())
						.forCodeGeneration(Boolean.TRUE)
						.globalOperationParameters(
								avoidTenanatUUID.contains(cl)? 
										Arrays.asList(new ParameterBuilder().name("User-Name").description("Current User Name")
												.modelRef(new ModelRef("string")).parameterType("header").required(true)
												.defaultValue(TransactionManagementService.STATIC_USER_SESSION.getUserName()).build())
										:
								Arrays.asList(new ParameterBuilder().name("User-Name").description("Current User Name")
										.modelRef(new ModelRef("string")).parameterType("header").required(true)
										.defaultValue(TransactionManagementService.STATIC_USER_SESSION.getUserName()).build(),
										new ParameterBuilder().name("tenant-uuid").description("Current UUID of Tenant that user has chosen for LifeCycle Graph.")
										.modelRef(new ModelRef("uuid")).parameterType("path").required(true)
										.defaultValue(UUID.randomUUID().toString()).build()
										)
								)
						.select()
						.paths("/v1/tenants".equals(resource_group)
								?PathSelectors.regex(resource_group + ".((?!tenant-uuid).)*")
										:PathSelectors.regex(resource_group.replace("{", "\\{").replace("}", "\\}") + ".*") )
						.paths(Predicates.not(PathSelectors.regex("/error.*"))).build();
				beanRegistry.registerSingleton(cl.getSimpleName() + "_docket_api", docket);
			}
		}

@RestController
@RequestMapping(value = "/v1/tenants/{tenant-uuid}/profiles/")
public class TestController{

}
```

A potential fix is to escape it in the following file:
https://github.com/springfox/springfox/blob/master/springfox-swagger-common/src/main/java/springfox/documentation/swagger/web/InMemorySwaggerResourcesProvider.java

```
  private String swaggerLocation(String swaggerUrl, String swaggerGroup) {
    String base = of(swaggerUrl).get();
    if (Docket.DEFAULT_GROUP_NAME.equals(swaggerGroup)) {
      return base;
    }
    return base + "?group=" + URLEncoder.encode(swaggerGroup, "UTF-8");
  }
```

**Comment by bmistry13** [comment]
@dilipkrish,  Can you please look into this issue and potential fix?
