### ISSUE TITLE
Bug: swagger-ui sourcemaps are invalid

### ISSUE THREAD

**Issue by Lucas-C** [springfox/springfox#3114]
This should be relatively straightfoward, taking inspiration from https://github.com/springfox/springfox/pull/2956

However this is pending on https://github.com/api-platform/core/pull/3021
I'll submit a PR once this patch is merged upstream, and [released](https://github.com/api-platform/core/releases) (in `v2.4.7` ?)

**Comment by Lucas-C** [comment]
My mistake: this repo does not rely on https://github.com/api-platform/core but on https://github.com/swagger-api/swagger-ui/

( source: https://github.com/springfox/springfox/blob/master/springfox-swagger-ui/build.gradle#L32 )

Moreover the `.map` files are already added here:
https://github.com/springfox/springfox/blob/master/springfox-swagger-ui/build.gradle#L132

And I tested, that they are correctly served:
- http://localhost:8080/rest/webjars/springfox-swagger-ui/swagger-ui-bundle.js -> `HTTP 200`
- http://localhost:8080/rest/webjars/springfox-swagger-ui/swagger-ui-bundle.js.map -> `HTTP 200`

However they seem to be invalid, based on [sourcemap-validator](https://github.com/ben-ng/sourcemap-validator) and `springfox-swagger-ui 2.9.2`:
```
sourcemap-validate swagger-ui-bundle.js swagger-ui-bundle.js.map
C:\Users\lucas_cimon\AppData\Roaming\npm\node_modules\sourcemap-validator\index.js:155
          throw new Error(errMsg);
          ^

Error: Warning: mismatched names
Expected: root || 'root' || 'root' || "root" || "root"
Got: (fun || (funct || (funct || (funct || (funct
Original Line: (function webpackUniversalModuleDefinition(root, factory) {
Mapping: 1:10→1:0 "root" in webpack:///webpack/universalModuleDefinition
    at C:\Users\lucas_cimon\AppData\Roaming\npm\node_modules\sourcemap-validator\index.js:155:17
    at Array.forEach (<anonymous>)
    at SourceMapConsumer_eachMapping [as eachMapping] (C:\Users\lucas_cimon\AppData\Roaming\npm\node_modules\sourcemap-validator\node_modules\source-map\lib\source-map\source-map-consumer.js:570:10)
    at validate (C:\Users\lucas_cimon\AppData\Roaming\npm\node_modules\sourcemap-validator\index.js:92:12)
    at Object.<anonymous> (C:\Users\lucas_cimon\AppData\Roaming\npm\node_modules\sourcemap-validator\index.js:166:5)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
```

**Comment by Lucas-C** [comment]
Pending upstream bug resolution: https://github.com/swagger-api/swagger-ui/issues/5598
