### ISSUE TITLE
ApiParam for type Long generates warning when example is not set

### ISSUE THREAD

**Issue by sigand** [springfox/springfox#3277]
Springfox version: 2.9.2
Swagger version: 1.5.20
Spring Boot version: 2.2.1.RELEASE
Kotlin version: 1.3.61

@ApiParam(value = "Some description.") @RequestParam(value"param") param: Long

Illegal DefaultValue null for parameter type integer. For input string: "" java.lang.NumberFormatException: For input string: "" at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) at java.lang.Long.parseLong(Long.java:601) at java.lang.Long.valueOf(Long.java:803) at io.swagger.models.parameters.AbstractSerializableParameter.getExample(AbstractSerializableParameter.java:412) ..... "

**Comment by dilipkrish** [comment]
This is a problem with the underlying swagger-core library.
