### ISSUE TITLE
Duplicate xmlModelPlugin definition

### ISSUE THREAD

**Issue by anuprk** [springfox/springfox#3308]
Getting below exception when integrating Swagger into Spring MVC application.

```
2020-05-14 16:09:11,543  WARN http-bio-7080-exec-1 AnnotationConfigWebApplicationContext Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanDefinitionStoreException: Failed to process import candidates for configuration class [springfox.documentation.spring.web.SpringfoxWebMvcConfiguration]; nested exception is org.springframework.context.annotation.ConflictingBeanDefinitionException: Annotation-specified bean name 'xmlModelPlugin' for bean class [springfox.documentation.schema.plugins.XmlModelPlugin] conflicts with existing, non-compatible bean definition of same name and class [springfox.documentation.schema.XmlModelPlugin]
2020-05-14 16:09:11,555 ERROR http-bio-7080-exec-1 ContextLoader Context initialization failed
org.springframework.beans.factory.BeanDefinitionStoreException: Failed to process import candidates for configuration class [springfox.documentation.spring.web.SpringfoxWebMvcConfiguration]; nested exception is org.springframework.context.annotation.ConflictingBeanDefinitionException: Annotation-specified bean name 'xmlModelPlugin' for bean class [springfox.documentation.schema.plugins.XmlModelPlugin] conflicts with existing, non-compatible bean definition of same name and class [springfox.documentation.schema.XmlModelPlugin]
	at org.springframework.context.annotation.ConfigurationClassParser.processImports(ConfigurationClassParser.java:597)
	at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:305)
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:245)
	at org.springframework.context.annotation.ConfigurationClassParser.processImports(ConfigurationClassParser.java:587)
	at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:305)
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:245)
	at org.springframework.context.annotation.ConfigurationClassParser.processImports(ConfigurationClassParser.java:587)
	at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:305)
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:245)
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:202)
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:170)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:319)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:236)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:275)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:95)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:706)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:532)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:401)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:292)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:103)


Caused by: org.springframework.context.annotation.ConflictingBeanDefinitionException: Annotation-specified bean name 'xmlModelPlugin' for bean class [springfox.documentation.schema.plugins.XmlModelPlugin] conflicts with existing, non-compatible bean definition of same name and class [springfox.documentation.schema.XmlModelPlugin]
	at org.springframework.context.annotation.ClassPathBeanDefinitionScanner.checkCandidate(ClassPathBeanDefinitionScanner.java:349)
	at org.springframework.context.annotation.ClassPathBeanDefinitionScanner.doScan(ClassPathBeanDefinitionScanner.java:287)
	at org.springframework.context.annotation.ComponentScanAnnotationParser.parse(ComponentScanAnnotationParser.java:132)
	at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:290)
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:245)
	at org.springframework.context.annotation.ConfigurationClassParser.processImports(ConfigurationClassParser.java:587)
	... 63 more
```

Tried using 2.7.0 and 2.9.1 but same issue.

```
compile "io.springfox:springfox-swagger2:2.7.0"
compile "io.springfox:springfox-swagger-ui:2.7.0"
```

I only added @EnableSwagger2 annotation to current webconfig with 

```
@EnableSwagger2
public class WebConfig extends WebMvcConfigurationSupport
{
   @Bean
    public Docket api() {
        return new Docket(DocumentationType.SWAGGER_2).select()
            .apis(RequestHandlerSelectors
                .basePackage("mypackage))
            .paths(PathSelectors.any())
            .build().apiInfo(apiEndPointsInfo());
    }

    private ApiInfo apiEndPointsInfo() {
        return new ApiInfoBuilder().title("Title")
            .description("Description")
            .version("1.0.0")
            .build();
    }
}
```

And added follwoing in servlet-context.xml 

```
<mvc:resources mapping="swagger-ui.html" location="classpath:/META-INF/resources/" />
   <mvc:resources mapping="/webjars/**" location="classpath:/META-INF/resources/webjars/" />
```

**Comment by anuprk** [comment]
Closing this issue. Had multiple version of spring fox jars in class path. Thanks.

**Comment by Inger-Chao** [comment]
> Closing this issue. Had multiple version of spring fox jars in class path. Thanks.

I got the same bug, fixed by the same solution.

```bash
./gradlew dependencies > ~/Documents/gmp/bsc/gradle-lib-tress.txt
```

**Comment by Inger-Chao** [comment]
> Closing this issue. Had multiple version of spring fox jars in class path. Thanks.

I got the same bug, fixed by the same solution.

```bash
./gradlew dependencies > ~/Documents/gmp/bsc/gradle-lib-tress.txt
```
