### ISSUE TITLE
NPE on EnumMapper.maybeAddAllowableValuesToParameter(EnumMapper.java:117)

### ISSUE THREAD

**Issue by othellico** [springfox/springfox#3339]
I'm using the 3.0.0-SNAPSHOT release, updated to this morning.

When I do a GET on /v2/api-docs, I get this error:

```
2020-06-24 09:55:54.754 ERROR 2880 --- [     parallel-1] a.w.r.e.AbstractErrorWebExceptionHandler : [5970db4a]  500 Server Error for HTTP GET "/v2/api-docs"

java.lang.NullPointerException: null
        at springfox.documentation.swagger2.mappers.EnumMapper.maybeAddAllowableValuesToParameter(EnumMapper.java:117) ~[springfox-swagger2-3.0.0-SNAPSHOT.jar:null]
        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
Error has been observed at the following site(s):
        |_ checkpoint ? it.siav.jarvis.integration.pillar.configuration.ContextPathConfig$$Lambda$696/0x0000000800fbe040 [DefaultWebFilterChain]
        |_ checkpoint ? HTTP GET "/v2/api-docs" [ExceptionHandlingWebHandler]
Stack trace:
                at springfox.documentation.swagger2.mappers.EnumMapper.maybeAddAllowableValuesToParameter(EnumMapper.java:117) ~[springfox-swagger2-3.0.0-SNAPSHOT.jar:null]
                at springfox.documentation.swagger2.mappers.RequestParameterMapper.lambda$mapParameter$1(RequestParameterMapper.java:88) ~[springfox-swagger2-3.0.0-SNAPSHOT.jar:null]
                at java.base/java.util.Optional.ifPresent(Optional.java:176) ~[na:na]
                at springfox.documentation.swagger2.mappers.RequestParameterMapper.mapParameter(RequestParameterMapper.java:88) ~[springfox-swagger2-3.0.0-SNAPSHOT.jar:null]
                at springfox.documentation.swagger2.mappers.ServiceModelToSwagger2Mapper.beforeMappingOperations(ServiceModelToSwagger2Mapper.java:125) ~[springfox-swagger2-3.0.0-SNAPSHOT.jar:null]
                at springfox.documentation.swagger2.mappers.ServiceModelToSwagger2MapperImpl.mapOperation(ServiceModelToSwagger2MapperImpl.java:108) ~[springfox-swagger2-3.0.0-SNAPSHOT.jar:null]
                at springfox.documentation.swagger2.mappers.ServiceModelToSwagger2Mapper.mapOperations(ServiceModelToSwagger2Mapper.java:270) ~[springfox-swagger2-3.0.0-SNAPSHOT.jar:null]
                at springfox.documentation.swagger2.mappers.ServiceModelToSwagger2Mapper.lambda$mapApiListings$2(ServiceModelToSwagger2Mapper.java:258) ~[springfox-swagger2-3.0.0-SNAPSHOT.jar:null]
                at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[na:na]
                at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1624) ~[na:na]
                at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658) ~[na:na]
                at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274) ~[na:na]
                at java.base/java.util.TreeMap$ValueSpliterator.forEachRemaining(TreeMap.java:2905) ~[na:na]
                at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[na:na]
                at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[na:na]
                at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[na:na]
                at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[na:na]
                at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
                at java.base/java.util.stream.ReferencePipeline.forEachOrdered(ReferencePipeline.java:502) ~[na:na]
                at springfox.documentation.swagger2.mappers.ServiceModelToSwagger2Mapper.mapApiListings(ServiceModelToSwagger2Mapper.java:253) ~[springfox-swagger2-3.0.0-SNAPSHOT.jar:null]
                at springfox.documentation.swagger2.mappers.ServiceModelToSwagger2MapperImpl.mapDocumentation(ServiceModelToSwagger2MapperImpl.java:47) ~[springfox-swagger2-3.0.0-SNAPSHOT.jar:null]
                at springfox.documentation.swagger2.web.Swagger2ControllerWebFlux.getDocumentation(Swagger2ControllerWebFlux.java:90) ~[springfox-swagger2-3.0.0-SNAPSHOT.jar:null]
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
                at java.base/java.lang.reflect.Method.invoke(Method.java:564) ~[na:na]
                at org.springframework.web.reactive.result.method.InvocableHandlerMethod.lambda$invoke$0(InvocableHandlerMethod.java:147) ~[spring-webflux-5.2.3.RELEASE.jar:5.2.3.RELEASE]
                at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:118) ~[reactor-core-3.3.2.RELEASE.jar:3.3.2.RELEASE]
                at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1637) ~[reactor-core-3.3.2.RELEASE.jar:3.3.2.RELEASE]
                at reactor.core.publisher.MonoZip$ZipCoordinator.signal(MonoZip.java:247) ~[reactor-core-3.3.2.RELEASE.jar:3.3.2.RELEASE]
                at reactor.core.publisher.MonoZip$ZipInner.onNext(MonoZip.java:329) ~[reactor-core-3.3.2.RELEASE.jar:3.3.2.RELEASE]
                at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:173) ~[reactor-core-3.3.2.RELEASE.jar:3.3.2.RELEASE]
                at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2199) ~[reactor-core-3.3.2.RELEASE.jar:3.3.2.RELEASE]
                at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.request(MonoPeekTerminal.java:132) ~[reactor-core-3.3.2.RELEASE.jar:3.3.2.RELEASE]
                at reactor.core.publisher.MonoZip$ZipInner.onSubscribe(MonoZip.java:318) ~[reactor-core-3.3.2.RELEASE.jar:3.3.2.RELEASE]
                at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onSubscribe(MonoPeekTerminal.java:145) ~[reactor-core-3.3.2.RELEASE.jar:3.3.2.RELEASE]
                at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:54) ~[reactor-core-3.3.2.RELEASE.jar:3.3.2.RELEASE]
                at reactor.core.publisher.Mono.subscribe(Mono.java:4105) ~[reactor-core-3.3.2.RELEASE.jar:3.3.2.RELEASE]
...
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 9.616 s <<< FAILURE! - in it.siav.jarvis.integration.pillar.SwaggerCreatorPseudoTest
[ERROR] createSpringfoxSwaggerJson  Time elapsed: 0.76 s  <<< FAILURE!
java.lang.AssertionError:
Status expected:<200 OK> but was:<500 INTERNAL_SERVER_ERROR>

> GET /v2/api-docs
> WebTestClient-Request-Id: [1]
> Accept: [application/json]

No content

< 500 INTERNAL_SERVER_ERROR Internal Server Error
< Content-Type: [application/json]
< Content-Length: [149]

{"timestamp":"2020-06-24T07:55:54.749+0000","path":"/v2/api-docs","status":500,"error":"Internal Server Error","message":null,"requestId":"5970db4a"}

```

My project is a webflux one with Spring Boot 2.2.4-RELEASE.

I user a test class to generate the swagger.json file:

```
@WebAppConfiguration
@ExtendWith(SpringExtension.class)
@WebFluxTest
@AutoConfigureWebTestClient
@ActiveProfiles({"local", "development"})
class SwaggerCreatorPseudoTest {

    @Autowired
    private WebTestClient webTestClient;

    @Test
    void createSpringfoxSwaggerJson() throws IOException {
        String outputDir = "target/generated-docs";
        String swaggerJson = webTestClient
                .get()
                .uri("/v2/api-docs")
                .accept(MediaType.APPLICATION_JSON)
                .exchange()
                .expectStatus().isOk()
                .returnResult(String.class)
                .getResponseBody()
                .blockFirst();

        if (swaggerJson != null) {
            Files.createDirectories(Paths.get(outputDir));
            try (BufferedWriter writer = Files.newBufferedWriter(Paths.get(outputDir, "swagger.json"), StandardCharsets.UTF_8)) {
                writer.write(swaggerJson);
            }
        }
    }

}
```

Until yesterday I had no problems launching that test class.
Thanks

Claudio

**Comment by dilipkrish** [comment]
That stack trace doesn't match what's on master. Would you be able to create a failing test or [replicate it here fixed](https://github.com/springfox/springfox-demos/blob/master/boot-webflux/src/main/java/io/springfox/demo/bootwebflux/BootWebfluxApplication.java)?  so this can be fixed. Alternatively you could try one of these 
- 2.10.5 which is a snapshot of the 3.0.0-SNAPSHOT.
- trying setting the following property `springfox.documentation.swagger.v2.use-model-v3=false`

**Comment by othellico** [comment]
With the version 2.10.5 it works, but it has the molteplicity bug (the same bean replicated more times).
It's very hard for me to write a failing test: I have 1435 operations and 10k+ beans and the trace does not give me any information to identify witch operation, or bean, or attribute causes the NPE.
Maybe this bug can be modified in: add info to determine che cause of NPE in maybeAddAllowableValuesToParameter.
Thanks.
Claudio

**Comment by dilipkrish** [comment]
This should no longer be an issue, @othellico would you mind confirming that it works in the latest snapshot?

**Comment by othellico** [comment]
Hi @dilipkrish !
With the latest snapshot I have a new problem!
A bean that I use both for request and response now is duplicated, one with the "Req" suffix and one with the "Res" suffix.
That is even worse than the number suffix of multiple beans, because the name is different from client to server view!
Claudio

**Comment by dilipkrish** [comment]
@othellico I dont understand. If you had the the numbered suffixes before it means the models are truly different. Can you provide an example of a scenario where it should not be the case and it is so I can see if it can be fixed?

Also you can set this property `springfox.documentation.swagger.v2.use-model-v3=false` I your property file and it will use the old model generation.

**Comment by othellico** [comment]
Hi @dilipkrish .
I have this controller method:

```
    @ApiOperation(value = "Update a sheet.", nickname = "updateSheet")
    @PutMapping(value = "/{sheetId}", consumes = {SillogeIntegrationLayerApiRest.CURRENT_VERSION_MIME_TYPE})
    public Mono<SheetBean> updateSheet(ServerHttpRequest request,
                                       @ApiParam(name = "sheetId",
                                               value = "The identifier of the sheet.",
                                               example = "abcdefgh-abcd-abcd-abcd-0123456789ab",
                                               required = true)
                                       @PathVariable String sheetId,
                                       @RequestBody SheetBean sheet) {
        sheet.setId(sheetId);
        return callExecutor(request, requestContext -> updateSheetExecutor.exec(requestContext, sheet));
    }
```

The SheetBean is defined as:

```
@ApiModel("Sheet")
public class SheetBean {
...
}
```

In the swagger.json I find:

```
"put": {
...
				"parameters": [
					{
						"in": "body",
						"name": "sheet",
						"description": "sheet",
						"required": true,
						"schema": {
							"$ref": "#/definitions/SheetReq"
						}
					},
					{
						"name": "sheetId",
						"in": "path",
						"description": "The identifier of the sheet.",
						"required": true,
						"type": "string",
						"x-example": "abcdefgh-abcd-abcd-abcd-0123456789ab"
					},
...
				],
				"responses": {
					"200": {
						"description": "OK",
						"schema": {
							"$ref": "#/definitions/SheetRes"
						}
					},
...
```

This is just generated with springfox-core-3.0.0-20200708.040910-94.jar and relatives.
Thanks

Claudio

**Comment by othellico** [comment]
With the `springfox.documentation.swagger.v2.use-model-v3=false` property I got an ever worse situation.
The operation definition is the same with the bean named SheetReq and SheetRes:

```
"put": {
...
				"parameters": [
					{
						"in": "body",
						"name": "sheet",
						"description": "sheet",
						"required": true,
						"schema": {
							"$ref": "#/definitions/SheetReq"
						}
					},
					{
						"name": "sheetId",
						"in": "path",
						"description": "The identifier of the sheet.",
						"required": true,
						"type": "string",
						"x-example": "abcdefgh-abcd-abcd-abcd-0123456789ab"
					},
...
				],
				"responses": {
					"200": {
						"description": "OK",
						"schema": {
							"$ref": "#/definitions/SheetRes"
						}
					},
...
```

But the bean definitions are named Sheet and Sheet_1:

```
		"Sheet": {
			"type": "object",
			"properties": {
...

		"Sheet_1": {
			"type": "object",
			"properties": {
```

**Comment by dilipkrish** [comment]
@othellico thanks for the detailed response

> But the bean definitions are named Sheet and Sheet_1:

That is a bug, that needs to be fixed.

Im curious what is your `SheetReq` and `SheetRes`? Do they have different properties?

**Comment by othellico** [comment]
@dilipkrish 
SheetReq and SheetRes are not beans of mine. I have only the SheetBean (with `@ApiModel("Sheet")` annotation) that you can see in the above code. Only one bean in my code, two beans in swagger.
Thanks
Claudio

**Comment by dilipkrish** [comment]
@othellico I understand. I'm asking you for a couple of things...
1. Can you share what the `SheetBean` looks like
2. Can you share the full json definition of `SheetReq` and `SheetRes`

The reason you have SheetBean producing two model definitions is because they the request and response representations of the same bean are __different__.

**Comment by othellico** [comment]
No problem.

SheetBean:

```
@Setter
@Getter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@ApiModel("Sheet")
public class SheetBean {

    @ApiModelProperty(value = "The identifier of the sheet.", example = "abc")
    private String id;

    @JsonInclude(JsonInclude.Include.NON_NULL)
    @ApiModelProperty(value = "The folder in which the sheet is. Required for non protocol sheets.")
    @ToString.Include
    private FolderBean folder;

    @JsonInclude(JsonInclude.Include.NON_NULL)
    @ApiModelProperty(value = "The protocol registry in which to create the sheet. Required for protocol sheets.")
    @ToString.Include
    private ProtocolType protocol;

    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @ApiModelProperty(value = "The properties of the sheet.")
    @Builder.Default
    private List<PropertyBean> properties = new ArrayList<>();

    @JsonInclude(JsonInclude.Include.NON_NULL)
    @ApiModelProperty(value = "The ACL of the sheet.")
    private AclBean acl;

    @JsonInclude(JsonInclude.Include.NON_NULL)
    @ApiModelProperty(value = "The content (main document) of the sheet.")
    private ContentBean content;

    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @ApiModelProperty(value = "The attachments of the sheet.")
    @Builder.Default
    private List<ContentBean> attachments = new ArrayList<>();

    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @ApiModelProperty(value = "The classification items of the sheet.")
    @Builder.Default
    private List<SheetClassificationItemBean> classificationItems = new ArrayList<>();

    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @ApiModelProperty(value = "The annotations of the sheet.")
    @Builder.Default
    private List<AnnotationBean> annotations = new ArrayList<>();

    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @ApiModelProperty(value = "The email messages of the sheet.")
    private EmailMessageSetBean emailMessages;

}
```

Definitions:

```
		"SheetReq": {
			"type": "object",
			"properties": {
				"acl": {
					"description": "The ACL of the sheet.",
					"$ref": "#/definitions/ACLReq"
				},
				"annotations": {
					"type": "array",
					"description": "The annotations of the sheet.",
					"items": {
						"$ref": "#/definitions/Annotation"
					}
				},
				"attachments": {
					"type": "array",
					"description": "The attachments of the sheet.",
					"items": {
						"$ref": "#/definitions/Content"
					}
				},
				"classificationItems": {
					"type": "array",
					"description": "The classification items of the sheet.",
					"items": {
						"$ref": "#/definitions/SheetClassificationItem"
					}
				},
				"content": {
					"description": "The content (main document) of the sheet.",
					"$ref": "#/definitions/Content"
				},
				"emailMessages": {
					"description": "The email messages of the sheet.",
					"$ref": "#/definitions/EmailMessageSet"
				},
				"folder": {
					"description": "The folder in which the sheet is. Required for non protocol sheets.",
					"$ref": "#/definitions/Folder"
				},
				"id": {
					"type": "string",
					"example": "abc",
					"description": "The identifier of the sheet."
				},
				"properties": {
					"type": "array",
					"description": "The properties of the sheet.",
					"items": {
						"$ref": "#/definitions/Property"
					}
				},
				"protocol": {
					"type": "string",
					"description": "The protocol registry in which to create the sheet. Required for protocol sheets.",
					"enum": [
						"INBOUND",
						"INTERNAL",
						"OUTBOUND"
					]
				}
			},
			"title": "SheetReq"
		},
		"SheetRes": {
			"type": "object",
			"properties": {
				"acl": {
					"description": "The ACL of the sheet.",
					"$ref": "#/definitions/ACLRes"
				},
				"annotations": {
					"type": "array",
					"description": "The annotations of the sheet.",
					"items": {
						"$ref": "#/definitions/Annotation"
					}
				},
				"attachments": {
					"type": "array",
					"description": "The attachments of the sheet.",
					"items": {
						"$ref": "#/definitions/Content"
					}
				},
				"classificationItems": {
					"type": "array",
					"description": "The classification items of the sheet.",
					"items": {
						"$ref": "#/definitions/SheetClassificationItem"
					}
				},
				"content": {
					"description": "The content (main document) of the sheet.",
					"$ref": "#/definitions/Content"
				},
				"emailMessages": {
					"description": "The email messages of the sheet.",
					"$ref": "#/definitions/EmailMessageSet"
				},
				"folder": {
					"description": "The folder in which the sheet is. Required for non protocol sheets.",
					"$ref": "#/definitions/Folder"
				},
				"id": {
					"type": "string",
					"example": "abc",
					"description": "The identifier of the sheet."
				},
				"properties": {
					"type": "array",
					"description": "The properties of the sheet.",
					"items": {
						"$ref": "#/definitions/Property"
					}
				},
				"protocol": {
					"type": "string",
					"description": "The protocol registry in which to create the sheet. Required for protocol sheets.",
					"enum": [
						"INBOUND",
						"INTERNAL",
						"OUTBOUND"
					]
				}
			},
			"title": "SheetRes"
		},
```

They look equal.

**Comment by dilipkrish** [comment]
Seems like there is a difference in your `AclBean` between request and response, which in-turn makes the SheetBean different between request and response.

**Comment by othellico** [comment]
GOT IT!!! 
In AclBean there is a read-only attribute that makes it different from request to response!!!
Thank you very much!!!

But... now I've got another problem.
The order of the parameters has changed. Now the headers parameters are the last ones, not the first ones. And this changes the client parameters order.
Is there a way to fix it?

**Comment by dilipkrish** [comment]
@othellico parameter order is not typically guaranteed by open api. it currently uses the order the parameter was declared as the order to provide the principle of least surprise when rendering. You could create your own plugin however that reads your own custom annotation that provides a custom order and use the `RequestParameterBuilder#parameterIndex`to change the value.

Im going to close this issue as fixed. Feel free to re-open if you feel it hasn't been fixed or open a new one if its not related to enums.
