### ISSUE TITLE
404 while access the swagger UI

### ISSUE THREAD

**Issue by ashutoshnayanmishra** [springfox/springfox#3349]
<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-boot-starter</artifactId>
			<version>3.0.0-SNAPSHOT</version>
		</dependency>

While deploying i am getting warning  like 

2020-06-27 14:32:02.791 Apples-MacBook-Pro-7.local  WARN67287 --- [           main] d.s.r.o.OperationImplicitParameterReader :Unable to interpret the implicit parameter configuration with dataType: , dataTypeClass: class java.lang.Void
2020-06-27 14:32:02.807 Apples-MacBook-Pro-7.local  WARN67287 --- [           main] Validator                                :ERROR [ModelSpecification.spec] At least one type of specification is required
2020-06-27 14:32:02.809 Apples-MacBook-Pro-7.local  WARN67287 --- [           main] d.s.r.o.OperationImplicitParameterReader :Unable to interpret the implicit parameter configuration with dataType: , dataTypeClass: class java.lang.Void
2020-06-27 14:32:02.809 Apples-MacBook-Pro-7.local  WARN67287 --- [           main] Validator                                :ERROR [ModelSpecification.spec] At least one type of specification is required
2020-06-27 14:32:02.809 Apples-MacBook-Pro-7.local  WARN67287 --- [           main] d.s.r.o.OperationImplicitParameterReader :Unable to interpret the implicit parameter configuration with dataType: , dataTypeClass: class java.lang.Void
2020-06-27 14:32:02.809 Apples-MacBook-Pro-7.local  WARN67287 --- [           main] Validator                                :ERROR [ModelSpecification.spec] At least one type of specification is required
2020-06-27 14:32:03.229 Apples-MacBook-Pro-7.local  WARN67287 --- [           main] d.s.r.o.OperationImplicitParameterReader :Unable to interpret the implicit parameter configuration with dataType: , dataTypeClass: class java.lang.Void
2020-06-27 14:32:03.229 Apples-MacBook-Pro-7.

And while accessing the swagger link below error is coming.

org.springframework.web.server.ResponseStatusException: 404 NOT_FOUND
	at org.springframework.web.reactive.resource.ResourceWebHandler.lambda$handle$0(ResourceWebHandler.java:325) ~[spring-webflux-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44) [reactor-core-3.2.9.RELEASE.jar:3.2.9.RELEASE]
	at reactor.core.publisher.MonoLift.subscribe(MonoLift.java:45) [reactor-core-3.2.9.RELEASE.jar:3.2.9.RELEASE]
	at reactor.core.publisher.Mono.subscribe(Mono.java:3710) [reactor-core-3.2.9.RELEASE.jar:3.2.9.RELEASE]
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:75) [reactor-core-3.2.9.RELEASE.jar:3.2.9.RELEASE]
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onComplete(ScopePassingSpanSubscriber.java:112) [spring-cloud-sleuth-core-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onComplete(MonoFlatMap.java:174) [reactor-core-3.2.9.RELEASE.jar:3.2.9.RELEASE]
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onComplete(ScopePassingSpanSubscriber.java:112) [spring-cloud-sleuth-core-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at reactor.core.publisher.MonoNext$NextSubscriber.onComplete(MonoNext.java:96) [reactor-core-3.2.9.RELEASE.jar:3.2.9.RELEASE]
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onComplete(ScopePassingSpanSubscriber.java:112) [spring-cloud-sleuth-core-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:360) [reactor-core-3.2.9.RELEASE.jar:3.2.9.RELEASE]
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onComplete(FluxConcatMap.java:269) [reactor-core-3.2.9.RELEASE.jar:3.2.9.RELEASE]
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onComplete(ScopePassingSpanSubscriber.java:112) [spring-cloud-sleuth-core-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at reactor.core.publisher.FluxIterable$IterableSubscription.slowPath(FluxIterable.java:265) [reactor-core-3.2.9.RELEASE.jar:3.2.9.RELEASE]
	at reactor.core.publisher.FluxIterable$IterableSubscription.request(FluxIterable.java:201) [reactor-core-3.2.9.RELEASE.jar:3.2.9.RELEASE]
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.request(ScopePassingSpanSubscriber.java:79) [spring-cloud-sleuth-core-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onSubscribe(FluxConcatMap.java:229) [reactor-core-3.2.9.RELEASE.jar:3.2.9.RELEASE]
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onSubscribe(Sc

**Comment by NaccOll** [comment]
@ashutoshnayanmishra 
You can access /swagger-ui/index.html insteading of /swagger-ui.html due to springfox.boot.starter.autoconfigure.SwaggerUiWebMvcConfigurer#addResourceHandlers

**Comment by ashutoshnayanmishra** [comment]
Thanks @NaccOll 
it worked. 
I am getting the this warnings
2020-06-27 14:32:02.791 Apples-MacBook-Pro-7.local WARN67287 --- [ main] d.s.r.o.OperationImplicitParameterReader :Unable to interpret the implicit parameter configuration with dataType: , dataTypeClass: class java.lang.Void
2020-06-27 14:32:02.807 Apples-MacBook-Pro-7.local WARN67287 --- [ main] Validator :ERROR [ModelSpecification.spec] At least one type of specification is required
Am I missing something?

**Comment by dilipkrish** [comment]
@NaccOll Thank you for answering that @NaccOll. Yes reworked the swagger-ui so that it is more friendly to being auto configured and less buggy.

**Comment by ashutoshnayanmishra** [comment]
Thanks for replying.
But this warnings I am getting. Am I missing something?

2020-06-27 14:32:02.791 Apples-MacBook-Pro-7.local WARN67287 --- [ main] d.s.r.o.OperationImplicitParameterReader :Unable to interpret the implicit parameter configuration with dataType: , dataTypeClass: class java.lang.Void
2020-06-27 14:32:02.807 Apples-MacBook-Pro-7.local WARN67287 --- [ main] Validator :ERROR [ModelSpecification.spec] At least one type of specification is required

**Comment by dilipkrish** [comment]
Are you seeing what you expect in the API? Those are asserts to help iron out bugs.

**Comment by xiongjia** [comment]
We are using 3.0 snapshot and enabled webflux, start from  today's build both 'swagger-ui.html' and 'swagger-ui/index.html' cannot be accessed. (404  error) 

Any workarounds for springfox webflux?

**Comment by dilipkrish** [comment]
@xiongjia Are you using the `springfox-boot-starter` dependency? If not you should be. Remove explicit dependencies on the ...-swagger2, ..swagger-ui libraries and remove the `@Enable...` annotations.

**Comment by vpylypenko2** [comment]
I switched to springfox-boot-starter dependencies, but started to see 'java.lang.ClassNotFoundException: org.springframework.data.rest.core.config.RepositoryRestConfiguration' error. I do not use Spring Data Rest.

**Comment by vpylypenko2** [comment]
I temporary added dependency on Spring Data Rest to be able to proceed. Any advise how to resolve this issue?
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-rest</artifactId>
        </dependency>

**Comment by dilipkrish** [comment]
Hmmm that shouldnt be the case. The spring data rest configuration [shouldn't load if you dont use spring data rest](https://github.com/springfox/springfox/blob/master/springfox-data-rest/src/main/java/springfox/documentation/spring/data/rest/configuration/SpringDataRestConfiguration.java#L43). Also the [the demos](https://github.com/springfox/springfox-demos) don't require it to start up.

**Comment by atkawa7** [comment]
@dilipkrish I am having  a similar issue as well. I am failing to access 

http://localhost:8080/springfox/swagger-ui.html


```java
@Configuration
@EnableOpenApi
public class WebConfig implements WebMvcConfigurer {


  @Bean
  public Docket petApi() {
    return new Docket(DocumentationType.OAS_30)
        .groupName("full-petstore-api")
        .apiInfo(apiInfo())
        .select()
        .build();
  }

  private ApiInfo apiInfo() {
    return new ApiInfoBuilder()
        .title("Springfox petstore API")
        .description(
            "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum "
                + "has been the industry's standard dummy text ever since the 1500s, when an unknown printer "
                + "took a "
                + "galley of type and scrambled it to make a type specimen book. It has survived not only five "
                + "centuries, but also the leap into electronic typesetting, remaining essentially unchanged. "
                + "It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum "
                + "passages, and more recently with desktop publishing software like Aldus PageMaker including "
                + "versions of Lorem Ipsum.")
        .termsOfServiceUrl("http://springfox.io")
        .contact(new Contact("springfox", "", ""))
        .license("Apache License Version 2.0")
        .licenseUrl("https://github.com/springfox/springfox/blob/master/LICENSE")
        .version("2.0")
        .build();
  }
}

```

**Comment by atkawa7** [comment]
@dilipkrish Is there a simple open api demo?

**Comment by dilipkrish** [comment]
@atkawa7 [the demos](https://github.com/springfox/springfox-demos) the boot-webmvc and boot-webflux are as basic as they get.

**Comment by asuri3** [comment]
Hi,
In my case even after removing @EnableSwagger2WebFlux, it's not working. I am getting 404 from last 2 days.
```
@Configuration
@EnableSwagger2WebFlux
public class SwaggerConfiguration {

  private TypeResolver typeResolver = new TypeResolver();

  @Bean
  public Docket api() {
    return new Docket(DocumentationType.SWAGGER_2)
        .host("")
        .produces(Collections.singleton(MediaType.APPLICATION_JSON_VALUE))
```

**Comment by asuri3** [comment]
It works after adding

`  <dependency>
      <groupId>io.springfox</groupId>
      <artifactId>springfox-boot-starter</artifactId>
      <version>3.0.0-SNAPSHOT</version>
    </dependency>`

but earlier this dependency was not required. Is it mandatory to use this dependency now?

I was using springfox-swagger2, springfox-spring-webflux, springfox-swagger-ui, and springfox-schema and my swagger-ui was working fine.

**Comment by atkawa7** [comment]
Thanks @dilipkrish. Its working now

**Comment by dilipkrish** [comment]
@asuri3 If you're using a boot app. It is best to let the boot starter do all the configuration for you. Nothing is mandatory, its just sets up your project with the right settings.

**Comment by asuri3** [comment]
> @asuri3 If you're using a boot app. It is best to let the boot starter do all the configuration for you. Nothing is mandatory, its just sets up your project with the right settings. Also it simplifies your dependencies to one dependency

ok thanks @dilipkrish

**Comment by schrek1** [comment]
which repository using for obtain springfox-boot-starter, please?

**Comment by dilipkrish** [comment]
Please [see the docs](http://springfox.github.io/springfox/docs/snapshot/#dependencies)

**Comment by vpylypenko2** [comment]
@dilipkrish Going back to my comment about the following error "I switched to springfox-boot-starter dependencies, but started to see 'java.lang.ClassNotFoundException: org.springframework.data.rest.core.config.RepositoryRestConfiguration' error. I do not use Spring Data Rest.". I debugged it a bit and found BasePathAwareServicesProvider class which is annotated with Component, which instance of the class is created automatically. RepositoryRestConfiguration is autowired in constructor. This component needs to be conditional on Spring Data Rest

**Comment by vpylypenko2** [comment]
@dilipkrish The same issue exists for EntityServicesProvider class as well. It is annotated as Component

**Comment by dotw** [comment]
> @ashutoshnayanmishra
> You can access `/swagger-ui/index.html` insteading of `/swagger-ui.html` due to springfox.boot.starter.autoconfigure.SwaggerUiWebMvcConfigurer#addResourceHandlers

this works for me. this issue blocked me several days...

**Comment by dilipkrish** [comment]
@vpylypenko2 That is because its auto configured based on the existence of `@ConditionalOnClass(RepositoryRestConfiguration.class)` causing `SpringDataRestConfiguration` to light up. Open to ideas on how best to determine if the spring data rest support be auto configured.

**Comment by vpylypenko2** [comment]
@dilipkrish We need `@ConditionalOnClass(RepositoryRestConfiguration.class)` for `BasePathAwareServicesProvider` and `EntityServicesProvider` classes as well. Another alternative is to define bean creation for those two classes in `SpringDataRestConfiguration`

**Comment by dilipkrish** [comment]
I dont follow. The component scan should only happen when `SpringDataRestConfiguration` is active right?

**Comment by vpylypenko2** [comment]
@dilipkrish You are right. I debugged it a bit more and found `@ComponentScan(basePackages = {"springfox.documentation", ...` in our project code. The code was created long time. It needs to change. Thanks for the quick response and the hint

**Comment by cnidadavolu** [comment]
> It works after adding
> 
> > 
> 
> ```
>   <groupId>io.springfox</groupId>
>   <artifactId>springfox-boot-starter</artifactId>
>   <version>3.0.0-SNAPSHOT</version>
> </dependency>
> ```
> 
> but earlier this dependency was not required. Is it mandatory to use this dependency now?
> 
> I was using springfox-swagger2, springfox-spring-webflux, springfox-swagger-ui, and springfox-schema and my swagger-ui was working fine.

It worked for me using springfox-boot-starter and swagger-ui/index.html
