### ISSUE TITLE
springfox-boot-starter 3.0.0: java.lang.IllegalStateException: Model already registered with different name using 

### ISSUE THREAD

**Issue by Jojoooo1** [springfox/springfox#3389]
- [ ] What version of the library are you using? springfox-boot-starter: 3.0.0

What kind of issue is this?

 - [ ] Bug report. 
![1](https://user-images.githubusercontent.com/17641873/87421596-92bb8b80-c5ad-11ea-8b0c-4b0c8ab4d263.png)

Tried to migrate from springdoc-openapi-ui to springfox-boot-starter but unfortunately It seems that something is wrong. I did not add any file or configuration.

**Comment by dilipkrish** [comment]
Could you share your stacktrace _not as a screenshot_ but as text?

**Comment by Jojoooo1** [comment]
Sure

2020-07-14 08:55:02,537 ERROR [paketo,,,] 1679 --- [  restartedMain] d.s.w.p.DocumentationPluginsBootstrapper : Unable to scan documentation context default

java.lang.IllegalStateException: Model already registered with different name.
	at springfox.documentation.schema.TypeNameIndexingAdapter.checkTypeRegistration(TypeNameIndexingAdapter.java:55)
	at springfox.documentation.schema.TypeNameIndexingAdapter.registerUniqueType(TypeNameIndexingAdapter.java:82)
	at springfox.documentation.spring.web.scanners.ApiModelReader.mergeConditions(ApiModelReader.java:415)
	at springfox.documentation.spring.web.scanners.ApiModelReader.mergeModelBranch(ApiModelReader.java:255)
	at springfox.documentation.spring.web.scanners.ApiModelReader.lambda$mergeModelBranch$6(ApiModelReader.java:197)
	at java.base/java.util.Optional.orElseGet(Optional.java:369)
	at springfox.documentation.spring.web.scanners.ApiModelReader.mergeModelBranch(ApiModelReader.java:197)
	at springfox.documentation.spring.web.scanners.ApiModelReader.lambda$mergeModelBranch$6(ApiModelReader.java:197)
	at java.base/java.util.Optional.orElseGet(Optional.java:369)
	at springfox.documentation.spring.web.scanners.ApiModelReader.mergeModelBranch(ApiModelReader.java:197)
	at springfox.documentation.spring.web.scanners.ApiModelReader.lambda$read$2(ApiModelReader.java:145)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at springfox.documentation.spring.web.scanners.ApiModelReader.read(ApiModelReader.java:145)
	at springfox.documentation.spring.web.scanners.ApiListingScanner.scan(ApiListingScanner.java:154)
	at springfox.documentation.spring.web.scanners.ApiDocumentationScanner.scan(ApiDocumentationScanner.java:67)
	at springfox.documentation.spring.web.plugins.AbstractDocumentationPluginsBootstrapper.scanDocumentation(AbstractDocumentationPluginsBootstrapper.java:96)
	at springfox.documentation.spring.web.plugins.AbstractDocumentationPluginsBootstrapper.bootstrapDocumentationPlugins(AbstractDocumentationPluginsBootstrapper.java:82)
	at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.start(DocumentationPluginsBootstrapper.java:100)
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:182)
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:53)
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:360)
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:158)
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:122)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:913)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:570)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at br.com.paketo.pudo.Application.main(Application.java:16)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)

**Comment by Jojoooo1** [comment]
Yes sure, just updated the comment.

**Comment by dilipkrish** [comment]
Thank you!

**Comment by ffarnia** [comment]
I use spring boot ver2.x and this lib and i get the same error.
Any help?

**Comment by dilipkrish** [comment]
@MaksimOrlov any ideas?

**Comment by DennisGuo** [comment]
I have the save error.  I check all my `@ApiModel `, but there was nothing duplicate.

`java.lang.IllegalStateException: Model already registered with different name.
        at springfox.documentation.schema.TypeNameIndexingAdapter.checkTypeRegistration(TypeNameIndexingAdapter.java:55) ~[springfox-schema-3.0.0.jar!/:3.0.0]
        at springfox.documentation.schema.TypeNameIndexingAdapter.registerUniqueType(TypeNameIndexingAdapter.java:82) ~[springfox-schema-3.0.0.jar!/:3.0.0]
        at springfox.documentation.spring.web.scanners.ApiModelReader.mergeConditions(ApiModelReader.java:415) ~[springfox-spring-web-3.0.0.jar!/:3.0.0]
        at springfox.documentation.spring.web.scanners.ApiModelReader.mergeModelBranch(ApiModelReader.java:255) ~[springfox-spring-web-3.0.0.jar!/:3.0.0]
        at springfox.documentation.spring.web.scanners.ApiModelReader.lambda$mergeModelBranch$6(ApiModelReader.java:197) ~[springfox-spring-web-3.0.0.jar!/:3.0.0]
        at java.util.Optional.orElseGet(Optional.java:267) ~[na:1.8.0_112]
        at springfox.documentation.spring.web.scanners.ApiModelReader.mergeModelBranch(ApiModelReader.java:197) ~[springfox-spring-web-3.0.0.jar!/:3.0.0]
        at springfox.documentation.spring.web.scanners.ApiModelReader.lambda$mergeModelBranch$6(ApiModelReader.java:197) ~[springfox-spring-web-3.0.0.jar!/:3.0.0]
        at java.util.Optional.orElseGet(Optional.java:267) ~[na:1.8.0_112]
        at springfox.documentation.spring.web.scanners.ApiModelReader.mergeModelBranch(ApiModelReader.java:197) ~[springfox-spring-web-3.0.0.jar!/:3.0.0]
        at springfox.documentation.spring.web.scanners.ApiModelReader.lambda$mergeModelBranch$6(ApiModelReader.java:197) ~[springfox-spring-web-3.0.0.jar!/:3.0.0]
        at java.util.Optional.orElseGet(Optional.java:267) ~[na:1.8.0_112]
        at springfox.documentation.spring.web.scanners.ApiModelReader.mergeModelBranch(ApiModelReader.java:197) ~[springfox-spring-web-3.0.0.jar!/:3.0.0]
        at springfox.documentation.spring.web.scanners.ApiModelReader.lambda$read$2(ApiModelReader.java:145) ~[springfox-spring-web-3.0.0.jar!/:3.0.0]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[na:1.8.0_112]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[na:1.8.0_112]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[na:1.8.0_112]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_112]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_112]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[na:1.8.0_112]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[na:1.8.0_112]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_112]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[na:1.8.0_112]
        at springfox.documentation.spring.web.scanners.ApiModelReader.read(ApiModelReader.java:145) ~[springfox-spring-web-3.0.0.jar!/:3.0.0]
        at springfox.documentation.spring.web.scanners.ApiListingScanner.scan(ApiListingScanner.java:154) ~[springfox-spring-web-3.0.0.jar!/:3.0.0]
        at springfox.documentation.spring.web.scanners.ApiDocumentationScanner.scan(ApiDocumentationScanner.java:67) ~[springfox-spring-web-3.0.0.jar!/:3.0.0]
        at springfox.documentation.spring.web.plugins.AbstractDocumentationPluginsBootstrapper.scanDocumentation(AbstractDocumentationPluginsBootstrapper.java:96) [springfox-spring-web-3.0.0.jar!/:3.0.0]
        at springfox.documentation.spring.web.plugins.AbstractDocumentationPluginsBootstrapper.bootstrapDocumentationPlugins(AbstractDocumentationPluginsBootstrapper.java:82) [springfox-spring-web-3.0.0.jar!/:3.0.0]
        at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.start(DocumentationPluginsBootstrapper.java:100) [springfox-spring-web-3.0.0.jar!/:3.0.0]
        at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:182) [spring-context-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
        at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:53) [spring-context-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
        at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:360) [spring-context-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
        at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:158) [spring-context-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
        at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:122) [spring-context-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:895) [spring-context-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:162) [spring-boot-2.2.10.RELEASE.jar!/:2.2.10.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:554) [spring-context-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) [spring-boot-2.2.10.RELEASE.jar!/:2.2.10.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) [spring-boot-2.2.10.RELEASE.jar!/:2.2.10.RELEASE]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.2.10.RELEASE.jar!/:2.2.10.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-2.2.10.RELEASE.jar!/:2.2.10.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.2.10.RELEASE.jar!/:2.2.10.RELEASE]`

**Comment by jenni** [comment]
+1

**Comment by Yera** [comment]
+1, the same happening to me, using with Spring Data Rest

**Comment by Domingos-Masta** [comment]
+1

**Comment by Delirante** [comment]
+1

**Comment by DerekVonk** [comment]
+1, Spring Data Rest, Spring boot version 2.4.5

**Comment by kchvilyov** [comment]
+1
What version of the library are you using? springfox-boot-starter: 3.0.0
ext {
    mapstructVersion = "1.4.2.Final"
    lombokVersion = "1.18.20"
    lombokMapstructBindingVersion = "0.2.0"
    jjwtVersion="0.11.2"
}
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-mail'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    compile 'org.springframework.boot:spring-boot-starter-log4j2'

    implementation "io.springfox:springfox-boot-starter:3.0.0"

    implementation "org.mapstruct:mapstruct:${mapstructVersion}", "org.projectlombok:lombok:${lombokVersion}"

What kind of issue is this?

Bug report.
d.s.w.p.DocumentationPluginsBootstrapper : Unable to scan documentation context default

java.lang.IllegalStateException: Model already registered with different name.
	at springfox.documentation.schema.TypeNameIndexingAdapter.checkTypeRegistration(TypeNameIndexingAdapter.java:55) ~[springfox-schema-3.0.0.jar:3.0.0]
	at springfox.documentation.schema.TypeNameIndexingAdapter.registerUniqueType(TypeNameIndexingAdapter.java:82) ~[springfox-schema-3.0.0.jar:3.0.0]
	at springfox.documentation.spring.web.scanners.ApiModelReader.mergeConditions(ApiModelReader.java:415) ~[springfox-spring-web-3.0.0.jar:3.0.0]
	at springfox.documentation.spring.web.scanners.ApiModelReader.mergeModelBranch(ApiModelReader.java:255) ~[springfox-spring-web-3.0.0.jar:3.0.0]
	at springfox.documentation.spring.web.scanners.ApiModelReader.lambda$mergeModelBranch$6(ApiModelReader.java:197) ~[springfox-spring-web-3.0.0.jar:3.0.0]
	at java.util.Optional.orElseGet(Optional.java:369) ~[?:?]
	at springfox.documentation.spring.web.scanners.ApiModelReader.mergeModelBranch(ApiModelReader.java:197) ~[springfox-spring-web-3.0.0.jar:3.0.0]
	at springfox.documentation.spring.web.scanners.ApiModelReader.lambda$mergeModelBranch$6(ApiModelReader.java:197) ~[springfox-spring-web-3.0.0.jar:3.0.0]
	at java.util.Optional.orElseGet(Optional.java:369) ~[?:?]
	at springfox.documentation.spring.web.scanners.ApiModelReader.mergeModelBranch(ApiModelReader.java:197) ~[springfox-spring-web-3.0.0.jar:3.0.0]
	at springfox.documentation.spring.web.scanners.ApiModelReader.lambda$mergeModelBranch$6(ApiModelReader.java:197) ~[springfox-spring-web-3.0.0.jar:3.0.0]
	at java.util.Optional.orElseGet(Optional.java:369) ~[?:?]
	at springfox.documentation.spring.web.scanners.ApiModelReader.mergeModelBranch(ApiModelReader.java:197) ~[springfox-spring-web-3.0.0.jar:3.0.0]
	at springfox.documentation.spring.web.scanners.ApiModelReader.lambda$mergeModelBranch$6(ApiModelReader.java:197) ~[springfox-spring-web-3.0.0.jar:3.0.0]
	at java.util.Optional.orElseGet(Optional.java:369) ~[?:?]
	at springfox.documentation.spring.web.scanners.ApiModelReader.mergeModelBranch(ApiModelReader.java:197) ~[springfox-spring-web-3.0.0.jar:3.0.0]
	at springfox.documentation.spring.web.scanners.ApiModelReader.lambda$mergeModelBranch$6(ApiModelReader.java:197) ~[springfox-spring-web-3.0.0.jar:3.0.0]
	at java.util.Optional.orElseGet(Optional.java:369) ~[?:?]
	at springfox.documentation.spring.web.scanners.ApiModelReader.mergeModelBranch(ApiModelReader.java:197) ~[springfox-spring-web-3.0.0.jar:3.0.0]
	at springfox.documentation.spring.web.scanners.ApiModelReader.lambda$read$2(ApiModelReader.java:145) ~[springfox-spring-web-3.0.0.jar:3.0.0]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[?:?]
	at springfox.documentation.spring.web.scanners.ApiModelReader.read(ApiModelReader.java:145) ~[springfox-spring-web-3.0.0.jar:3.0.0]
	at springfox.documentation.spring.web.scanners.ApiListingScanner.scan(ApiListingScanner.java:154) ~[springfox-spring-web-3.0.0.jar:3.0.0]
	at springfox.documentation.spring.web.scanners.ApiDocumentationScanner.scan(ApiDocumentationScanner.java:67) ~[springfox-spring-web-3.0.0.jar:3.0.0]
	at springfox.documentation.spring.web.plugins.AbstractDocumentationPluginsBootstrapper.scanDocumentation(AbstractDocumentationPluginsBootstrapper.java:96) ~[springfox-spring-web-3.0.0.jar:3.0.0]
	at springfox.documentation.spring.web.plugins.AbstractDocumentationPluginsBootstrapper.bootstrapDocumentationPlugins(AbstractDocumentationPluginsBootstrapper.java:82) ~[springfox-spring-web-3.0.0.jar:3.0.0]
	at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.start(DocumentationPluginsBootstrapper.java:100) ~[springfox-spring-web-3.0.0.jar:3.0.0]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178) ~[spring-context-5.3.7.jar:5.3.7]
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:54) ~[spring-context-5.3.7.jar:5.3.7]
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:356) ~[spring-context-5.3.7.jar:5.3.7]
	at java.lang.Iterable.forEach(Iterable.java:75) [?:?]
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:155) [spring-context-5.3.7.jar:5.3.7]
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:123) [spring-context-5.3.7.jar:5.3.7]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:935) [spring-context-5.3.7.jar:5.3.7]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:586) [spring-context-5.3.7.jar:5.3.7]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) [spring-boot-2.5.0.jar:2.5.0]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758) [spring-boot-2.5.0.jar:2.5.0]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:438) [spring-boot-2.5.0.jar:2.5.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:337) [spring-boot-2.5.0.jar:2.5.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1336) [spring-boot-2.5.0.jar:2.5.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1325) [spring-boot-2.5.0.jar:2.5.0]

**Comment by kchvilyov** [comment]
@MaksimOrlov @dilipkrish
Please clarify about your swagger product:
What should we do with our applications the year!!!! while you are fixing this swagger  bug?..
Do we have to downgrade the version to ...?
or don't use the swagger at all?..

**Comment by kchvilyov** [comment]
Hi @Jojoooo1 @ffarnia @DennisGuo @Yera @jenni @Domingos-Masta @DerekVonk @Delirante .
Have you fixed or avoided this bug?
If yes please share your decision to me or us.

**Comment by cagriertek1** [comment]
+1, the same happening

Any solution ideas?

**Comment by kchvilyov** [comment]
I have temporary avoided the problem by minimization of the count of the objects returning by controllers.
Now my PUT, POST and DELETE type methods return void.

**Comment by kchvilyov** [comment]
I have more ideas how to avoid the problem: 
2. to replace database entities to DTO in the endpoints return.
3. to minimize relations between DTOs returned by endpoints.
But I have not checked it yet.

**Comment by Delirante** [comment]
@kchvilyov, I have already tried that. You have to change relations very drastically to make it work. This is not suitable solution. 
Now I am using springfox v. 2.9.2 instead and i have manually fixed easier bug in this version.

**Comment by kchvilyov** [comment]
Thank you @Delirante !
Could you give me/us working springfox v. 2.9.2 config parts?
Preferably for Gradle Build Tool if possible :)

**Comment by kchvilyov** [comment]
@Delirante, I have alredy downgraded Springfox version by:
    compile "io.springfox:springfox-swagger2:2.9.2"
    compile "io.springfox:springfox-swagger-ui:2.9.2"
instead of:
    implementation "io.springfox:springfox-boot-starter:3.0.0"
So my last question is not actual.

**Comment by Yera** [comment]
i used openApi instead for now, also uses swagger ui

springdoc-openapi-ui: 1.6.3
springdoc-openapi-data-rest: 1.6.3

**Comment by M4jor-Tom** [comment]
+1, same issue

**Comment by hakanozerden** [comment]
+1

**Comment by gantispam** [comment]
+1

Exception throw after add new child inherance on hibernate's entity (Single table)

**Comment by alessiojr** [comment]
I isolated one more occurrence of the error.
occurs when we have a HashMap with different internal types

    public ResponseEntity<HashMap<String, List<RankSkill>>> get....() {
    public ResponseEntity<HashMap<Skill, Integer>> get..........(

**Comment by chengda** [comment]
+1

**Comment by chengda** [comment]
A temporary method to avoid this issue :  Add an annotation @ApiModelProperty(hidden = true) on the recursive field of the entity class.

**Comment by redguardofchina** [comment]
https://github.com/springfox/springfox.git

springfox-schema/src/main/java/springfox/documentation/schema/TypeNameIndexingAdapter.java
rowNum: 50-60

改了源码

    private boolean checkTypeRegistration(String typeName, String typeId) {
        return this.knownNames.containsKey(typeId);
    }

然后替换Maven

        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-schema</artifactId>
            <version>3.0.1-SNAPSHOT</version>
            <scope>system</scope>
            <systemPath>${basedir}/src/main/resources/libs/springfox-schema-3.0.1-SNAPSHOT.jar</systemPath>
        </dependency>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    
                    <includeSystemScope>true</includeSystemScope>
                </configuration>
            </plugin>
        </plugins>
    </build>

**Comment by TYMELAPSE** [comment]
Using:
Spring Boot 2.5.5
Springfox oas 3.0.0
Springfox Swagger2 3.0.0
Springfox Bean Validators 3.0.0

Error starts happening when I make my DTOs implement an interface with atleast one method implementation requirement.
