### ISSUE TITLE
HttpAuthenticationScheme - exception when name not given

### ISSUE THREAD

**Issue by kdebski85** [springfox/springfox#3424]
I am using SpringFox 3.0.0.

I encountered an exception when swagger-ui tried to call /v3/api-docs.
After some time I found out that the reason is that I need to provide the name of the security scheme with `new HttpAuthenticationBuilder().name("Authorization").scheme("Bearer").build();`

SpringFox should throw better exception if required element is missing.

**Exception:**

```
java.lang.RuntimeException: Could not write JSON
        at springfox.documentation.spring.web.json.JsonSerializer.toJson(JsonSerializer.java:40) ~[springfox-spring-web-3.0.0.jar:3.0.0]
        at springfox.documentation.oas.web.OpenApiControllerWebMvc.getDocumentation(OpenApiControllerWebMvc.java:95) ~[springfox-oas-3.0.0.jar:3.0.0]
(...)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Null key for a Map not allowed in JSON (use a converting NullKeySerializer?) (through reference chain: io.swagger.v3.oas.models.OpenAPI["components"]->io.swagger.v3.oas.models.Components["securitySchemes"]->java.util.HashMap["null"])
        at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:288) ~[jackson-databind-2.11.0.jar:2.11.0]
        at com.fasterxml.jackson.databind.SerializerProvider.mappingException(SerializerProvider.java:1337) ~[jackson-databind-2.11.0.jar:2.11.0]
        at com.fasterxml.jackson.databind.SerializerProvider.reportMappingProblem(SerializerProvider.java:1231) ~[jackson-databind-2.11.0.jar:2.11.0]
        at com.fasterxml.jackson.databind.ser.impl.FailingSerializer.serialize(FailingSerializer.java:35) ~[jackson-databind-2.11.0.jar:2.11.0]
```

**My configuration:**

```
@Configuration
public class SwaggerConfiguration {

    @Bean
    public Docket api () {
        return new Docket(DocumentationType.OAS_30)
                .select()
                .apis(RequestHandlerSelectors.any())
                .paths(PathSelectors.regex("/api.*"))
                .build()
                .securitySchemes(singletonList(securityScheme()))
                .securityContexts(singletonList(securityContext()));
    }

    private SecurityScheme securityScheme() {
        return new HttpAuthenticationBuilder().scheme("Bearer").build(); //name not set
    }

    private SecurityContext securityContext() {
        return SecurityContext.builder()
                .securityReferences(securityReferences())
                .build();
    }

    private List<SecurityReference> securityReferences() {
        return singletonList(
                new SecurityReference("Authorization", new AuthorizationScope[] {new AuthorizationScope("global", "global")}));
    }

}
```

**Proposed solution:**
If name and type are always required, null-checks should be added in constructor of springfox.documentation.service.SecurityScheme abstract class.

```
  public SecurityScheme(
      String name,
      String type,
      String description,
      List<VendorExtension> extensions) {
    Objects.requireNonNull(name , "Security scheme name is required");
    Objects.requireNonNull(type, "Security scheme type is required");

    this.name = name;
    this.type = type;
    this.description = description;
    this.extensions.addAll(extensions);
  }
```

**Comment by dilipkrish** [comment]
I agree, but have you looked at using the [starting builders](https://github.com/springfox/springfox/blob/861764c7823e51b0805e554ccfda0361b3e3bd7e/springfox-core/src/main/java/springfox/documentation/service/HttpAuthenticationScheme.java#L8-L11) that are already available?

**Comment by dilipkrish** [comment]
Also do you think you could submit a PR. Would be awesome!

**Comment by kdebski85** [comment]
Starting builders do not set 'name' parameter.
If somebody tries `HttpAuthenticationScheme.JWT_BEARER_BUILDER.build()`, `JsonMappingException` will be thrown on GET.
Name still needs to be set:
`HttpAuthenticationScheme.JWT_BEARER_BUILDER.name("token").build()`

I can try to prepare PR next week (no time right now for it, sorry).

**Comment by dilipkrish** [comment]
Starting builders are exactly what they mean. It sets the right defaults leaving the rest to the consumers ie name etc.

**Comment by okysuryadi** [comment]
hello @dilipkrish, why does DocumentationType.SWAGGER_2 not support HttpAuthenticationScheme class? so, now I am using ApiKey class, will this case be fixed in version 3.0.1 as well?

**Comment by Typraeurion** [comment]
1. SpringFox needs better Javadoc documentation.
2. https://springfox.github.io/springfox/javadoc/current/springfox/documentation/builders/HttpAuthenticationBuilder.html doesn’t show any “starting” builders, nor are any visible in the class (in version 3.0.0).
