### ISSUE TITLE
What version of spring data rest should I use with 3.0?

### ISSUE THREAD

**Issue by gigecogary** [springfox/springfox#3444]
I migrated over to 3.0 from snapshot and now the whole project broke. 

I use both SDR and Springfox. Which version of SDR should I use with springfox 3.0?

**Comment by dilipkrish** [comment]
You should use whatever version of SDR is right for you. Keep in mind that 3.0.0 works with spring 5.2+ and boot 2.2+. I believe you should use a version of SDR that's compatible with that. Also following semantic versioning, it's expected to break, however some effort has been taken to ensure it is as compatible as possible. 

If that's not your spring dependency range then you should switch back to 2.9.2. 

With that said, what exactly do you mean when u say the project is broke? If you provide details of the versions you're using and the exactly exception may be I can help you fix it?

**Comment by gigecogary** [comment]
Thanks so much for your prompt response!

Without changing anything in my code base, I opened my project (after 1 month without running it) and now for some reason it started giving this exception on booting the application. 

Again, I haven't changed anything. I suspect the pom.xml pulled in some updated libraries and maybe that broke something?

`Caused by: java.io.FileNotFoundException: class path resource [springfox/documentation/spi/service/ResponseBuilderPlugin.class] cannot be opened because it does not exist
	at org.springframework.core.io.ClassPathResource.getInputStream(ClassPathResource.java:180) ~[spring-core-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.core.type.classreading.SimpleMetadataReader.<init>(SimpleMetadataReader.java:51) ~[spring-core-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:103) ~[spring-core-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.boot.type.classreading.ConcurrentReferenceCachingMetadataReaderFactory.createMetadataReader(ConcurrentReferenceCachingMetadataReaderFactory.java:86) ~[spring-boot-2.1.9.RELEASE.jar:2.1.9.RELEASE]
	at org.springframework.boot.type.classreading.ConcurrentReferenceCachingMetadataReaderFactory.getMetadataReader(ConcurrentReferenceCachingMetadataReaderFactory.java:73) ~[spring-boot-2.1.9.RELEASE.jar:2.1.9.RELEASE]
	at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:81) ~[spring-core-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassParser.asSourceClass(ConfigurationClassParser.java:682) ~[spring-context-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassParser$SourceClass.getInterfaces(ConfigurationClassParser.java:1008) ~[spring-context-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassParser.processInterfaces(ConfigurationClassParser.java:375) ~[spring-context-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:323) ~[spring-context-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:242) ~[spring-context-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:191) ~[spring-context-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:295) ~[spring-context-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:242) ~[spring-context-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassParser.processImports(ConfigurationClassParser.java:586) ~[spring-context-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	... 23 common frames omitted`

**Comment by dilipkrish** [comment]
Between the snapshot and the release things have changed. Try following the migration instructions at http://springfox.io from the snapshot especially regarding the dependencies. Ideally you should have a dependency on springFox-boot-starter and it should auto configure itself if you're using a boot app. You should also remove any `@Enable...` annotations.

**Comment by gigecogary** [comment]
I already followed all the steps, can you let me know what versions of spring boot, spring data, spring data rest, spring hateoas will work with springfox 3.0?

**Comment by dilipkrish** [comment]
Its in the [release notes](https://github.com/springfox/springfox/releases/tag/3.0.0). So as regards HATEOAS and spring data rest, you should have good success if you're using springboot 2.2+ and the starters that come with it.
