### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by sgri** [springfox/springfox#3482]
When using version 3.0.1-SNAPSHOT, its git hash is c459ac5cbb82cde4982a5a49df4b1715bc990fa8 I got the following error when starting my web application

> Model already registered with different name

The issue is in line springfox.documentation.schema.TypeNameIndexingAdapter#checkTypeRegistration, line 50
if (knownNames.containsKey(typeId)) {
      if (!knownNames.get(typeId).equals(typeName)) {
        LOGGER.debug("Rewriting type {} with model id: {} is not allowed, because it is already registered",
                 typeName,
                 typeId);
        throw new IllegalStateException("Model already registered with different name.");
      } 

I have debugged the code and revealed that the value of typeName is "Job" when  knownNames.get(typeId) evaluates to "Job_1". "Job" is a re-usable class which appears in multiple REST functions as return value like

List<Job> allJobs();
Job getJob(int id);

Job has  a field of User type  which is also used in multiple REST controllers.

Seems when scanning REST controllers springfox assigns different names to the same entity.

**Comment by dilipkrish** [comment]
This possibly a bug, thanks for reporting.

**Comment by babybabyCloud** [comment]
I think the main problem is here.
```java
private boolean checkTypeRegistration(
      String typeName,
      String typeId) {
    if (knownNames.containsKey(typeId)) {
      if (!knownNames.get(typeId).equals(typeName)) {
        LOGGER.debug("Rewriting type {} with model id: {} is not allowed, because it is already registered",
                 typeName,
                 typeId);
        throw new IllegalStateException("Model already registered with different name.");
      } else {
        return true;
      }
    }

    return false;
  }
  @Override
  public void registerUniqueType(
      String typeName,
      String typeId) {
    if (checkTypeRegistration(
        typeName,
        typeId)) {
      return;
    }
    Integer nameIndex = 0;
    String tempName = typeName;
    while (knownNames.values().contains(tempName)) {
      ++nameIndex;
      tempName = new StringBuilder(typeName)
          .append("_")
          .append(nameIndex).
          toString();
    }
    knownNames.put(
        typeId,
        tempName);
  }
```
In mehtod  checkTypeRegistration, it uses the key to check.
And the in the while condition, uses the value to judge the suffix in springfox.documentation.schema.TypeNameIndexingAdapter.java

**Comment by rubensitbon** [comment]
Hello ! 

I have the same issue on my project and I came to the same conclusion as @babybabyCloud 

Have you found a way to ignore the model that is breaking the start up ?

Best Regards,

**Comment by jenni** [comment]
+1

**Comment by jenni** [comment]
+1

**Comment by lmcdubo** [comment]
Getting the same issue after upgrading from 2.9.2

java.lang.IllegalStateException: Model already registered with different name.
	at springfox.documentation.schema.TypeNameIndexingAdapter.checkTypeRegistration(TypeNameIndexingAdapter.java:55)
	at springfox.documentation.schema.TypeNameIndexingAdapter.registerUniqueType(TypeNameIndexingAdapter.java:82)
	at springfox.documentation.spring.web.scanners.ApiModelReader.mergeConditions(ApiModelReader.java:415)
	at springfox.documentation.spring.web.scanners.ApiModelReader.mergeModelBranch(ApiModelReader.java:255)
	at springfox.documentation.spring.web.scanners.ApiModelReader.lambda$read$2(ApiModelReader.java:145)
...

any updates?

**Comment by Delirante** [comment]
+1

**Comment by XpamAmAdEuS** [comment]
+1

**Comment by skylinehyc** [comment]
+1

**Comment by kchvilyov** [comment]
+1
Hi all!
Have you fixed or avoided this bug?
If yes please share your decision to me or us.

**Comment by Blauspecht** [comment]
+1
Hello, I just wanted to let you guys know I discovered a workaround: For me that bug happened with a class named AdresseDto, I renamed the file and class to ZAdresseDto and then it worked. I'm still not sure why and if it will work for others aswell.

I experimented a bit more: 
In the folder where the AdressDto is located are a few other files: 

![Unbenannt](https://user-images.githubusercontent.com/34535585/130083242-3c84a277-bccf-4b36-897b-73211b46f49e.png)

> When renaming AdresseDto to BAdresseDto the issue still happens.
> When renaming AdresseDto to ImaaAdresseDto, to get it alphabetically between ImageLocationDto and ImportDto, the issue still remains.
> When renaming AdresseDto to ImrAdresseDto to get it sorted after ImportDto the bug doesn't happen.

This suggested it had something to do with ImportDto and where this file is sorted inside the folder. Maybe that changes injection/inspection order? No idea..
> When renaming the ImportDto to AaImportDto to get it to the first position another bug happend for me:

> java.lang.IllegalStateException: Ambiguous models equality when conditions is empty.
>	at springfox.documentation.spring.web.scanners.ApiModelReader.checkCondition(ApiModelReader.java:618) ~[springfox-spring-web-3.0.0.jar:3.0.0]
>	at springfox.documentation.spring.web.scanners.ApiModelReader.mergeConditions(ApiModelReader.java:385) ~[springfox-spring-web-3.0.0.jar:3.0.0]
>	at springfox.documentation.spring.web.scanners.ApiModelReader.mergeModelBranch(ApiModelReader.java:255) ~[springfox-spring-web-3.0.0.jar:3.0.0]
>	at springfox.documentation.spring.web.scanners.ApiModelReader.lambda$read$2(ApiModelReader.java:145) ~[springfox-spring-web-3.0.0.jar:3.0.0]

Haven't found any solution for that error too, the only suggested solutions were to downgrade to v2.9.2.
So the order of the files is somehow important, triggeres different errors on different orders but not sure how or why. 
I should mention AdresseDto has a field FooDto, and FooDto as a field with a list of AdresseDto's, so theres a circular dependency. 

Currently I have renamed AdresseDto to ZAdresseDto as a workaround. It works as expected but it isn't a viable solution to alter my code that way just to get swagger to run without issues. Hope for a fix soon, otherwise I will need to switch to a different api-documentation tool.

**Comment by lianmengfan** [comment]
hi, Has this problem been solved?

**Comment by kchvilyov** [comment]
Not fixed.
I downgraded to v2.9.2.

**Comment by hakanozerden** [comment]
+1
