### ISSUE TITLE
cannot load api definition: nullpointerexception

### ISSUE THREAD

**Issue by faenschi** [springfox/springfox#3545]
I upgraded from version 2.9.2 to version 3.0.0 in our spring boot project. 

the following dependencies are used 

` <dependency>
                <groupId>io.springfox</groupId>
                <artifactId>springfox-boot-starter</artifactId>
                <version>3.0.0</version>
            </dependency>
            <dependency>
                <groupId>io.springfox</groupId>
                <artifactId>springfox-swagger-ui</artifactId>
                <version>3.0.0</version>
            </dependency>
`
first when i startup my application the following warnings occur:
`
2020-09-09 08:44:10.544  WARN 13912 --- [           main] d.s.r.o.OperationImplicitParameterReader : Unable to interpret the implicit parameter configuration with dataType: , dataTypeClass: class java.lang.Void
2020-09-09 08:44:10.546  WARN 13912 --- [           main] d.s.r.o.OperationImplicitParameterReader : Unable to interpret the implicit parameter configuration with dataType: , dataTypeClass: class java.lang.Void
2020-09-09 08:44:10.551  WARN 13912 --- [           main] d.s.r.o.OperationImplicitParameterReader : Unable to interpret the implicit parameter configuration with dataType: , dataTypeClass: class java.lang.Void
2020-09-09 08:44:10.565  WARN 13912 --- [           main] d.s.r.o.OperationImplicitParameterReader : Unable to interpret the implicit parameter configuration with dataType: , dataTypeClass: class java.lang.Void
2020-09-09 08:44:10.565  WARN 13912 --- [           main] d.s.r.o.OperationImplicitParameterReader : Unable to interpret the implicit parameter configuration with dataType: , dataTypeClass: class java.lang.Void
2020-09-09 08:44:10.569  WARN 13912 --- [           main] d.s.r.o.OperationImplicitParameterReader : Unable to interpret the implicit parameter configuration with dataType: , dataTypeClass: class java.lang.Void
`

and when I try to access the ui at http://localhost:8080/swagger-ui/index.html I see a nullpointer:

java.lang.NullPointerException: null
	at springfox.documentation.swagger2.mappers.RequestParameterMapper.bodyParameter(RequestParameterMapper.java:264) ~[springfox-swagger2-3.0.0.jar:3.0.0]
	at springfox.documentation.swagger2.mappers.RequestParameterMapper.mapParameter(RequestParameterMapper.java:149) ~[springfox-swagger2-3.0.0.jar:3.0.0]
	at springfox.documentation.swagger2.mappers.ServiceModelToSwagger2Mapper.beforeMappingOperations(ServiceModelToSwagger2Mapper.java:125) ~[springfox-swagger2-3.0.0.jar:3.0.0]
	at springfox.documentation.swagger2.mappers.ServiceModelToSwagger2MapperImpl.mapOperation(ServiceModelToSwagger2MapperImpl.java:109) ~[springfox-swagger2-3.0.0.jar:3.0.0]
	at springfox.documentation.swagger2.mappers.ServiceModelToSwagger2Mapper.mapOperations(ServiceModelToSwagger2Mapper.java:270) ~[springfox-swagger2-3.0.0.jar:3.0.0]
	at springfox.documentation.swagger2.mappers.ServiceModelToSwagger2Mapper.lambda$mapApiListings$2(ServiceModelToSwagger2Mapper.java:258) ~[springfox-swagger2-3.0.0.jar:3.0.0]`
`
i debugged through the source code and it may be a problem with my pageable api documentation. The NPE happens here:
RequestParameterMapper.java Linke 264:
`
 parameter.setIn(source.getIn().getIn());
`

source.getIn() is null in my case, and i see that it happens with the pageable documentation:
`@ApiImplicitParam(name = "pageable", value = "pageable object")
`
is there a way to fix this?

**Comment by zruchala** [comment]
The issue is reproducible only for /v2/docs version (v3 works fine) and the culprit is the missing _paramType_ attribute 
Check this out:
@ApiImplicitParam(name = "pageable", value = "pageable object", paramType = "query")
