### ISSUE TITLE
NullPointer exception on mapModel 

### ISSUE THREAD

**Issue by HuppiFluppi** [springfox/springfox#3557]
What version of the library are you using?  -> 3.0.0
What kind of issue is this? -> Bug, Regression

When browsing v3/api-docs?group=api I get a Nullpointer Exception in SchemaMapper.java line 97. It seems like the mapFrom function returns null.

```
java.lang.NullPointerException: null
	at springfox.documentation.oas.mappers.SchemaMapper.model(SchemaMapper.java:97) ~[springfox-oas-3.0.0.jar:3.0.0]
	at springfox.documentation.oas.mappers.SchemaMapper.mapModel(SchemaMapper.java:85) ~[springfox-oas-3.0.0.jar:3.0.0]
	at springfox.documentation.oas.mappers.ServiceModelToOpenApiMapperImpl.fromRepresentation(ServiceModelToOpenApiMapperImpl.java:187) ~[springfox-oas-3.0.0.jar:3.0.0]
	at springfox.documentation.oas.mappers.ServiceModelToOpenApiMapper.map(ServiceModelToOpenApiMapper.java:216) ~[springfox-oas-3.0.0.jar:3.0.0]
	at springfox.documentation.oas.mappers.ServiceModelToOpenApiMapperImpl.mapOperation(ServiceModelToOpenApiMapperImpl.java:113) ~[springfox-oas-3.0.0.jar:3.0.0]
	at springfox.documentation.oas.mappers.ServiceModelToOpenApiMapper.mapOperations(ServiceModelToOpenApiMapper.java:283) ~[springfox-oas-3.0.0.jar:3.0.0]
	at springfox.documentation.oas.mappers.ServiceModelToOpenApiMapper.lambda$mapPaths$4(ServiceModelToOpenApiMapper.java:264) ~[springfox-oas-3.0.0.jar:3.0.0]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658) ~[?:?]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274) ~[?:?]
	at java.util.TreeMap$ValueSpliterator.forEachRemaining(TreeMap.java:2890) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEachOrdered(ReferencePipeline.java:502) ~[?:?]
	at springfox.documentation.oas.mappers.ServiceModelToOpenApiMapper.mapPaths(ServiceModelToOpenApiMapper.java:260) ~[springfox-oas-3.0.0.jar:3.0.0]
	at springfox.documentation.oas.mappers.ServiceModelToOpenApiMapperImpl.mapDocumentation(ServiceModelToOpenApiMapperImpl.java:83) ~[springfox-oas-3.0.0.jar:3.0.0]
	at springfox.documentation.oas.web.OpenApiControllerWebMvc.getDocumentation(OpenApiControllerWebMvc.java:88) ~[springfox-oas-3.0.0.jar:3.0.0]
```

Variables at that time:
source=ModelSpecification[scalar=null, compound=null, collection=null, map=null, reference=ReferenceModelSpecification{modelKey=ModelKey{qualifiedModelName=ModelName{namespace='', name='null'}, viewDiscriminator=null, validationGroupDiscriminators=[], isResponse=true}}, facets=null, name='null']
facets=Optional.empty

The v2/api-docs?group=api endpoint is working and it worked before upgrading to version 3.0.0.
Following operation/rest controller seems to trigger this (kotlin):

```
import io.swagger.annotations.Api
import io.swagger.annotations.ApiOperation
import io.swagger.annotations.ApiParam
import org.springframework.http.HttpStatus
import org.springframework.http.MediaType.APPLICATION_JSON_VALUE
import org.springframework.web.bind.annotation.RequestBody
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RequestMethod.POST
import org.springframework.web.bind.annotation.ResponseStatus
import org.springframework.web.bind.annotation.RestController

@RestController
@Api(tags = ["some tag"])
@Deprecated("no longer supported. ")
class RestController(private val service: SomeService) {
    @RequestMapping(path = [URL_CALL], method = [POST], consumes = [APPLICATION_JSON_VALUE])
    @ApiOperation(value = "Logs and stores a message")
    @ResponseStatus(value = HttpStatus.NO_CONTENT)
    fun call(
            @RequestBody
            @ApiParam(name = "call", value = "data to be stored")
            call: MutableMap<String, Any?>) {
        service.log(call)
    }

    companion object {
        const val URL_CALL = "api" + "/calls"
    }
}```

**Comment by suguiura** [comment]
I could reproduce the NullPointerException problem with the following minimal controller:

    import io.swagger.annotations.ApiOperation;
    import org.springframework.http.MediaType;
    import org.springframework.web.bind.annotation.PostMapping;
    import org.springframework.web.bind.annotation.RestController;

    @RestController
    public class TestController {

        @ApiOperation("an endpoint")
        @PostMapping(value = "/endpoint/", consumes = MediaType.APPLICATION_JSON_VALUE)
        public void endpoint () {
            // do stuff here
        }

    }

From my experiments, it seems `consumes` at `@PostMapping` is not handled well with `DocumentationType.OAS_30`, even though it was OK with `DocumentationType.SWAGGER_2`. So, if you take this argument off, the exception is not thrown; however, this is not a workaround.

Just in case, here is the Application I used:

    import org.springframework.boot.SpringApplication;
    import org.springframework.boot.autoconfigure.SpringBootApplication;
    import org.springframework.context.annotation.Bean;
    import springfox.documentation.spi.DocumentationType;
    import springfox.documentation.spring.web.plugins.Docket;

    @SpringBootApplication
    public class Application {

        public static void main (String[] args) {
            SpringApplication.run(Application.class, args);
        }

        @Bean
        public Docket docket () {
            return new Docket(DocumentationType.OAS_30);
        }

    }

**Comment by illidan80** [comment]
Confirming, experiencing the same. Issue happens only when providing "@ApiOperation". Without it, everything works.

Any ETA for fix?

**Comment by illidan80** [comment]
BTW, workaround is to return ResponseEntity<String> instead of void, like this:

```
@RestController
public class TestController {

    @ApiOperation("an endpoint")
    @PostMapping(value = "/endpoint/", consumes = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<String> endpoint () {
        // do stuff here
       return ResponseEntity.ok().build();
    }
}
```

**Comment by kdebski85** [comment]
I confirm that returning ResponseEntity instead of void is a working workaround.

It is best to return `ResponseEntity<Void>`.
You can return it with `ResponseEntity.noContent().build()`.

I did some debugging and SchemaMapper fails when it tries to map response code 200. But there should not be that code at all. Void methods use result code 204 to indicate success.

**Comment by christophejan** [comment]
So if I’m not mistaken, now, to specify a 201 with location header, without 200 OK, I must :
* specify a 201 @ApiResponse with the location header
* Return ResponseEntity.created
* Specify @ResponseStatus(HttpStatus.CREATED) to avoid 200 OK in Springfox contract

It seems a bit redundant... With previous Springfox versions and void methods, there was no need of the ResponseEntity.created...

**Comment by marcus-li** [comment]
> So if I’m not mistaken, now, to specify a 201 with location header, without 200 OK, I must :
> 
> * specify a 201 @ApiResponse with the location header
> * Return ResponseEntity.created
> * Specify @ResponseStatus(HttpStatus.CREATED) to avoid 200 OK in Springfox contract
> 
> It seems a bit redundant... With previous Springfox versions and void methods, there was no need of the ResponseEntity.created...

For anyone else facing this issue: 

This was also frustrating us, a less invasive workaround I was able to get working was to override the automatically derived data type on the ApiOperation by setting the response = String.class, this resolved the NPE and still allows for using a void return type on the method. 

![2021-11-04_11-04-23](https://user-images.githubusercontent.com/7215543/140338883-d013eb63-3dca-4bf8-aa04-973609d3aa50.png)


![image](https://user-images.githubusercontent.com/7215543/140338303-9b54306e-63b2-4223-885b-f8c3c08e946f.png)

**Comment by puppylpg** [comment]
> I confirm that returning ResponseEntity instead of void is a working workaround.
> 
> It is best to return `ResponseEntity<Void>`. You can return it with `ResponseEntity.noContent().build()`.
> 
> I did some debugging and SchemaMapper fails when it tries to map response code 200. But there should not be that code at all. Void methods use result code 204 to indicate success.

Seems that return void body still incurs another small problem: Error-ModelName{namespace='java.lang', name='Void'}

https://github.com/springfox/springfox/issues/3476
