### ISSUE TITLE
OAuth2Scheme cannot be cast to OAuth

### ISSUE THREAD

**Issue by CBEPX4EJIOBEK** [springfox/springfox#3604]
Stacktrace: 
```
springfox.documentation.service.OAuth2Scheme cannot be cast to springfox.documentation.service.OAuth
	at springfox.documentation.swagger2.mappers.OAuth2AuthFactory.create(OAuth2AuthFactory.java:35) ~[springfox-swagger2-3.0.0.jar:3.0.0]
	at springfox.documentation.swagger2.mappers.SecurityMapper.lambda$toSecuritySchemeDefinition$0(SecurityMapper.java:60) ~[springfox-swagger2-3.0.0.jar:3.0.0]

```

OAuth2AuthFactory is used for both security schemes: OAuth and OAuth2Scheme (type is "oauth2").
OAuth2AuthFactory:25 makes casting of input to OAuth type but OAuth2Scheme is not OAuth type. 
```
 public SecuritySchemeDefinition create(SecurityScheme input) {
        OAuth oAuth = (OAuth)input;  
        OAuth2Definition definition = new OAuth2Definition();
```

My code:

```
    @Bean
    public Docket securedApi() {
        return new Docket(DocumentationType.OAS_30)
                .select()
                .apis(RequestHandlerSelectors.basePackage(""))
                .paths(PathSelectors.ant("/v1/secured/**"))
                .build()
                .groupName("secured")
                .apiInfo(securedApiInfo())
                .securitySchemes(Collections.singletonList(securityScheme()))
                .securityContexts(Collections.singletonList(securityContext()));
    }

    private SecurityScheme securityScheme() {

        return OAUTH2_CLIENT_CREDENTIALS_FLOW_BUILDER
                .scopes(scopes())
                .name("oauth2")
                .tokenUrl("https://localhost:8080/oauth/token")
                .build();
    }

    private SecurityContext securityContext() {
        return SecurityContext.builder()
                .securityReferences(Collections.singletonList(new SecurityReference.SecurityReferenceBuilder().scopes(scopes())
                        .reference("oauth2").build()))
                .build();
    }
```

**Comment by emmaLP** [comment]
I get the same issue with security scheme is configured as follows:
```
return OAuth2Scheme.OAUTH2_IMPLICIT_FLOW_BUILDER
                .name("oauth")
                .authorizationUrl(props.getIssuer() + "/v1/authorize")
                .tokenUrl(props.getIssuer() + "/v1/token")
                .scopes(List.of(authScope()))
                .build();
```

I've using version 3.0.0

**Comment by Budlee** [comment]
Had a look and issue that I saw was that the Swagger-2 uses the OAuth2AuthFactory with expects the SecurityScheme to be OAuth (which according to comments is for Swagger 1 & 2), the swagger oas uses a different security mapper and does not remap this.

I guess the fix is to use OAuth object for configuring for swagger2 specs
Or allow the OAuth2AuthFactory should accept the instance of OAuth2Scheme

@dilipkrish, happy to put in a PR for this, can you let me know if that is the correct action to take

**Comment by geld0r** [comment]
Is there any workaround or progress on this?

Currently this results in not being able to generate Swagger 2 next to an OpenApi-Spec when  OAuth 2 is used for authentication as removing the OAuth2Scheme breaks the "try-out" feature in Swagger-UI as this is based on OpenApi-Spec.

**Comment by msemik** [comment]
This is still an issue
