### ISSUE TITLE
ParameterMerger#mergedParameters throw NullPointerException  at StartUP

### ISSUE THREAD

**Issue by Wanxp** [springfox/springfox#3631]
Please take the time to search the repository, if your question has already been asked or answered.

- [ ] springfox-swagger2 version is 3.0.0
- [ ] springfox-boot-starter version is 3.0.0
- [ ] springboot version is lasted.

 **Bug report. NullPointerException Occured**
1. condition: when I use ApiImplicitParams as below
```java
@RestController
@Api(tags = "menu manager")
@RequestMapping("v1/menu")
public class MenuController {
    @ApiOperation(value = "get menu by parentId and menuType")
    @ApiImplicitParams({
            @ApiImplicitParam(value = "parentId", example = "1", required = true, paramType = "query"),
            @ApiImplicitParam(value = "menuType", example = "2", required = true, paramType = "query")
    })
    @GetMapping("children/menus")
    public Integer getPlatformAllMenuTree(@RequestParam("parentId") Long parentId, @RequestParam("menuType") Integer menuType) {
          return 1;
    }
}
```
2. output stack:
```stack
java.lang.NullPointerException: null
	at springfox.documentation.builders.ParameterMerger.lambda$mergedParameters$2(ParameterMerger.java:87) ~[springfox-core-3.0.0.jar:3.0.0]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) ~[na:1.8.0_161]
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1359) ~[na:1.8.0_161]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) ~[na:1.8.0_161]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498) ~[na:1.8.0_161]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485) ~[na:1.8.0_161]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_161]
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152) ~[na:1.8.0_161]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_161]
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464) ~[na:1.8.0_161]
	at springfox.documentation.builders.ParameterMerger.mergedParameters(ParameterMerger.java:87) ~[springfox-core-3.0.0.jar:3.0.0]
	at springfox.documentation.builders.ParameterMerger.merged(ParameterMerger.java:64) ~[springfox-core-3.0.0.jar:3.0.0]
	at springfox.documentation.builders.OperationBuilder.parameters(OperationBuilder.java:224) ~[springfox-core-3.0.0.jar:3.0.0]
	at springfox.documentation.swagger.readers.operation.OperationImplicitParametersReader.apply(OperationImplicitParametersReader.java:58) ~[springfox-swagger-common-3.0.0.jar:3.0.0]
	at springfox.documentation.spring.web.plugins.DocumentationPluginsManager.operation(DocumentationPluginsManager.java:144) ~[springfox-spring-web-3.0.0.jar:3.0.0]
	at springfox.documentation.spring.web.readers.operation.ApiOperationReader.read(ApiOperationReader.java:72) ~[springfox-spring-web-3.0.0.jar:3.0.0]
	at springfox.documentation.spring.web.scanners.CachingOperationReader.lambda$new$0(CachingOperationReader.java:43) ~[springfox-spring-web-3.0.0.jar:3.0.0]
	at java.util.HashMap.computeIfAbsent(HashMap.java:1127) ~[na:1.8.0_161]
	at springfox.documentation.spring.web.scanners.CachingOperationReader.read(CachingOperationReader.java:48) ~[springfox-spring-web-3.0.0.jar:3.0.0]
	at springfox.documentation.spring.web.scanners.ApiDescriptionReader.read(ApiDescriptionReader.java:72) ~[springfox-spring-web-3.0.0.jar:3.0.0]
	at springfox.documentation.spring.web.scanners.ApiListingScanner.scan(ApiListingScanner.java:169) ~[springfox-spring-web-3.0.0.jar:3.0.0]
	at springfox.documentation.spring.web.scanners.ApiDocumentationScanner.scan(ApiDocumentationScanner.java:67) ~[springfox-spring-web-3.0.0.jar:3.0.0]
	at springfox.documentation.spring.web.plugins.AbstractDocumentationPluginsBootstrapper.scanDocumentation(AbstractDocumentationPluginsBootstrapper.java:96) [springfox-spring-web-3.0.0.jar:3.0.0]
	at springfox.documentation.spring.web.plugins.AbstractDocumentationPluginsBootstrapper.bootstrapDocumentationPlugins(AbstractDocumentationPluginsBootstrapper.java:82) [springfox-spring-web-3.0.0.jar:3.0.0]
	at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.start(DocumentationPluginsBootstrapper.java:100) [springfox-spring-web-3.0.0.jar:3.0.0]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:182) [spring-context-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:53) [spring-context-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:360) [spring-context-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:158) [spring-context-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:122) [spring-context-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:894) [spring-context-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:162) [spring-boot-2.2.7.RELEASE.jar:2.2.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:553) [spring-context-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) [spring-boot-2.2.7.RELEASE.jar:2.2.7.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) [spring-boot-2.2.7.RELEASE.jar:2.2.7.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.2.7.RELEASE.jar:2.2.7.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-2.2.7.RELEASE.jar:2.2.7.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.2.7.RELEASE.jar:2.2.7.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) [spring-boot-2.2.7.RELEASE.jar:2.2.7.RELEASE]
	at com.mypackage.platform.PlatformWebApplication.main(EtowerPlatformWebApplication.java:25) [classes/:na]

```
3. if I remove ApiImplicitParams, the NPE not happen.
```java
@RestController
@Api(tags = "menu manager")
@RequestMapping("v1/menu")
public class MenuController {
    @ApiOperation(value = "get menu by parentId and menuType")
    @GetMapping("children/menus")
    public Integer getPlatformAllMenuTree(@RequestParam("parentId") Long parentId, @RequestParam("menuType") Integer menuType) {
          return 1;
    }
}
```

**Comment by Wanxp** [comment]
when I cheked out the source file at below:springfox.documentation.builders.ParameterMerger#mergedParameters
```java
  private List<springfox.documentation.service.Parameter> mergedParameters(
      Set<String> paramsToMerge,
      List<springfox.documentation.service.Parameter> existingParameters,
      List<springfox.documentation.service.Parameter> newParams) {
    List<springfox.documentation.service.Parameter> parameters = new ArrayList<>();
    for (springfox.documentation.service.Parameter newParam : newParams) {
      Optional<springfox.documentation.service.Parameter> original = existingParameters.stream()
          .filter(input -> newParam.getName().equals(input.getName())).findFirst();
      if (paramsToMerge.contains(newParam.getName()) && original.isPresent()) {
        if (newParam.getOrder() > original.get().getOrder()) {
          parameters.add(merged(newParam, original.get()));
        } else {
          parameters.add(merged(original.get(), newParam));
        }
      }
    }
    return parameters;
  }
```
It happened because of newParam.getName() is null.

**Comment by unjie** [comment]
use spring boot 2.7.1  , reproduce the problem

**Comment by unjie** [comment]
确定原因是 ApiImplicitParams name 属性没有配置,  设置不允许为null
