### ISSUE TITLE
springfox.documentation.spring.web.plugins.Docket class missing at maven-generated jar

### ISSUE THREAD

**Issue by mucciolo** [springfox/springfox#3748]
Running `mvn clean package && java -jar target/cmexprt-1.0.0.jar` at the base directory of [this](https://github.com/mucciolo/cmexprt) maven Java project with versions:
- Java 1.8
- Maven 3.6.1
- spring-boot-starter-parent 2.3.5.RELEASE
- springfox-boot-starter and springfox-swagger-ui 3.0.0

gets you the following error:

> Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: springfox/documentation/spring/web/plugins/Docket
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
        at java.lang.Class.getMethod0(Class.java:3018)
        at java.lang.Class.getMethod(Class.java:1784)
        at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: springfox.documentation.spring.web.plugins.Docket
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 7 more

I appreciate any idea on how to fix it.

**Comment by mucciolo** [comment]
Solved by adding `spring-boot:repackage` command right after `mvn clean package`
