### ISSUE TITLE
NullPointerException in DefaultModelPropertiesProvider

### ISSUE THREAD

**Issue by 03xb7** [springfox/springfox#433]
Hi,

I having troubles getting swagger-springmvc in my application. At startup, the plugin, crawls my different Controllers and do its stuff but at one point I am getting:

```
java.lang.NullPointerException: null
    at com.mangofactory.swagger.models.property.field.FieldModelPropertyProvider.propertiesForSerialization(FieldModelPropertyProvider.java:49) ~[swagger-models-0.8.8.jar:na]
    at com.mangofactory.swagger.models.property.provider.DefaultModelPropertiesProvider.propertiesForSerialization(DefaultModelPropertiesProvider.java:31) ~[swagger-models-0.8.8.jar:na]
    at com.mangofactory.swagger.models.DefaultModelProvider.properties(DefaultModelProvider.java:101) ~[swagger-models-0.8.8.jar:na]
    at com.mangofactory.swagger.models.DefaultModelProvider.modelFor(DefaultModelProvider.java:58) ~[swagger-models-0.8.8.jar:na]
    at com.mangofactory.swagger.readers.ApiModelReader.execute(ApiModelReader.java:68) ~[swagger-springmvc-0.8.8.jar:na]
    at com.mangofactory.swagger.readers.ApiModelReader.execute(ApiModelReader.java:36) ~[swagger-springmvc-0.8.8.jar:na]
    at com.mangofactory.swagger.core.CommandExecutor.execute(CommandExecutor.java:13) ~[swagger-springmvc-0.8.8.jar:na]
    at com.mangofactory.swagger.scanners.ApiListingScanner.scan(ApiListingScanner.java:96) ~[swagger-springmvc-0.8.8.jar:na]
    at com.mangofactory.swagger.core.SwaggerApiResourceListing.initialize(SwaggerApiResourceListing.java:71) ~[swagger-springmvc-0.8.8.jar:na]
    at com.mangofactory.swagger.plugin.SwaggerSpringMvcPlugin.initialize(SwaggerSpringMvcPlugin.java:361) ~[swagger-springmvc-0.8.8.jar:na]
    at com.mangofactory.swagger.plugin.SwaggerPluginAdapter.onApplicationEvent(SwaggerPluginAdapter.java:43) ~[swagger-springmvc-0.8.8.jar:na]
    at com.mangofactory.swagger.plugin.SwaggerPluginAdapter.onApplicationEvent(SwaggerPluginAdapter.java:21) ~[swagger-springmvc-0.8.8.jar:na]
    at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:96) ~[spring-context-3.2.8.RELEASE.jar:3.2.8.RELEASE]
    at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:334) ~[spring-context-3.2.8.RELEASE.jar:3.2.8.RELEASE]
    at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:948) ~[spring-context-3.2.8.RELEASE.jar:3.2.8.RELEASE]
    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:482) ~[spring-context-3.2.8.RELEASE.jar:3.2.8.RELEASE]
    at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:410) ~[spring-web-3.2.7.RELEASE.jar:3.2.7.RELEASE]
    at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306) ~[spring-web-3.2.7.RELEASE.jar:3.2.7.RELEASE]
    at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:112) [spring-web-3.2.7.RELEASE.jar:3.2.7.RELEASE]
```

Here is my environnement:

JDK7
Maven 3.0.3
swagger-springmvc 0.8.8
spring-webmvc 3.2.7.RELEASE
Configuration with an applicationContext.xml

For the record I am using a stack called Resthub that already provide a [RequestMapingHandlerAdapater](https://github.com/resthub/resthub-spring-stack/blob/resthub-spring-stack-2.1.6/resthub-web/resthub-web-server/src/main/resources/resthubContext.xml). Hence I did not add the `<mvc:annotation-driven/>` tag in my conf file.

Many thanks

**Comment by vivekpandian** [comment]
@htulipe  How did you fix this issue. I am facing similar issue? It's working fine with embdeded container. When i deploy the war to tomcat, i get this exception.   Please look at my stacktrace below :

java.lang.NullPointerException: null
        at springfox.documentation.schema.property.field.FieldModelPropertyProvider.beanDescription(FieldModelPropertyProvider.java:136)
        at springfox.documentation.schema.property.field.FieldModelPropertyProvider.propertiesFor(FieldModelPropertyProvider.java:117)
        at springfox.documentation.schema.property.provider.DefaultModelPropertiesProvider.propertiesFor(DefaultModelPropertiesProvider.java:58)
        at springfox.documentation.schema.DefaultModelProvider.properties(DefaultModelProvider.java:119)
        at springfox.documentation.schema.DefaultModelProvider.modelFor(DefaultModelProvider.java:75)
        at springfox.documentation.spring.web.scanners.ApiModelReader.read(ApiModelReader.java:66)
        at springfox.documentation.spring.web.scanners.ApiListingScanner.scan(ApiListingScanner.java:85)
        at springfox.documentation.spring.web.scanners.ApiDocumentationScanner.scan(ApiDocumentationScanner.java:61)
        at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.scanDocumentation(DocumentationPluginsBootstrapper.java:101)
        at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.onApplicationEvent(DocumentationPluginsBootstrapper.java:87)
        at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.onApplicationEvent(DocumentationPluginsBootstrapper.java:50)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:151)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:128)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:331)
        at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:773)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:140)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:483)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:686)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:320)
        at org.springframework.boot.context.web.SpringBootServletInitializer.run(SpringBootServletInitializer.java:117)
        at org.springframework.boot.context.web.SpringBootServletInitializer.createRootApplicationContext(SpringBootServletInitializer.java:108)
        at org.springframework.boot.context.web.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.java:68)
        at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:175)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5156)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:945)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1768)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

**Comment by dilipkrish** [comment]
@vivekpandian what version of springfox are you using?

**Comment by vivekpandian** [comment]
@dilipkrish 

I am using version 2.0.0

**Comment by htulipe** [comment]
I did not say it explicitly in my last answer but I just provided the json mapper needed by the library.

**Comment by vivekpandian** [comment]
@htulipe   What's the maven dependency that you added ?

**Comment by dilipkrish** [comment]
@vivekpandian Do you have custom HttpMessageConverters? I suspect this problem is because of running it in tomcat 8, which hasn't been tested yet

**Comment by vivekpandian** [comment]
@dilipkrish 

I don't have any custom HttpMessageConverters
