### ISSUE TITLE
NullPointerException thrown on initialisation when @ResponseBody annotation is after public

### ISSUE THREAD

**Issue by chrishuttonch** [springfox/springfox#439]
Hi there,

It seems that when you specify the @ResponseBody after public in a method the following exception is thrown:

[RMI TCP Connection(4)-127.0.0.1] ERROR ContextLoader - Context initialization failed
java.lang.NullPointerException: null
    at com.mangofactory.swagger.models.property.field.FieldModelPropertyProvider.propertiesForSerialization(FieldModelPropertyProvider.java:49) ~[swagger-models-0.8.8.jar:na]
    at com.mangofactory.swagger.models.property.provider.DefaultModelPropertiesProvider.propertiesForSerialization(DefaultModelPropertiesProvider.java:31) ~[swagger-models-0.8.8.jar:na]
    at com.mangofactory.swagger.models.DefaultModelProvider.properties(DefaultModelProvider.java:101) ~[swagger-models-0.8.8.jar:na]
    at com.mangofactory.swagger.models.DefaultModelProvider.modelFor(DefaultModelProvider.java:58) ~[swagger-models-0.8.8.jar:na]
    at com.mangofactory.swagger.readers.ApiModelReader.execute(ApiModelReader.java:68) ~[swagger-springmvc-0.8.8.jar:na]
    at com.mangofactory.swagger.readers.ApiModelReader.execute(ApiModelReader.java:36) ~[swagger-springmvc-0.8.8.jar:na]
    at com.mangofactory.swagger.core.CommandExecutor.execute(CommandExecutor.java:13) ~[swagger-springmvc-0.8.8.jar:na]
    at com.mangofactory.swagger.scanners.ApiListingScanner.scan(ApiListingScanner.java:96) ~[swagger-springmvc-0.8.8.jar:na]
    at com.mangofactory.swagger.core.SwaggerApiResourceListing.initialize(SwaggerApiResourceListing.java:71) ~[swagger-springmvc-0.8.8.jar:na]
    at com.mangofactory.swagger.plugin.SwaggerSpringMvcPlugin.initialize(SwaggerSpringMvcPlugin.java:361) ~[swagger-springmvc-0.8.8.jar:na]
    at com.mangofactory.swagger.plugin.SwaggerPluginAdapter.onApplicationEvent(SwaggerPluginAdapter.java:51) ~[swagger-springmvc-0.8.8.jar:na]
    at com.mangofactory.swagger.plugin.SwaggerPluginAdapter.onApplicationEvent(SwaggerPluginAdapter.java:21) ~[swagger-springmvc-0.8.8.jar:na]
    at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:96) ~[spring-context-3.2.2.RELEASE.jar:3.2.2.RELEASE]
    at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:334) ~[spring-context-3.2.2.RELEASE.jar:3.2.2.RELEASE]
    at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:948) ~[spring-context-3.2.2.RELEASE.jar:3.2.2.RELEASE]
    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:482) ~[spring-context-3.2.2.RELEASE.jar:3.2.2.RELEASE]
    at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:389) ~[spring-web-3.2.2.RELEASE.jar:3.2.2.RELEASE]
    at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:294) ~[spring-web-3.2.2.RELEASE.jar:3.2.2.RELEASE]
    at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:112) [spring-web-3.2.2.RELEASE.jar:3.2.2.RELEASE]
    at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4939) [catalina.jar:7.0.42]
    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5434) [catalina.jar:7.0.42]
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [catalina.jar:7.0.42]
    at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901) [catalina.jar:7.0.42]
    at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877) [catalina.jar:7.0.42]
    at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:633) [catalina.jar:7.0.42]
    at org.apache.catalina.startup.HostConfig.manageApp(HostConfig.java:1551) [catalina.jar:7.0.42]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.6.0_65]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39) ~[na:1.6.0_65]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) ~[na:1.6.0_65]
    at java.lang.reflect.Method.invoke(Method.java:597) ~[na:1.6.0_65]
    at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:301) [tomcat-coyote.jar:7.0.42]
    at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:835) [na:1.6.0_65]
    at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:771) [na:1.6.0_65]
    at org.apache.catalina.mbeans.MBeanFactory.createStandardContext(MBeanFactory.java:622) [catalina.jar:7.0.42]
    at org.apache.catalina.mbeans.MBeanFactory.createStandardContext(MBeanFactory.java:569) [catalina.jar:7.0.42]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.6.0_65]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39) ~[na:1.6.0_65]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) ~[na:1.6.0_65]
    at java.lang.reflect.Method.invoke(Method.java:597) ~[na:1.6.0_65]
    at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:301) [tomcat-coyote.jar:7.0.42]
    at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:835) [na:1.6.0_65]
    at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:771) [na:1.6.0_65]
    at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1455) [na:1.6.0_65]
    at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:75) [na:1.6.0_65]
    at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1296) [na:1.6.0_65]
    at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1388) [na:1.6.0_65]
    at javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:819) [na:1.6.0_65]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.6.0_65]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39) ~[na:1.6.0_65]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) ~[na:1.6.0_65]
    at java.lang.reflect.Method.invoke(Method.java:597) ~[na:1.6.0_65]
    at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:303) [na:1.6.0_65]
    at sun.rmi.transport.Transport$1.run(Transport.java:159) [na:1.6.0_65]
    at java.security.AccessController.doPrivileged(Native Method) [na:1.6.0_65]
    at sun.rmi.transport.Transport.serviceCall(Transport.java:155) [na:1.6.0_65]
    at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:535) [na:1.6.0_65]
    at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:790) [na:1.6.0_65]
    at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:649) [na:1.6.0_65]
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895) [na:1.6.0_65]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918) [na:1.6.0_65]
    at java.lang.Thread.run(Thread.java:695) [na:1.6.0_65]

To solve without changing swagger simply change:

public @ResponseBody MyObject myMethod() {}

to 

@ResponseBody public MyObject myMethod() {}

**Comment by zhouyaohua** [comment]
where to adding an Object Mapper?
