### ISSUE TITLE
Conflict with my bean org.springframework.web.servlet.view.XmlViewResolver

### ISSUE THREAD

**Issue by totomaze** [springfox/springfox#470]
Hi, 
I try to use swagger springmvc 0.8.8 but I have this exception. (it was working fine with the version 0.6.6 )

27/10/2014 12:12:11 PM org.apache.catalina.core.StandardContext listenerStart
SEVERE: Exception sending context initialized event to listener instance of class org.springframework.web.context.ContextLoaderListener
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jsonViewResolver' defined in ServletContext resource [/WEB-INF/presentation-servlet.xml]: Invocation of init method failed; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1512)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:521)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:458)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:296)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:223)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:293)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:628)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:932)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:479)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:410)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:112)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4210)
	at org.apache.catalina.core.StandardContext.start(StandardContext.java:4709)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:799)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:779)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:583)
	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:675)
	at org.apache.catalina.startup.HostConfig.deployDescriptors(HostConfig.java:601)
	at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:502)
	at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1317)
	at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:324)
	at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:142)
	at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1065)
	at org.apache.catalina.core.StandardHost.start(StandardHost.java:822)
	at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1057)
	at org.apache.catalina.core.StandardEngine.start(StandardEngine.java:463)
	at org.apache.catalina.core.StandardService.start(StandardService.java:525)
	at org.apache.catalina.core.StandardServer.start(StandardServer.java:754)
	at org.apache.catalina.startup.Catalina.start(Catalina.java:595)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:289)
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:414)
Caused by: java.lang.NullPointerException
	at com.mangofactory.swagger.models.property.field.FieldModelPropertyProvider.propertiesForSerialization(FieldModelPropertyProvider.java:49)
	at com.mangofactory.swagger.models.property.provider.DefaultModelPropertiesProvider.propertiesForSerialization(DefaultModelPropertiesProvider.java:31)
	at com.mangofactory.swagger.models.DefaultModelProvider.properties(DefaultModelProvider.java:101)
	at com.mangofactory.swagger.models.DefaultModelProvider.modelFor(DefaultModelProvider.java:58)
	at com.mangofactory.swagger.readers.ApiModelReader.execute(ApiModelReader.java:68)
	at com.mangofactory.swagger.readers.ApiModelReader.execute(ApiModelReader.java:36)
	at com.mangofactory.swagger.core.CommandExecutor.execute(CommandExecutor.java:13)
	at com.mangofactory.swagger.scanners.ApiListingScanner.scan(ApiListingScanner.java:96)
	at com.mangofactory.swagger.core.SwaggerApiResourceListing.initialize(SwaggerApiResourceListing.java:71)
	at com.mangofactory.swagger.plugin.SwaggerSpringMvcPlugin.initialize(SwaggerSpringMvcPlugin.java:361)
	at com.mangofactory.swagger.plugin.SwaggerPluginAdapter.onApplicationEvent(SwaggerPluginAdapter.java:51)
	at com.mangofactory.swagger.plugin.SwaggerPluginAdapter.onApplicationEvent(SwaggerPluginAdapter.java:21)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:96)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:334)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:336)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:948)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:482)
	at org.springframework.web.servlet.view.XmlViewResolver.initFactory(XmlViewResolver.java:143)
	at org.springframework.web.servlet.view.XmlViewResolver.afterPropertiesSet(XmlViewResolver.java:91)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1571)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1509)
	... 36 more

Here is my config file :
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:p="http://www.springframework.org/schema/p"
	xmlns:context="http://www.springframework.org/schema/context"
	xmlns:mvc="http://www.springframework.org/schema/mvc"
	xsi:schemaLocation="
        http://www.springframework.org/schema/beans
        http://www.springframework.org/schema/beans/spring-beans-3.2.xsd
        http://www.springframework.org/schema/context
        http://www.springframework.org/schema/context/spring-context-3.2.xsd
        http://www.springframework.org/schema/mvc
        http://www.springframework.org/schema/mvc/spring-mvc-3.2.xsd">

	
	<bean id="sysEnvConfig"
		class="org.springframework.beans.factory.config.PropertyPlaceholderConfigurer">
		<property name="order" value="1" />
		<property name="ignoreUnresolvablePlaceholders" value="true" />
		<property name="systemPropertiesModeName" value="SYSTEM_PROPERTIES_MODE_OVERRIDE" />
	</bean>

	
	<bean id="propertyFileLocations" class="java.util.ArrayList">
		<constructor-arg>
			<list>
				<value>file:${user.home}/o3configuration/online-env.properties
				</value>
				<value>file:${user.home}/o3configuration/o3server.properties</value>
				<value>file:${user.home}/o3configuration/mitchell-corp.properties
				</value>
				<value>classpath:swagger.properties</value>
			</list>
		</constructor-arg>
	</bean>

	
	
	
	<bean id="propertyConfigurer"
		class="org.springframework.beans.factory.config.PropertyPlaceholderConfigurer">
		<property name="order" value="2" />
		<property name="ignoreResourceNotFound" value="true" />
		<property name="locations">
			<ref bean="propertyFileLocations" />
		</property>
	</bean>

 	<bean name="jsonViewResolver" class="org.springframework.web.servlet.view.XmlViewResolver" /> 

	<bean id="viewResolver"
		class="org.springframework.web.servlet.view.InternalResourceViewResolver"
		p:prefix="/WEB-INF/jsp/" p:suffix=".jsp" />

	<bean
		class="org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter" />
	<bean
		class="org.springframework.web.servlet.mvc.annotation.DefaultAnnotationHandlerMapping" />

	<bean id="configurationLoader"
		class="org.springmodules.validation.bean.conf.loader.annotation.AnnotationBeanValidationConfigurationLoader" />
	<bean id="validator" class="org.springmodules.validation.bean.BeanValidator"
		p:configurationLoader-ref="configurationLoader" />

	
	<bean id="messageSource"
		class="org.springframework.context.support.ResourceBundleMessageSource"
		p:basenames="errors" />

	<import resource="classpath:ldap-context.xml" />
	<import resource="classpath:datasource-context.xml" />
	<import resource="classpath:services-context.xml" />

	
	
	
	<bean id="reportsHost" class="java.lang.String">
		<constructor-arg value="${env.reports.server.host}" />
	</bean>
	<bean id="reportsApp" class="java.lang.String">
		<constructor-arg value="${env.reports.server.app}" />
	</bean>

	<bean id="homeController" class="com.ozone.web.controller.HomeController">
		<property name="reportsHost">
			<ref bean="reportsHost" />
		</property>
	</bean>
	<context:component-scan base-package="com.ozone.web" />
	<context:annotation-config />
	<mvc:annotation-driven />
	<mvc:default-servlet-handler />

		<bean id="documentationConfig" class="com.mangofactory.swagger.configuration.SpringSwaggerConfig"/>
</beans>

if I remove this line : <bean name="jsonViewResolver" class="org.springframework.web.servlet.view.XmlViewResolver" />
swagger works fine but I my api stop working.

Is there any solution to keeo my jsonViewResolver with swagger working ?

Thank you

**Comment by navom1** [comment]
I get an error in 'p' for p:objectMapper-ref.  what is that referencing?

**Comment by dilipkrish** [comment]
@navom1 ```xmlns:p="http://www.springframework.org/schema/p"```
