### ISSUE TITLE
Default Error Controller ("Basic Error Controller") - TRACE verb causes NPE in Swagger Codegen-2.1.2-M1 + duplicate nickname-problem

### ISSUE THREAD

**Issue by jfiala** [springfox/springfox#659]
If you launch Swagger codegen (version com.wordnik:swagger-codegen-project:2.1.2M1) (https://github.com/swagger-api/swagger-codegen) on any API provided by Spring Swagger-MVC it will cause a NPE (regardless of language being used):

The error seems to be located in the Swagger Codegen project, not in Spring-Swagger-MVC

com.wordnik.swagger.codegen.Codegen -i http://localhost:8080/api-docs -l java

causes:
```java
java.lang.NullPointerException
	at io.swagger.parser.SwaggerCompatConverter.convert(SwaggerCompatConverter.java:455)
	at io.swagger.parser.SwaggerCompatConverter.read(SwaggerCompatConverter.java:111)
	at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:34)
	at com.wordnik.swagger.codegen.Codegen.main(Codegen.java:88)
```

The SwaggerCompatConverter (located in swagger-compat-spec-parser-1.0.1.jar)  is referenced by SwaggerParser (located in swagger-parser-1.0.1.jar).

Quick fix:
Provide your own customer error converter:

``` Java
@Controller
@ApiIgnore
public class CustomErrorController implements ErrorController {

	private static final String PATH = "/error";

	@Override
	public String getErrorPath() {
		return PATH;
	}
	
	@RequestMapping(method=RequestMethod.GET, value=PATH, produces="application/json")
    @ResponseBody
    public Map<String, Object> handleGet(HttpServletRequest request) {

        Map<String, Object> map = new HashMap<String, Object>();
        map.put("status", request.getAttribute("javax.servlet.error.status_code"));
        map.put("reason", request.getAttribute("javax.servlet.error.message"));

        return map;
    }
	
	@RequestMapping(method=RequestMethod.POST, value=PATH, produces="application/json")
    @ResponseBody
    public Map<String, Object> handlePost(HttpServletRequest request) {

        Map<String, Object> map = new HashMap<String, Object>();
        map.put("status", request.getAttribute("javax.servlet.error.status_code"));
        map.put("reason", request.getAttribute("javax.servlet.error.message"));

        return map;
    }
	
	
}
```
Using this, you can generate the client sources using Swagger Codegen without errors.

With earlier versions of Swagger-Codegen (e.g. the maven integration of com.wordnik:swagger-codegen_2.9.1), this error doesn't occur.

The bug itself is caused by an limitation of Swagger-Codegen, it is only related with the TRACE-verb in the Basic Error Controller. If you remove the TRACE-section in the basic-error-controller-api-docs, it will run without errors:
```
, {
					"method": "TRACE",
					"summary": "error",
					"notes": "error",
					"nickname": "error",
					"produces": ["*/*"],
					"consumes": ["application/json"],
					"parameters": [],
					"responseMessages": [
						{
							"code": 200,
							"message": null,
							"responseModel": "Map«string,object»"
						}
					],
					"deprecated": "false",
					"type": "Map«string,object»"
				}

, {
					"method": "TRACE",
					"summary": "errorHtml",
					"notes": "errorHtml",
					"nickname": "errorHtml",
					"produces": ["text/html"],
					"consumes": ["application/json"],
					"parameters": [],
					"responseMessages": [
						{
							"code": 200,
							"message": null,
							"responseModel": "ModelAndView"
						}
					],
					"deprecated": "false",
					"type": "ModelAndView"
				}
```

**Comment by dilipkrish** [comment]
@jfiala wonder if we should open a bug in swagger-codegen for this?

**Comment by jfiala** [comment]
already answered by the Swagger-codegen team:
https://github.com/swagger-api/swagger-codegen/issues/612

"Swagger doesn't support TRACE for REST calls in general. Other than that, that definition is malformed for using Maps with Swagger 1.2 (which is only supported in 2.0 and is represented differently) and it looks like none of the operations have any parameters which is especially odd for PUT, POST and PATCH requests."

So it seems the HTTP verb TRACE should be removed in Spring-MVC-Swagger.
Regarding the ""Map«string,object»"": this is another issue!

**Comment by dilipkrish** [comment]
@jfiala that issue is fixed in 2.0. There is a ```forCodeGeneration([true|false])``` method. Also I would strongly recommend moving to 2.0 rather than 1.x because its not going to be maintained going forward.

**Comment by jfiala** [comment]
As there is an easy workaround, I think this can be closed and remain unfixed in the 1.x branch.

**Comment by jfiala** [comment]
There is a second error:
After removing the http verb TRACE, Swagger-Codegen generates multiple errorHtml()-methods.

According to Swagger-Codegen the nickname should be unique, but currently is supplied as duplicates in the api-docs.

**Comment by jfiala** [comment]
Using 2.0.0-SNAPSHOT the TRACE http verb is no longer generated.

```
{"swagger":"2.0","info":{"description":"Api Documentation","version":"1.0","title":"Api Documentation","termsOfService":"urn:tos","contact":{"name":"Contact Email"},"license":{"name":"Apache 2.0","url":"http://www.apache.org/licenses/LICENSE-2.0"}},"host":"localhost:8080","basePath":"/","tags":[{"name":"search-services"},{"name":"user-crud-responseentity"},{"name":"user-crud"},{"name":"basic-error-controller"}],"paths":{"/error":{"get":{"tags":["basic-error-controller"],"summary":"error","description":"error","operationId":"error","consumes":["application/json"],"produces":["*/*"],"responses":{"404":{"description":"Not Found"},"200":{"description":"OK","schema":{"type":"object","additionalProperties":{"type":"object"}}},"401":{"description":"Unauthorized"},"403":{"description":"Forbidden"}}},"post":{"tags":["basic-error-controller"],"summary":"error","description":"error","operationId":"error","consumes":["application/json"],"produces":["*/*"],"responses":{"404":{"description":"Not Found"},"200":{"description":"OK","schema":{"type":"object","additionalProperties":{"type":"object"}}},"201":{"description":"Created"},"401":{"description":"Unauthorized"},"403":{"description":"Forbidden"}}},"put":{"tags":["basic-error-controller"],"summary":"error","description":"error","operationId":"error","consumes":["application/json"],"produces":["*/*"],"responses":{"404":{"description":"Not Found"},"200":{"description":"OK","schema":{"type":"object","additionalProperties":{"type":"object"}}},"201":{"description":"Created"},"401":{"description":"Unauthorized"},"403":{"description":"Forbidden"}}},"delete":{"tags":["basic-error-controller"],"summary":"error","description":"error","operationId":"error","consumes":["application/json"],"produces":["*/*"],"responses":{"204":{"description":"No Content"},"200":{"description":"OK","schema":{"type":"object","additionalProperties":{"type":"object"}}},"401":{"description":"Unauthorized"},"403":{"description":"Forbidden"}}},"options":{"tags":["basic-error-controller"],"summary":"error","description":"error","operationId":"error","consumes":["application/json"],"produces":["*/*"],"responses":{"204":{"description":"No Content"},"200":{"description":"OK","schema":{"type":"object","additionalProperties":{"type":"object"}}},"401":{"description":"Unauthorized"},"403":{"description":"Forbidden"}}},"patch":{"tags":["basic-error-controller"],"summary":"error","description":"error","operationId":"error","consumes":["application/json"],"produces":["*/*"],"responses":{"204":{"description":"No Content"},"200":{"description":"OK","schema":{"type":"object","additionalProperties":{"type":"object"}}},"401":{"description":"Unauthorized"},"403":{"description":"Forbidden"}}}},"/search":{"get":{"tags":["search-services"],"summary":"search for users by name-part","description":"search for users","operationId":"searchUsers","consumes":["application/json"],"produces":["*/*"],"parameters":[{"name":"query","in":"query","description":"query","required":true,"type":"string"}],"responses":{"404":{"description":"Not Found"},"200":{"description":"OK","schema":{"type":"array","items":{"$ref":"#/definitions/User"}}},"401":{"description":"Unauthorized"},"403":{"description":"Forbidden"}}}},"/user":{"get":{"tags":["user-crud"],"summary":"read User by ID","description":"pass ID to read user","operationId":"getUser","consumes":["application/json"],"produces":["*/*"],"parameters":[{"name":"id","in":"query","description":"id","required":true,"type":"integer","format":"int64"}],"responses":{"404":{"description":"Not Found"},"200":{"description":"OK","schema":{"$ref":"#/definitions/User"}},"401":{"description":"Unauthorized"},"403":{"description":"Forbidden"}}},"post":{"tags":["user-crud"],"summary":"create or update a user name by id","description":"saveUser","operationId":"saveUser","consumes":["application/json"],"produces":["*/*"],"parameters":[{"name":"id","in":"query","description":"id","required":true,"type":"integer","format":"int64"},{"name":"name","in":"query","description":"name","required":true,"type":"string"}],"responses":{"404":{"description":"Not Found"},"200":{"description":"OK","schema":{"$ref":"#/definitions/User"}},"201":{"description":"Created"},"401":{"description":"Unauthorized"},"403":{"description":"Forbidden"}}}},"/user_with_responseentity":{"get":{"tags":["user-crud-responseentity"],"summary":"getUserResponseEntity","description":"getUserResponseEntity","operationId":"getUserResponseEntity","consumes":["application/json"],"produces":["*/*"],"parameters":[{"name":"id","in":"query","description":"id","required":true,"type":"integer","format":"int64"}],"responses":{"404":{"description":"Not Found"},"200":{"description":"OK","schema":{"type":"object"}},"401":{"description":"Unauthorized"},"403":{"description":"Forbidden"},"500":{"description":"Unexpected Error"}}}}},"definitions":{"User":{"required":["id","name"],"properties":{"bytes":{"type":"array","items":{"type":"string","format":"byte"}},"id":{"type":"integer","format":"int64","description":"ID of the user"},"name":{"type":"string","description":"Name of the user"},"state":{"type":"string","enum":["ACTIVE","DISABLED"]}},"description":"User object"},"View":{"properties":{"contentType":{"type":"string"}}},"ModelAndView":{"properties":{"empty":{"type":"boolean"},"model":{"type":"object"},"modelMap":{"type":"object","additionalProperties":{"type":"object"}},"reference":{"type":"boolean"},"view":{"$ref":"#/definitions/View"},"viewName":{"type":"string"}}}}}
```

However, the operationId is still "error" for all http verbs, so after generating the client code using swagger-codegen-2.1.2-M2, the "BasicerrorcontrollerApi.java" has compile errors: "Duplicate method error() in BasicerrorcontrollerApi".

```
...
/**
   * error
   * error
   * @return Map<String, Object>
   */
  public Map<String, Object> error () throws ApiException {
    Object postBody = null;
...
 String response = apiInvoker.invokeAPI(basePath, path, "GET", queryParams, postBody, headerParams, formParams, contentType);
....
 /**
   * error
   * error
   * @return Map<String, Object>
   */
  public Map<String, Object> error () throws ApiException {
    Object postBody = null;
    

    // create path and map variables
...
String response = apiInvoker.invokeAPI(basePath, path, "PUT", queryParams, postBody, headerParams, formParams, contentType);

**Comment by dilipkrish** [comment]
@jfiala this means they are expecting that the nickname is different for the same method name for different http methods? I'd be curious how they handle it for a jax-rs implementation.

**Comment by jfiala** [comment]
Yes exactly, @webron has put it this way:
https://github.com/swagger-api/swagger-codegen/issues/612
"That looks like a problem with the Swagger definition as well. They all have the same nickname value, and those have to be unique."

**Comment by webron** [comment]
@dilipkrish - the `nickname` indeed has to be unique according to the spec. In swagger-core, we use the actual method name as the nickname to solve the issue. One good thing about 2.0 is that `operationId` (the equivalent to `nickname`) is not mandatory and should be handled by the processing end and not the producing end. This means that you can simply omit it instead of having to worry about generating the value (however, if you do generate it, it still has to be unique). Unfortunately, for 1.2, you still have to generate it.

**Comment by jfiala** [comment]
the nickname problem has been fixed (get suffixed with _<increment> automatically).

Now the "Map«string,object»" in the api-docs of Swagger-Spring 1.0.2 will get converted to "MapÂ«string,objectÂ» " which then causes compile errors.
However, this can easily be workaround by suppressing the basic-error-controller of Swagger-Spring-1.0.2.

```
{"apiVersion":"1.0","apis":[{"description":"errorHtml","operations":[{"method":"GET","summary":"errorHtml","notes":"errorHtml","nickname":"errorHtml","produces":["text/html"],"consumes":["application/json"],"parameters":[],"responseMessages":[{"code":200,"message":null,"responseModel":"ModelAndView"}],"deprecated":"false","type":"ModelAndView"},{"method":"HEAD","summary":"errorHtml","notes":"errorHtml","nickname":"errorHtml","produces":["text/html"],"consumes":["application/json"],"parameters":[],"responseMessages":[{"code":200,"message":null,"responseModel":"ModelAndView"}],"deprecated":"false","type":"ModelAndView"},{"method":"POST","summary":"errorHtml","notes":"errorHtml","nickname":"errorHtml","produces":["text/html"],"consumes":["application/json"],"parameters":[],"responseMessages":[{"code":200,"message":null,"responseModel":"ModelAndView"}],"deprecated":"false","type":"ModelAndView"},{"method":"PUT","summary":"errorHtml","notes":"errorHtml","nickname":"errorHtml","produces":["text/html"],"consumes":["application/json"],"parameters":[],"responseMessages":[{"code":200,"message":null,"responseModel":"ModelAndView"}],"deprecated":"false","type":"ModelAndView"},{"method":"PATCH","summary":"errorHtml","notes":"errorHtml","nickname":"errorHtml","produces":["text/html"],"consumes":["application/json"],"parameters":[],"responseMessages":[{"code":200,"message":null,"responseModel":"ModelAndView"}],"deprecated":"false","type":"ModelAndView"},{"method":"DELETE","summary":"errorHtml","notes":"errorHtml","nickname":"errorHtml","produces":["text/html"],"consumes":["application/json"],"parameters":[],"responseMessages":[{"code":200,"message":null,"responseModel":"ModelAndView"}],"deprecated":"false","type":"ModelAndView"},{"method":"OPTIONS","summary":"errorHtml","notes":"errorHtml","nickname":"errorHtml","produces":["text/html"],"consumes":["application/json"],"parameters":[],"responseMessages":[{"code":200,"message":null,"responseModel":"ModelAndView"}],"deprecated":"false","type":"ModelAndView"},{"method":"TRACE","summary":"errorHtml","notes":"errorHtml","nickname":"errorHtml","produces":["text/html"],"consumes":["application/json"],"parameters":[],"responseMessages":[{"code":200,"message":null,"responseModel":"ModelAndView"}],"deprecated":"false","type":"ModelAndView"}],"path":"/error"},{"description":"error","operations":[{"method":"GET","summary":"error","notes":"error","nickname":"error","produces":["*/*"],"consumes":["application/json"],"parameters":[],"responseMessages":[{"code":200,"message":null,"responseModel":"Map«string,object»"}],"deprecated":"false","type":"Map«string,object»"},{"method":"HEAD","summary":"error","notes":"error","nickname":"error","produces":["*/*"],"consumes":["application/json"],"parameters":[],"responseMessages":[{"code":200,"message":null,"responseModel":"Map«string,object»"}],"deprecated":"false","type":"Map«string,object»"},{"method":"POST","summary":"error","notes":"error","nickname":"error","produces":["*/*"],"consumes":["application/json"],"parameters":[],"responseMessages":[{"code":200,"message":null,"responseModel":"Map«string,object»"}],"deprecated":"false","type":"Map«string,object»"},{"method":"PUT","summary":"error","notes":"error","nickname":"error","produces":["*/*"],"consumes":["application/json"],"parameters":[],"responseMessages":[{"code":200,"message":null,"responseModel":"Map«string,object»"}],"deprecated":"false","type":"Map«string,object»"},{"method":"PATCH","summary":"error","notes":"error","nickname":"error","produces":["*/*"],"consumes":["application/json"],"parameters":[],"responseMessages":[{"code":200,"message":null,"responseModel":"Map«string,object»"}],"deprecated":"false","type":"Map«string,object»"},{"method":"DELETE","summary":"error","notes":"error","nickname":"error","produces":["*/*"],"consumes":["application/json"],"parameters":[],"responseMessages":[{"code":200,"message":null,"responseModel":"Map«string,object»"}],"deprecated":"false","type":"Map«string,object»"},{"method":"OPTIONS","summary":"error","notes":"error","nickname":"error","produces":["*/*"],"consumes":["application/json"],"parameters":[],"responseMessages":[{"code":200,"message":null,"responseModel":"Map«string,object»"}],"deprecated":"false","type":"Map«string,object»"},{"method":"TRACE","summary":"error","notes":"error","nickname":"error","produces":["*/*"],"consumes":["application/json"],"parameters":[],"responseMessages":[{"code":200,"message":null,"responseModel":"Map«string,object»"}],"deprecated":"false","type":"Map«string,object»"}],"path":"/error"}],"basePath":"/","consumes":["application/json"],"models":{"View":{"description":"","id":"View","properties":{"contentType":{"required":false,"type":"string"}}},"ModelAndView":{"description":"","id":"ModelAndView","properties":{"view":{"required":false,"type":"View"},"model":{"required":false,"type":"object"},"empty":{"required":false,"type":"boolean"},"viewName":{"required":false,"type":"string"},"reference":{"required":false,"type":"boolean"},"modelMap":{"required":false,"type":"ModelMap"}}},"ModelMap":{"description":"","id":"ModelMap","properties":{"empty":{"required":false,"type":"boolean"}}}},"produces":["*/*","text/html"],"resourcePath":"/error","swaggerVersion":"1.2"}
```

**Comment by jfiala** [comment]
In my opinion the generated
suffix "UsingGET" (e.g. getUserUsingGET)
should only be provided as operationId if really necessary = if there are really duplicate operationId's .

Right now using the API is not as simple as before:
before: userApi.getUser(new Long(1));
now: userApi.getUserUsingGET(new Long(1));
Additionally, dealing with duplicate id's is meanwhile fixed at swagger-codegen  (see https://github.com/swagger-api/swagger-codegen/issues/612).

For 2.0 this is now provided as api-docs:

```
{"swagger":"2.0","info":{"description":"Demo Swagger Spring 2 API Description","version":"1.0","title":"My Apps API Title","termsOfService":"My Apps API terms of service","contact":{"name":"My Apps API Contact Email"},"license":{"name":"My Apps API Licence Type","url":"My Apps API License URL"}},"host":"localhost:8080","basePath":"/","tags":[{"name":"basic-error-controller"},{"name":"user-crud"},{"name":"user-crud-responseentity"},{"name":"search-services"}],"paths":{"/error":{"get":{"tags":["basic-error-controller"],"summary":"error","description":"error","operationId":"errorUsingGET","consumes":["application/json"],"produces":["*/*"],"responses":{"404":{"description":"Not Found"},"200":{"description":"OK","schema":{"type":"object","additionalProperties":{"type":"object"}}},"401":{"description":"Unauthorized"},"403":{"description":"Forbidden"}}},"post":{"tags":["basic-error-controller"],"summary":"error","description":"error","operationId":"errorUsingPOST","consumes":["application/json"],"produces":["*/*"],"responses":{"404":{"description":"Not Found"},"200":{"description":"OK","schema":{"type":"object","additionalProperties":{"type":"object"}}},"201":{"description":"Created"},"401":{"description":"Unauthorized"},"403":{"description":"Forbidden"}}},"put":{"tags":["basic-error-controller"],"summary":"error","description":"error","operationId":"errorUsingPUT","consumes":["application/json"],"produces":["*/*"],"responses":{"404":{"description":"Not Found"},"200":{"description":"OK","schema":{"type":"object","additionalProperties":{"type":"object"}}},"201":{"description":"Created"},"401":{"description":"Unauthorized"},"403":{"description":"Forbidden"}}},"delete":{"tags":["basic-error-controller"],"summary":"error","description":"error","operationId":"errorUsingDELETE","consumes":["application/json"],"produces":["*/*"],"responses":{"204":{"description":"No Content"},"200":{"description":"OK","schema":{"type":"object","additionalProperties":{"type":"object"}}},"401":{"description":"Unauthorized"},"403":{"description":"Forbidden"}}},"options":{"tags":["basic-error-controller"],"summary":"error","description":"error","operationId":"errorUsingOPTIONS","consumes":["application/json"],"produces":["*/*"],"responses":{"204":{"description":"No Content"},"200":{"description":"OK","schema":{"type":"object","additionalProperties":{"type":"object"}}},"401":{"description":"Unauthorized"},"403":{"description":"Forbidden"}}},"patch":{"tags":["basic-error-controller"],"summary":"error","description":"error","operationId":"errorUsingPATCH","consumes":["application/json"],"produces":["*/*"],"responses":{"204":{"description":"No Content"},"200":{"description":"OK","schema":{"type":"object","additionalProperties":{"type":"object"}}},"401":{"description":"Unauthorized"},"403":{"description":"Forbidden"}}}},"/search":{"get":{"tags":["search-services"],"summary":"search for users by name-part","description":"search for users","operationId":"searchUsersUsingGET","consumes":["application/json"],"produces":["*/*"],"parameters":[{"name":"query","in":"query","description":"query","required":true,"type":"string"}],"responses":{"404":{"description":"Not Found"},"200":{"description":"OK","schema":{"type":"array","items":{"$ref":"#/definitions/User"}}},"401":{"description":"Unauthorized"},"403":{"description":"Forbidden"}}}},"/user":{"get":{"tags":["user-crud"],"summary":"read User by ID","description":"pass ID to read user","operationId":"getUserUsingGET","consumes":["application/json"],"produces":["*/*"],"parameters":[{"name":"id","in":"query","description":"id","required":true,"type":"integer","format":"int64"}],"responses":{"404":{"description":"Not Found"},"200":{"description":"OK","schema":{"$ref":"#/definitions/User"}},"401":{"description":"Unauthorized"},"403":{"description":"Forbidden"}}},"post":{"tags":["user-crud"],"summary":"create or update a user name by id","description":"saveUser","operationId":"saveUserUsingPOST","consumes":["application/json"],"produces":["*/*"],"parameters":[{"name":"id","in":"query","description":"id","required":true,"type":"integer","format":"int64"},{"name":"name","in":"query","description":"name","required":true,"type":"string"}],"responses":{"404":{"description":"Not Found"},"200":{"description":"OK","schema":{"$ref":"#/definitions/User"}},"201":{"description":"Created"},"401":{"description":"Unauthorized"},"403":{"description":"Forbidden"}}}},"/user_with_responseentity":{"get":{"tags":["user-crud-responseentity"],"summary":"getUserResponseEntity","description":"getUserResponseEntity","operationId":"getUserResponseEntityUsingGET","consumes":["application/json"],"produces":["*/*"],"parameters":[{"name":"id","in":"query","description":"id","required":true,"type":"integer","format":"int64"}],"responses":{"404":{"description":"Not Found"},"200":{"description":"OK","schema":{"type":"object"}},"401":{"description":"Unauthorized"},"403":{"description":"Forbidden"},"500":{"description":"Unexpected Error"}}}}},"definitions":{"User":{"required":["id","name"],"properties":{"bytes":{"type":"array","items":{"type":"string","format":"byte"}},"id":{"type":"integer","format":"int64","description":"ID of the user"},"name":{"type":"string","description":"Name of the user"},"state":{"type":"string","enum":["ACTIVE","DISABLED"]}},"description":"User object"},"View":{"properties":{"contentType":{"type":"string"}}},"ModelAndView":{"properties":{"empty":{"type":"boolean"},"model":{"type":"object"},"modelMap":{"type":"object","additionalProperties":{"type":"object"}},"reference":{"type":"boolean"},"view":{"$ref":"#/definitions/View"},"viewName":{"type":"string"}}}}}
```

generated code (sample UserApi):

```java
package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.ApiInvoker;

import io.swagger.client.model.*;

import java.util.*;

import io.swagger.client.model.User;


import com.sun.jersey.multipart.FormDataMultiPart;
import com.sun.jersey.multipart.file.FileDataBodyPart;

import javax.ws.rs.core.MediaType;

import java.io.File;
import java.util.Map;
import java.util.HashMap;


public class UsercrudApi {
  String basePath = "https://localhost:8080/";
  ApiInvoker apiInvoker = ApiInvoker.getInstance();

  public ApiInvoker getInvoker() {
    return apiInvoker;
  }

  public void setBasePath(String basePath) {
    this.basePath = basePath;
  }

  public String getBasePath() {
    return basePath;
  }

  
  /**
   * read User by ID
   * pass ID to read user
   * @param id id
   * @return User
   */
  public User getUserUsingGET (Long id) throws ApiException {
    Object postBody = null;
    

    // create path and map variables
    String path = "/user".replaceAll("\\{format\\}","json");

    // query params
    Map<String, String> queryParams = new HashMap<String, String>();
    Map<String, String> headerParams = new HashMap<String, String>();
    Map<String, String> formParams = new HashMap<String, String>();

    if (id != null)
      queryParams.put("id", ApiInvoker.parameterToString(id));
    
    
    String[] contentTypes = {
      "application/json",
    };

    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if(contentType.startsWith("multipart/form-data")) {
      boolean hasFields = false;
      FormDataMultiPart mp = new FormDataMultiPart();
      
      if(hasFields)
        postBody = mp;
    }
    else {
      
    }

    try {
      String response = apiInvoker.invokeAPI(basePath, path, "GET", queryParams, postBody, headerParams, formParams, contentType);
      if(response != null){
        return (User) ApiInvoker.deserialize(response, "", User.class);
      }
      else {
        return null;
      }
    } catch (ApiException ex) {
      throw ex;
    }
  }
  
  /**
   * create or update a user name by id
   * saveUser
   * @param id id
   * @param name name
   * @return User
   */
  public User saveUserUsingPOST (Long id, String name) throws ApiException {
    Object postBody = null;
    

    // create path and map variables
    String path = "/user".replaceAll("\\{format\\}","json");

    // query params
    Map<String, String> queryParams = new HashMap<String, String>();
    Map<String, String> headerParams = new HashMap<String, String>();
    Map<String, String> formParams = new HashMap<String, String>();

    if (id != null)
      queryParams.put("id", ApiInvoker.parameterToString(id));
    if (name != null)
      queryParams.put("name", ApiInvoker.parameterToString(name));
    
    
    String[] contentTypes = {
      "application/json",
    };

    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if(contentType.startsWith("multipart/form-data")) {
      boolean hasFields = false;
      FormDataMultiPart mp = new FormDataMultiPart();
      
      if(hasFields)
        postBody = mp;
    }
    else {
      
    }

    try {
      String response = apiInvoker.invokeAPI(basePath, path, "POST", queryParams, postBody, headerParams, formParams, contentType);
      if(response != null){
        return (User) ApiInvoker.deserialize(response, "", User.class);
      }
      else {
        return null;
      }
    } catch (ApiException ex) {
      throw ex;
    }
  }
  
}

```

**Comment by adrianbk** [comment]
This feels like something we should make a call on before releasing - it's likely to be the type of behaviour we wont be able to change without a breaking change! 

For the swagger 2.0 spec should we completely ignore operationId and never return it? @webron it's unclear from the spec what the purpose operationId serves.. what is the history behind it and do you ever see it being something necessary?

**Comment by jfiala** [comment]
Of course this is also a main topic, it would break all existing generated API clients and have them manually updated.
I don't think the minor bug in the basic-error-controller is that worth.
My suggestion would be to leave everything as it is and simply fix the basic-error-controller to not use duplicate operationId's (as with any Java class that compiles).

**Comment by webron** [comment]
In 2.0, `operationId` is what `nickname` was in 1.2 and prior. It still has to be unique if used, however, it is no longer mandatory.

After consistent issues with `nickname` generation by libraries, we figures this adds extra complexity there, and it may as well be easier for the consumers to deal with it, making sure they uniquely identify an operation if/as they need it.

For 2.0 this is will not change. After releasing the spec, there have been voices regarding making `operationId` mandatory in future versions of the spec. The reason for that is the ease of navigation when going over a Swagger definition. Personally, I don't think it's right and will vote against it, but cannot guarantee if/when it'll change. Even if it changes, I imagine we'd drop the requirement for uniqueness and again pass the responsibility to the consumer.

Currently swagger-core uses the `nickname` property of `@ApiOperation` or the name of the method, if `nickname` isn't set as the `operationId` of the operation. I believe this is done mostly for backwards compatibility and it is really not required. There is *no guarantee* for uniqueness of value in swagger-core.

If you ask for my opinion - I would not generate it at all for 2.0 definitions.

If you're asking for my opinion

**Comment by adrianbk** [comment]
@webron that was the type of opinion I was after :)

@jfiala not including an optional JSON attribute should not break clients - if clients are relying on an optional attribute they are doing something wrong.

I recall when first spiking 2.0 I was using UUID's for the operationId as a sure way to have them unique. @jfiala it's not quite as simple as unique method names - think about method overloading in java or different spring controller classes  with the same method names.

I reckon we either:
1. Completely omit operationId for 2.0
2. Include operationId for 2.0 as UUID's which are truly unique and do not cary any semantics that clients may rely on.

@dilipkrish what't your thoughts? I'm leaning towards no.1

**Comment by jfiala** [comment]
@adrianbk I'm not sure if this is actually a good idea.
Right now, the operationId is the only true hint to the "real" java method name.
Swagger-Codegen so far uses primarily the operationId, and only tries to assemble the method name from the path in a fallback (see DefaultCodegen.java, line 659ff).
So to maintain backwards-compatibility the operationId should at least be includable as the Java method name.

What about adding a configuration parameter to the configuration class whether Java method names should be exposed as operationId (you could turn it off by default if you prefer option 1 above)? Thus people wanting to use their Java method names also from outside the container can do so.

**Comment by webron** [comment]
@adrianbk - using UUID for opertaionId is not a good idea. The operationId is used as an identifier for the operation and various tools (like the codegen) would use that as the identifier. I doubt you'd want to have a method name created from a UUID :)

This is also the reason I prefer the operationId to be left out. Different languages have different naming standards. Some use camel case, some snake case and so on, and the process of evaluating an existing standard, parse it, and reformat it to a different naming standard is a true pain. Imagine generating the operationId from Java and then auto-generating a library for it in python or ruby. Think of the tears and curse words.

**Comment by dilipkrish** [comment]
I prefer the option of leaving it out myself. The uniqueness of the operation is a combination of path+httpMethod. We shouldn't ever need a manufactured unique id IMHO. 

As far as reverting it; lets keep the mechanics but ignore in the mapping layer. That way it just won't be rendered. Since @webron indicated it might resurface as a required property. I can make that fix if everyone's cool with it.

**Comment by adrianbk** [comment]
@webron I agree, the producer should not be client agnostic! The clients need to find a different way to generate method names! It also leaks out the internals of the server side API.

I'm now fully convinced we should drop the operationId.

**Comment by adrianbk** [comment]
@dilipkrish :+1:

**Comment by adrianbk** [comment]
@jfiala I appreciate where you are coming from with regard to swagger codegen but I think swagger codegen needs to find a different mechanism for generating method names. It's completely a client concern, not a producer concern.

**Comment by jfiala** [comment]
@adrianbk: I agree, but I think leaving a configuration to still expose the operationId (and mark it deprecated / remove with next release) would be fine.

**Comment by who** [comment]
This is tricky. 

While I agree that this is not a producer concern, the removal of operationId will likely cause prevent user-friendly function names from being generated from a swagger spec, especially for APIs that use path predicates in their URIs, use URI versioning, or use REST sub-resources.

Here's a sample of generated PHP showing the result of the missing operationID:

URI:
`HTTP DELETE /api/v1/library/magazines/{magazine}`

Generated from operationID before: 
`deleteMagazine($magazine)`

And after, generated from path + verb: 
`apiV1LibraryMagazinesMagazineDelete($magazine)`

**Comment by dilipkrish** [comment]
Tricky it is! Thats why we went back and forth on this. When you're using a generator, I doubt everyone can or will be satisfied by the the aesthetics of the generated code in the context of a host codebase. A great example is the de/serialization code that is generated using the a protobuf definition. 

In any-case per the spec this is optional. And it seems like code-gen is setup to handle it.

**Comment by who** [comment]
After this change, I would not be surprised if some devs overload other fields (tags, description, or summary) to "serialize" the concept of operationId in order to give the generator hints as to how it should name things.  

Here's a quick-and-dirty:

```
...
"tags" : [
"generator-fn:deleteMagazine"
]
...
```

**Comment by jfiala** [comment]
As I said earlier before I think it would be nice to allow the user to configure it, so it's up to the user if he wants to expose the API Java method names or not.

**Comment by webron** [comment]
@who - can't keep everyone happy, and I promise you that with any solution, some people would complain. The vendor extensions can be used for that as well, sure. The codegen's naming logic can also be modified to suit the user's needs. Ultimately, I believe the proper place for the logic management is in the consumer and not the producer. You mentioned the `deleteMagazine($magazine)` example? Try doing that in python and let's see if people won't complain about it.

**Comment by wing328** [comment]
I agree with @jfiala to allow the user to configure the method name (`operationId`). If the user does not like the default method name, he/she can simply supply one that he/she prefers.

**Comment by who** [comment]
@wing328 :+1: 

OperationId should be a possibility. If we are worried that it will cause too many problems by being on by default, we could make it disabled by default, and you'd have to turn it on when setting up your `Docket`.

**Comment by webron** [comment]
I think the original idea of @dilipkrish and @adrianbk was related to not *auto-generating* the `opeartionId`. I believe a user of the library should be allowed to add it manually, it's the auto-generation that's a catch. By the way, for the code-generator I believe it would be just as useful to allow the end user to choose to ignore `opeartionId` even if one was provided.
