### ISSUE TITLE
Swagger 2.1.2 deployment Error - Error creating bean with name 'apiDescriptionReader'

### ISSUE THREAD

**Issue by GLE81** [springfox/springfox#899]
Hi,

I'm trying to integrate swagger with springMVC application, but when I deploy the application the followed error appear.
```log
ago 07, 2015 1:19:23 PM org.apache.catalina.core.StandardContext listenerStart
SEVERE: Excepción enviando evento inicializado de contexto a instancia de escuchador de clase org.springframework.web.context.ContextLoaderListener
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'apiDescriptionReader' defined in URL [jar:file:/K:/Development/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/notificationsApi/WEB-INF/lib/springfox-spring-web-2.1.2.jar!/springfox/documentation/spring/web/scanners/ApiDescriptionReader.class]: Unsatisfied dependency expressed through constructor argument with index 0 of type [springfox.documentation.spring.web.readers.operation.ApiOperationReader]: : Error creating bean with name 'apiOperationReader' defined in URL [jar:file:/K:/Development/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/notificationsApi/WEB-INF/lib/springfox-spring-web-2.1.2.jar!/springfox/documentation/spring/web/readers/operation/ApiOperationReader.class]: Initialization of bean failed; nested exception is org.springframework.aop.framework.AopConfigException: Could not generate CGLIB subclass of class [class springfox.documentation.spring.web.readers.operation.ApiOperationReader]: Common causes of this problem include using a final class or a non-visible class; nested exception is java.lang.IllegalArgumentException: Superclass has no null constructors but no arguments were given; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'apiOperationReader' defined in URL [jar:file:/K:/Development/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/notificationsApi/WEB-INF/lib/springfox-spring-web-2.1.2.jar!/springfox/documentation/spring/web/readers/operation/ApiOperationReader.class]: Initialization of bean failed; nested exception is org.springframework.aop.framework.AopConfigException: Could not generate CGLIB subclass of class [class springfox.documentation.spring.web.readers.operation.ApiOperationReader]: Common causes of this problem include using a final class or a non-visible class; nested exception is java.lang.IllegalArgumentException: Superclass has no null constructors but no arguments were given
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:752)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:193)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1077)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:981)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:487)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:458)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:293)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:223)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:290)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:191)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:636)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:934)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:479)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:410)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:112)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4701)
	at org.apache.catalina.core.StandardContext$1.call(StandardContext.java:5204)
	at org.apache.catalina.core.StandardContext$1.call(StandardContext.java:5199)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:722)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'apiOperationReader' defined in URL [jar:file:/K:/Development/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/notificationsApi/WEB-INF/lib/springfox-spring-web-2.1.2.jar!/springfox/documentation/spring/web/readers/operation/ApiOperationReader.class]: Initialization of bean failed; nested exception is org.springframework.aop.framework.AopConfigException: Could not generate CGLIB subclass of class [class springfox.documentation.spring.web.readers.operation.ApiOperationReader]: Common causes of this problem include using a final class or a non-visible class; nested exception is java.lang.IllegalArgumentException: Superclass has no null constructors but no arguments were given
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:529)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:458)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:293)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:223)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:290)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:191)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:921)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:864)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:779)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:817)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:745)
	... 23 more
Caused by: org.springframework.aop.framework.AopConfigException: Could not generate CGLIB subclass of class [class springfox.documentation.spring.web.readers.operation.ApiOperationReader]: Common causes of this problem include using a final class or a non-visible class; nested exception is java.lang.IllegalArgumentException: Superclass has no null constructors but no arguments were given
	at org.springframework.aop.framework.CglibAopProxy.getProxy(CglibAopProxy.java:218)
	at org.springframework.aop.framework.ProxyFactory.getProxy(ProxyFactory.java:109)
	at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.createProxy(AbstractAutoProxyCreator.java:479)
	at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.wrapIfNecessary(AbstractAutoProxyCreator.java:364)
	at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.postProcessAfterInitialization(AbstractAutoProxyCreator.java:324)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:409)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1520)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:521)
	... 33 more
Caused by: java.lang.IllegalArgumentException: Superclass has no null constructors but no arguments were given
	at org.springframework.cglib.proxy.Enhancer.emitConstructors(Enhancer.java:721)
	at org.springframework.cglib.proxy.Enhancer.generateClass(Enhancer.java:499)
	at org.springframework.cglib.transform.TransformingClassGenerator.generateClass(TransformingClassGenerator.java:33)
	at org.springframework.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
	at org.springframework.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:216)
	at org.springframework.cglib.proxy.Enhancer.createHelper(Enhancer.java:377)
	at org.springframework.cglib.proxy.Enhancer.create(Enhancer.java:285)
	at org.springframework.aop.framework.CglibAopProxy.getProxy(CglibAopProxy.java:206)
	... 40 more
```
This is my configuration:

pom.xml
```xml
<dependency>
		    <groupId>io.springfox</groupId>
		    <artifactId>springfox-spring-web</artifactId>
		    <version>2.1.2</version>
		</dependency>
		<dependency>
		    <groupId>io.springfox</groupId>
		    <artifactId>springfox-swagger2</artifactId>
		    <version>2.1.2</version>
		</dependency>
		<dependency>
		    <groupId>io.springfox</groupId>
		    <artifactId>springfox-swagger-ui</artifactId>
		    <version>2.1.2</version>
		</dependency>
		<dependency>
		  <groupId>org.ajar</groupId>
		  <artifactId>swagger-spring-mvc-ui</artifactId>
		  <version>0.4</version>
		</dependency>
		<dependency>
			<groupId>com.google.guava</groupId>
			<artifactId>guava</artifactId>
			<version>19.0-rc1</version>
		</dependency>
```
applicationContext.xml
```xml
        <bean class="com.test.notifications.config.SwaggerConfig" />
```
SwaggerConfig.java
```java
@EnableSwagger2
@Configuration
@ComponentScan(basePackages = "com.test.notifications.controller")
public class SwaggerConfig {

	  @Bean
	  public Docket swaggerSpringMvcPlugin() {
	    return new Docket(DocumentationType.SWAGGER_2)
	            .groupName("business-api")
	            .select() 
	               //Ignores controllers annotated with @CustomIgnore
//	              .apis(not(withClassAnnotation(CustomIgnore.class)) //Selection by RequestHandler
	              .paths(paths()) // and by paths
	              .build()
	            .apiInfo(apiInfo());
//	            .securitySchemes(securitySchemes())
//	            .securityContext(securityContext());
	  }

	  //Here is an example where we select any api that matches one of these paths
	  private Predicate<String> paths() {
	    return or(
	        regex("/service.*"));
	  }
    
	    private ApiInfo apiInfo() {
	        ApiInfo apiInfo = new ApiInfo("1-st Project's REST API",
	                "Write a description of REST API.",
	                "link",
	                "mail",
	                "API License",
	                "link", "");
	        return apiInfo;
	    }
}
```

and in the Controller class
```java
@Controller
@RequestMapping("/service/notification")
@Api(value="/service/notification" , description = "Operations about Notification services")
public class NotificationController {
.
.
.
@RequestMapping(value="/email/{id}",method = RequestMethod.POST, headers = "Accept=application/json")
    @ApiOperation(value = "Emails",
    	notes = "This is an async method to send emails.")
    @ApiResponses(value = { @ApiResponse(code = 500, message = "Internal Server Error"),
    @ApiResponse(code = 200, message = "Emails registrated") })
.
.
}
```

Another thing is that I tried to integrate my application with version 1.0.2, the deployment was fine but I didn't get information about my rest services in the "api-docs" path, just show:

```json
{"apiVersion":"1.0","swaggerVersion":"1.2","apis":[],"authorizations":[],"info":{"title":"default Title","description":"Api Description","termsOfServiceUrl":"Api terms of service","contact":"Contact Email","license":"Licence Type","licenseUrl":"License URL"}}
```
What can be wrong in my implementation?

**Comment by dilipkrish** [comment]
what version of spring are u using?

**Comment by GLE81** [comment]
Hi, I'm using spring 3.2.5.RELEASE

**Comment by GLE81** [comment]
I migrated the application to spring 4 and now I can see rest documentation. Thanks

**Comment by IoannesPaulus** [comment]
I am having the same issue when using the @EnableSwagger2 annotation.
I use spring 3.2.11.RELEASE, but I cannot move forward to spring 4.
Is spring 3.x not supported? What can I do?

Thanks in advance!

**Comment by dilipkrish** [comment]
@IoannesPaulus could u upgrade to the latest cglib and aspectjrt and see if that fixes your issue?

**Comment by dilipkrish** [comment]
@IoannesPaulus also you may need to downgrade spring-plugin-* to 1.1 but YMMV

**Comment by IoannesPaulus** [comment]
hey @dilipkrish,

Thanks for the quick reply. I upgraded to aspectjrt version 1.8.6 and added cglib version 3.1. I do not use any spring-plugin. Unfortunately I still get the same issue. I downgraded to swagger-springmvc version 1.0.2 in order to use the swagger v1 api. This is working with spring v3.
