### ISSUE TITLE
SpringFox no more compatible with Spring 3.2.x ?

### ISSUE THREAD

**Issue by Abdennebi** [springfox/springfox#901]
Hi, 

I use SpringFox for a year and I'm very happy user and thank you for maintainig an developing this great tool. However, since I switched to the v2, I encounter the following problem:

When I use the annotations *@ApiResponses* the application does not start and the console shows me the following exception:

	java.lang.NoSuchMethodError: org.springframework.http.HttpStatus.is2xxSuccessful()Z
	at springfox.documentation.swagger.readers.operation.SwaggerResponseMessageReader.read(SwaggerResponseMessageReader.java:91)
	at springfox.documentation.swagger.readers.operation.SwaggerResponseMessageReader.apply(SwaggerResponseMessageReader.java:68)
	at springfox.documentation.spring.web.plugins.DocumentationPluginsManager.operation(DocumentationPluginsManager.java:113)
	at springfox.documentation.spring.web.readers.operation.ApiOperationReader.read(ApiOperationReader.java:81)
	at springfox.documentation.spring.web.scanners.ApiDescriptionReader.read(ApiDescriptionReader.java:59)
	at springfox.documentation.spring.web.scanners.ApiListingScanner.scan(ApiListingScanner.java:92)
	at springfox.documentation.spring.web.scanners.ApiDocumentationScanner.scan(ApiDocumentationScanner.java:67)
	at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.scanDocumentation(DocumentationPluginsBootstrapper.java:102)
	at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.onApplicationEvent(DocumentationPluginsBootstrapper.java:88)
	at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.onApplicationEvent(DocumentationPluginsBootstrapper.java:51)

I looked at the code for the class concerned and it seeems that the method is only available in Spring 4.

Can make fix the problem especially that the method is easily replaceable (see the following code excerpt from HttpStatus from Spring 4.x) ?
```java
	/**
	 * Whether this status code is in the HTTP series
	 * {@link HttpStatus.Series#SUCCESSFUL}.
	 * This is a shortcut for checking the value of {@link #series()}.
	 */
	public boolean is2xxSuccessful() {
		return (Series.SUCCESSFUL.equals(series()));
	}
```

**Comment by dilipkrish** [comment]
@Abdennebi if thats the only breaking change then sure thats easily replaceable. PR?

Just FYI our spring dependency is usually one minor version behind springs official released version.
