### ISSUE TITLE
Error while deploying on cloud foundry -::0 can't find referenced pointcut model

### ISSUE THREAD

**Issue by brajput24** [springfox/springfox#916]
hi , tried to deploy my sample app on cloud foundry with swagger2 but getting the below error , same code working fine on my local. I'm using Spring boot with Jdk1.8  . Please help me !

swaggerReleaseVersion='2.1.2'
Here is my config file 
@EnableSwagger2
@Configuration
public class SwaggerConfig  extends WebMvcConfigurerAdapter{
   static final String detailDescription = "Sample ";
    @Bean
    public Docket sampleApi() {
        return new Docket(DocumentationType.SWAGGER_2)
..........

Error : 

2015-08-14T23:04:57.12-0400 [App/0]   OUT [2015-08-15 03:04:57.119] boot - 31  WARN [main] --- AnnotationConfigEmbeddedWebApplicationContext: Exception encountered during context initialization - cancelling refresh attempt
2015-08-14T23:04:57.12-0400 [App/0]   OUT org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'objectMapperConfigurer' defined in class path resource [springfox/documentation/spring/web/SpringfoxWebMvcConfiguration.class]: BeanPostProcessor before instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration': Initialization of bean failed; nested exception is java.lang.IllegalArgumentException: error at ::0 can't find referenced pointcut model
2015-08-14T23:04:57.12-0400 [App/0]   OUT 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:472)
2015-08-14T23:04:57.12-0400 [App/0]   OUT 	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
2015-08-14T23:04:57.12-0400 [App/0]   OUT 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
2015-08-14T23:04:57.12-0400 [App/0]   OUT 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
2015-08-14T23:04:57.12-0400 [App/0]   OUT 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
2015-08-14T23:04:57.12-0400 [App/0]   OUT 	at org.springframework.context.support.PostProcessorRegistrationDelegate.registerBeanPostProcessors(PostProcessorRegistrationDelegate.java:232)
2015-08-14T23:04:57.12-0400 [App/0]   OUT 	at org.springframework.context.support.AbstractApplicationContext.registerBeanPostProcessors(AbstractApplicationContext.java:615)
2015-08-14T23:04:57.12-0400 [App/0]   OUT 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:465)
2015-08-14T23:04:57.12-0400 [App/0]   OUT 	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
2015-08-14T23:04:57.12-0400 [App/0]   OUT 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:686)
2015-08-14T23:04:57.12-0400 [App/0]   OUT 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:320)
2015-08-14T23:04:57.12-0400 [App/0]   OUT 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:957)
2015-08-14T23:04:57.12-0400 [App/0]   OUT 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:946)
2015-08-14T23:04:57.12-0400 [App/0]   OUT 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2015-08-14T23:04:57.12-0400 [App/0]   OUT 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2015-08-14T23:04:57.12-0400 [App/0]   OUT 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2015-08-14T23:04:57.12-0400 [App/0]   OUT 	at java.lang.reflect.Method.invoke(Method.java:497)
2015-08-14T23:04:57.12-0400 [App/0]   OUT 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)
2015-08-14T23:04:57.12-0400 [App/0]   OUT 	at java.lang.Thread.run(Thread.java:745)
2015-08-14T23:04:57.12-0400 [App/0]   OUT Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration': Initialization of bean failed; nested exception is java.lang.IllegalArgumentException: error at ::0 can't find referenced pointcut model
2015-08-14T23:04:57.12-0400 [App/0]   OUT 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:547)
2015-08-14T23:04:57.12-0400 [App/0]   OUT 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
2015-08-14T23:04:57.12-0400 [App/0]   OUT 	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
2015-08-14T23:04:57.12-0400 [App/0]   OUT 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
2015-08-14T23:04:57.12-0400 [App/0]   OUT 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
2015-08-14T23:04:57.12-0400 [App/0]   OUT 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
2015-08-14T23:04:57.12-0400 [App/0]   OUT 	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:368)
2015-08-14T23:04:57.12-0400 [App/0]   OUT 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1119)
2015-08-14T23:04:57.12-0400 [App/0]   OUT 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1014)
2015-08-14T23:04:

**Comment by dilipkrish** [comment]
Looks like it's got something to do with the version of aspectj 

[This SO post](http://stackoverflow.com/questions/10482563/aop-java-lang-illegalargumentexception-error-at-0-cant-find-referenced-poi) looks like it might be your solution.

**Comment by brajput24** [comment]
yes you are right , aspectj version issue , thanks for your help ...

one more question - how can i set swagger-ui default page same as swagger.io
for exp- if i use http://localhost:8080 should auto load swagger ui instead of passing http://localhost:8080/swagger-ui.html  , unsuccessful redirect:swagger-ui.html in my controller

**Comment by dilipkrish** [comment]
Are you able to navigate to `http://localhost:8080/swagger-ui.html` and see swagger-ui successfully loaded? if so Redirecting `/` to should just work.

**Comment by brajput24** [comment]
yes i'm able to see swagger-ui successfully loaded with http://localhost:8080/swagger-ui.html

**Comment by dilipkrish** [comment]
not sure what the problem is then
