### ISSUE TITLE
Issue with codegen c# without RequestParam

### ISSUE THREAD

**Issue by amitbansal012** [springfox/springfox#964]
Hi Team,
The issue is as follows:
Mycode:
>> @Override
    @ApiOperation(value = "This is test service - checkPrimitiveParam")
    @RequestMapping(value = "/checkPrimitiveParam", method = GET)
    @ResponseBody
    public String checkPrimitiveParam(int id, float val, String name) {
        return "works: id:" + id + ", val:" + val + ",name:" + name;
    }

Spec:
>> "/service/testService/checkPrimitiveParam":{"get":{"tags":["test"],"summary":"This is test service - checkPrimitiveParam","operationId":"checkPrimitiveParamUsingGET","consumes":["application/json"],"produces":["*/*"],"parameters":[{"in":"body","name":"id","description":"id","required":false,"schema":{"type":"int"}},{"in":"body","name":"val","description":"val","required":false,"schema":{"type":"float"}},{"in":"body","name":"name","description":"name","required":false,"schema":{"type":"string"}}],"responses":{"200":{"description":"OK","schema":{"type":"string"}},"401":{"description":"Unauthorized"},"403":{"description":"Forbidden"},"404":{"description":"Not Found"}}}}

When i try to do codegen, it gives the following issue:
>> 849 [main] ERROR io.swagger.codegen.DefaultGenerator - Error while trying to get Config from Operation for tag(test)
	Resource: get /service/testService/checkPrimitiveParam
	Operation:io.swagger.models.Operation@b5a325e8
	Definitions: {Bundle=io.swagger.models.ModelImpl@d038d6f0}
java.lang.NullPointerException
	at io.swagger.codegen.DefaultCodegen.fromParameter(DefaultCodegen.java:1206)
	at io.swagger.codegen.DefaultCodegen.fromOperation(DefaultCodegen.java:993)
	at io.swagger.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:462)
	at io.swagger.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:408)
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:177)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:166)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
891 [main] ERROR io.swagger.codegen.DefaultGenerator - Error while trying to get Config from Operation for tag(test)
	Resource: get /service/testService/takeInt
	Operation:io.swagger.models.Operation@3a7c92ee
	Definitions: {Bundle=io.swagger.models.ModelImpl@d038d6f0}
java.lang.NullPointerException
	at io.swagger.codegen.DefaultCodegen.fromParameter(DefaultCodegen.java:1206)
	at io.swagger.codegen.DefaultCodegen.fromOperation(DefaultCodegen.java:993)
	at io.swagger.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:462)
	at io.swagger.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:408)
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:177)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:166)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)

Please look into this.

Thanks,
Amit Bansal

**Comment by dilipkrish** [comment]
This is user error. You cannot have multiple body parameters. Try adding `@RequestParam` to the parameters it should work just fine

**Comment by amitbansal012** [comment]
Hi Dilip,

Thanks for your response. I understand your point. Can you please throw some light on why can we not have multiple body parameters?

On the same context, can you please explain the behavior for issue 14 listed at https://groups.google.com/forum/embed/?place=forum%2Fswagger-swaggersocket#!topic/swagger-swaggersocket/AoNJh01yk_I 

A little context on the same:
>>   public Map<String, String> getMap(@RequestParam Map<String, String> m) ;

,gives issue with swagger-codegen.

Thanks,
Amit

**Comment by amitbansal012** [comment]
Hi,
I got the answer to the first question from http://stackoverflow.com/questions/31033394/swagger-editor-multiple-parameters-in-body . Can you please respond to the second question?

-Amit

**Comment by dilipkrish** [comment]
don't think this case of ```@RequestParam Map<string,string>``` is supported. Keep in mind however that such an open ended Api definition isn't really a good idea.
