### ISSUE TITLE
Error when using GregorianCalendar

### ISSUE THREAD

**Issue by jmandawg** [springfox/springfox#984]
Hi,

When our REST service returns an object containing a GregorianCalendar we get the following Error when running:

08:35:14,347 ERROR [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/customerreference]] (ServerService Thread Pool -- 126) JBWEB000287: Exception sending context initialized event to listener instance of class org.springframework.web.context.ContextLoaderListener: java.lang.IllegalArgumentException: Conflicting setter definitions for property "gregorianChange": java.util.GregorianCalendar#setGregorianChange(1 params) vs java.util.GregorianCalendar#setGregorianChange(1 params)
	at com.fasterxml.jackson.databind.introspect.POJOPropertyBuilder.getSetter(POJOPropertyBuilder.java:303) [jackson-databind-2.4.6.jar:2.4.6]
	at springfox.documentation.schema.Annotations.tryGetSetterAnnotation(Annotations.java:74) [springfox-schema-2.2.2.jar:2.2.2]
	at springfox.documentation.schema.Annotations.findPropertyAnnotation(Annotations.java:48) [springfox-schema-2.2.2.jar:2.2.2]
	at springfox.documentation.swagger.schema.ApiModelPropertyPropertyBuilder.apply(ApiModelPropertyPropertyBuilder.java:45) [springfox-swagger-common-2.2.2.jar:2.2.2]
	at springfox.documentation.schema.plugins.SchemaPluginsManager.property(SchemaPluginsManager.java:51) [springfox-schema-2.2.2.jar:2.2.2]
	at springfox.documentation.schema.property.OptimizedModelPropertiesProvider.beanModelProperty(OptimizedModelPropertiesProvider.java:253) [springfox-schema-2.2.2.jar:2.2.2]
	at springfox.documentation.schema.property.OptimizedModelPropertiesProvider.access$200(OptimizedModelPropertiesProvider.java:78) [springfox-schema-2.2.2.jar:2.2.2]
	at springfox.documentation.schema.property.OptimizedModelPropertiesProvider$1.apply(OptimizedModelPropertiesProvider.java:141) [springfox-schema-2.2.2.jar:2.2.2]
	at springfox.documentation.schema.property.OptimizedModelPropertiesProvider$1.apply(OptimizedModelPropertiesProvider.java:133) [springfox-schema-2.2.2.jar:2.2.2]
	at com.google.common.base.Present.transform(Present.java:71) [guava-18.0.jar:]
	at springfox.documentation.schema.property.OptimizedModelPropertiesProvider.candidateProperties(OptimizedModelPropertiesProvider.java:183) [springfox-schema-2.2.2.jar:2.2.2]
	at springfox.documentation.schema.property.OptimizedModelPropertiesProvider.propertiesFor(OptimizedModelPropertiesProvider.java:125) [springfox-schema-2.2.2.jar:2.2.2]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.7.0_79]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) [rt.jar:1.7.0_79]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.7.0_79]
	at java.lang.reflect.Method.invoke(Method.java:606) [rt.jar:1.7.0_79]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302) [spring-aop-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190) [spring-aop-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) [spring-aop-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:85) [spring-aop-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at springfox.documentation.spring.web.caching.CachingAspect.cachedValue(CachingAspect.java:86) [springfox-spring-web-2.2.2.jar:2.2.2]
	at springfox.documentation.spring.web.caching.CachingAspect.operationsAndProperties(CachingAspect.java:69) [springfox-spring-web-2.2.2.jar:2.2.2]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.7.0_79]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) [rt.jar:1.7.0_79]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.7.0_79]
	at java.lang.reflect.Method.invoke(Method.java:606) [rt.jar:1.7.0_79]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:621) [spring-aop-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:610) [spring-aop-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:68) [spring-aop-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168) [spring-aop-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) [spring-aop-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) [spring-aop-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207) [spring-aop-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at com.sun.proxy.$Proxy312.propertiesFor(Unknown Source)
	at springfox.documentation.schema.ModelDependencyProvider.propertiesFor(ModelDependencyProvider.java:184) [springfox-schema-2.2.2.jar:2.2.2]
	at springfox.documentation.schema.ModelDependencyProvider.nonTrivialProperties(ModelDependencyProvider.java:132) [springfox-schema-2.2.2.jar:2.2.2]
	at springfox.documentation.schema.ModelDependencyProvider.resolvedPropertiesAndFields(ModelDependencyProvider.java:121) [springfox-schema-2.2.2.jar:2.2.2]
	at springfox.documentation.schema.ModelDependencyProvider.resolvedDependencies(ModelDependencyProvider.java:100) [springfox-schema-2.2.2.jar:2.2.2]
	at springfox.documentation.schema.ModelDependencyProvider.maybeFromRegularType(ModelDependencyProvider.java:150) [springfox-schema-2.2.2.jar:2.2.2]
	at springfox.documentation.schema.ModelDependencyProvider.resolvedPropertiesAndFields(ModelDependencyProvider.java:126) [springfox-schema-2.2.2.jar:2.2.2]
	at springfox.documentation.schema.ModelDependencyProvider.resolvedDependencies(ModelDependencyProvider.java:100) [springfox-schema-2.2.2.jar:2.2.2]
	at springfox.documentation.schema.ModelDependencyProvider.dependentModels(ModelDependencyProvider.java:62) [springfox-schema-2.2.2.jar:2.2.2]
	at springfox.documentation.schema.ModelDependencyProvider$$FastClassBySpringCGLIB$$ac0d0878.invoke(<generated>) [spring-core-4.2.1.RELEASE.jar:2.2.2]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) [spring-core-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:717) [spring-aop-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) [spring-aop-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:85) [spring-aop-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at springfox.documentation.spring.web.caching.CachingAspect.cachedValue(CachingAspect.java:86) [springfox-spring-web-2.2.2.jar:2.2.2]
	at springfox.documentation.spring.web.caching.CachingAspect.modelsAndDependencies(CachingAspect.java:80) [springfox-spring-web-2.2.2.jar:2.2.2]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.7.0_79]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) [rt.jar:1.7.0_79]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.7.0_79]
	at java.lang.reflect.Method.invoke(Method.java:606) [rt.jar:1.7.0_79]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:621) [spring-aop-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:610) [spring-aop-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:68) [spring-aop-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168) [spring-aop-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) [spring-aop-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) [spring-aop-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:653) [spring-aop-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at springfox.documentation.schema.ModelDependencyProvider$$EnhancerBySpringCGLIB$$eb8f66a0.dependentModels(<generated>) [spring-core-4.2.1.RELEASE.jar:2.2.2]
	at springfox.documentation.schema.DefaultModelProvider.dependencies(DefaultModelProvider.java:113) [springfox-schema-2.2.2.jar:2.2.2]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.7.0_79]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) [rt.jar:1.7.0_79]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.7.0_79]
	at java.lang.reflect.Method.invoke(Method.java:606) [rt.jar:1.7.0_79]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302) [spring-aop-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190) [spring-aop-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) [spring-aop-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) [spring-aop-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) [spring-aop-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207) [spring-aop-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at com.sun.proxy.$Proxy313.dependencies(Unknown Source)
	at springfox.documentation.spring.web.scanners.ApiModelReader.populateDependencies(ApiModelReader.java:131) [springfox-spring-web-2.2.2.jar:2.2.2]
	at springfox.documentation.spring.web.scanners.ApiModelReader.read(ApiModelReader.java:75) [springfox-spring-web-2.2.2.jar:2.2.2]
	at springfox.documentation.spring.web.scanners.ApiListingScanner.scan(ApiListingScanner.java:91) [springfox-spring-web-2.2.2.jar:2.2.2]
	at springfox.documentation.spring.web.scanners.ApiDocumentationScanner.scan(ApiDocumentationScanner.java:62) [springfox-spring-web-2.2.2.jar:2.2.2]
	at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.scanDocumentation(DocumentationPluginsBootstrapper.java:101) [springfox-spring-web-2.2.2.jar:2.2.2]
	at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.onApplicationEvent(DocumentationPluginsBootstrapper.java:87) [springfox-spring-web-2.2.2.jar:2.2.2]
	at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.onApplicationEvent(DocumentationPluginsBootstrapper.java:50) [springfox-spring-web-2.2.2.jar:2.2.2]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:163) [spring-context-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:136) [spring-context-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:380) [spring-context-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:334) [spring-context-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:850) [spring-context-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:540) [spring-context-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:446) [spring-web-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:328) [spring-web-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107) [spring-web-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.apache.catalina.core.StandardContext.contextListenerStart(StandardContext.java:3339) [jbossweb-7.4.8.Final-redhat-4.jar:7.4.8.Final-redhat-4]
	at org.apache.catalina.core.StandardContext.start(StandardContext.java:3777) [jbossweb-7.4.8.Final-redhat-4.jar:7.4.8.Final-redhat-4]
	at org.jboss.as.web.deployment.WebDeploymentService.doStart(WebDeploymentService.java:161) [jboss-as-web-7.4.0.Final-redhat-19.jar:7.4.0.Final-redhat-19]
	at org.jboss.as.web.deployment.WebDeploymentService.access$000(WebDeploymentService.java:59) [jboss-as-web-7.4.0.Final-redhat-19.jar:7.4.0.Final-redhat-19]
	at org.jboss.as.web.deployment.WebDeploymentService$1.run(WebDeploymentService.java:94) [jboss-as-web-7.4.0.Final-redhat-19.jar:7.4.0.Final-redhat-19]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [rt.jar:1.7.0_79]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [rt.jar:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [rt.jar:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [rt.jar:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_79]
	at org.jboss.threads.JBossThread.run(JBossThread.java:122)

There is only one public setter for setGregorianChange, so I don't really don't know why it is looking at the private setter.   Anyway to fix this?  For now I am @jsonignore all the GregorianCalendar fields and it works, unfortunately we need them.

**Comment by dilipkrish** [comment]
@jmandawg the simplest solution is to provide an alternate type to render dates. For e.g. may be replace `GregorianCalendar` with a java `Date` or even a `String`. It all depends on how to represent the calendar over the wire.

**Comment by jmandawg** [comment]
Thanks, this will work until 2.3.0 :+1:

**Comment by E006840** [comment]
After I update to 2.3.1, I still get the same error as above. Do you know how to fix it?

**Comment by dilipkrish** [comment]
Like it says above, setup a rule to substitute `GregorianCalendar` to `Date` or `String`

```java
    docket.directModelSubstitute(GregorianCalendar.class, Date.class);
//OR
    docket.directModelSubstitute(GregorianCalendar.class, String.class);
```

**Comment by E006840** [comment]
It works now. Thanks!
